### ISSUE TITLE
Bedienung der Bildanalyse ist unelegant

### ISSUE THREAD

**Issue by hzulla** [weg-li/weg-li#10]
Nach dem Hochladen der Fotos muss ich weg-li per Button auffordern, die Bildanalyse zu starten. Danach soll ich warten und den Button noch einmal drücken, um das Ergebnis zu erhalten.

Eleganter wäre, die Analyse startet direkt nach dem Hochladen, es gibt einen [Status-Indikator](https://uxplanet.org/10-creative-loading-indicators-1a15c562b75a) und das Ergebnis wird automatisch nach der Bildanalyse im Formular eingetragen. o.ä.

**Comment by phoet** [comment]
danke für den vorschlag, so ähnlich stelle ich es mir auch vor. für den beta test sollte es primär einfach sein und zuverlässig funktionieren.

**Comment by phoet** [comment]
die analyse wird jetzt beim hochladen angestoßen und es muss nur noch refreshed werden. vorerst werde ich es so lassen. in einer späteren version wird es dann eine art auto-suggest geben, bei der man erkannte angaben übernehmen kann. das ist besonders für den fall praktisch, wo mehrere marken, kennzeichen etc erkannt werden.
