### ISSUE TITLE
googleMaps Ablösung

### ISSUE THREAD

**Issue by riccardoklinger** [weg-li/weg-li#100]
ich würde googlemaps api ausbauen und die Kartendarstellung auf leaflet-basierend mit Openstreetmap betreiben. Geocoding aus den Exif-Daten würde ich erstmal über einen freemium account bei HERE machen, der erlaubt 250.000 Transaktionen (wie geocoding) pro Monat für umsonst. Näheres dazu findet ihr hier:
https://go.engage.here.com/freemium

**Comment by phoet** [comment]
und warum würdest du das machen?

**Comment by riccardoklinger** [comment]
Pricing könnte, sollte die webseite steil gehen, definitiv ein issue werden. Ich denke Here bietet mit dem freemium modell ein bischen mehr puffer bis es etwas kostet. google hat die kOsten für die api nutzung vor kurzem [angepasst](https://gadgets.ndtv.com/apps/features/google-maps-apis-new-pricing-impact-1907242) (erhöht). Die Qualität der [Ergebnisse von HERE i](www.digital-geography.com/comparing-isochrone-apis-an-insight-into-different-providers/)st im Vergleich sehr gut. Und nein, ich arbeite nicht für HERE / bin affiliate.

**Comment by phoet** [comment]
https://github.com/weg-li/weg-li/pull/347
