### ISSUE TITLE
googlemaps api key

### ISSUE THREAD

**Issue by riccardoklinger** [weg-li/weg-li#101]
die app sollte den maps api key nicht hier auf github "exposen". Damit kann ich deine credits ganz schnell aufbrauchen: 
https://github.com/weg-li/weg-li/blob/39bd037af1ad157d3655080aba36799e44b6665d/app/views/layouts/application.html.slim

**Comment by phoet** [comment]
der ist doch ohnehin public

**Comment by riccardoklinger** [comment]
wie, du hast keinen dedizierten key? Wo hast du den Key her? https://developers.google.com/maps/api-key-best-practices
