### ISSUE TITLE
Foto aus Meldung in neue Meldung exportieren

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#102]
Man macht einem Massenupload. Dann gruppiert man die Fotos. Dann geht man in eine Meldung und möchte diese fertig machen. Dabei stellt man fest, dass das erste und letzte Foto anders als zuerst angenommen doch nicht zu dem selben Verstoß gehören mit entsprechen länger Verstoßdauer, sondern das Fahrzeug zwischendurch bewegt wurde. Räder stehen anders. Z.B. Anderer Lenkeinschlag. Dann möchte man gerne das bzw die Fotos von dem zweiten Verstoss des selben Zeitpunktes in einen neue Meldung exportieren und somit statt einem Verstoß mit länger Verstoßdauer zwei Verstöße mit kurzer Verstoßdauer machen.

**Comment by phoet** [comment]
Das habe ich schon mit anderen diskutiert. Für solche Details wird es keine Workflow Unterstützung geben. Löschen, Fotos erneuert hochladen oder duplizieren muss ausreichend sein
