### ISSUE TITLE
Geotagging: Korrigierte Koordinate auf Karte verwenden statt EXIF

### ISSUE THREAD

**Issue by chk1** [weg-li/weg-li#106]
Beim Erstellen einer Meldung habe ich die Adresse einer Meldung über die Karte ermittelt, die vom Smartphone im EXIF hinterlegte Koordinate war in meinem Fall nicht sehr genau (lag auf der gegenüberliegenden Straßenseite, ca. 30m entfernt). 

Nach dem Abschicken der Meldung erscheint diese nun in der öffentlichen Karte & dem Meldungslink wieder an der ursprünglichen, unkorrigierten, Koordinate. Könnte man stattdessen die korrigierte Koordinate verwenden?

**Comment by phoet** [comment]
Ja, das könnte man machen, die Geodaten der Fotos sind zwar nicht immer sehr genau, dafür aber robust zuverlässig, deshalb werden sie im Moment immer bevorzugt.
