### ISSUE TITLE
Fahrzeugfarben: bitte auch die Eingabe eigener Farben erlauben

### ISSUE THREAD

**Issue by Wikinaut** [weg-li/weg-li#109]
Ich benötigte eben Farbe "Blauschwarz", war nicht verfügbar.

**Comment by phoet** [comment]
das feld farbe ist optional, ggf fehlende informationen können im info feld nachgetragen werden

**Comment by Wikinaut** [comment]
Äh, woher soll eine Benutzerin das wissen?

**Comment by phoet** [comment]
pflichtfelder sind wie im internet üblich mit einem "*" markiert
