### ISSUE TITLE
Eine Install/Build-Anleitung wäre nett

### ISSUE THREAD

**Issue by hzulla** [weg-li/weg-li#11]
Für das Github-Repository wäre es hilfreich, in einer [Anleitung](https://github.com/AntennaPod/AntennaPod/wiki/Building-AntennaPod) die Installation aller Abhängigkeiten und der Software selbst zu erklären, damit man schneller eine lokale Test-Installation startklar hat und Features beisteuern kann.

**Comment by phoet** [comment]
👍 was wäre dir persönlich lieber? mit oder ohne docker?

**Comment by hzulla** [comment]
Das ist mir persönlich egal. Wenn Du eh Docker verwenden solltest, dann gerne das. Hauptsache, man hat fix eine Testinstallation lokal online, wenn man (wie ich) kein versierter Rails-Entwickler ist.

**Comment by phoet** [comment]
@hzulla schau doch mal ob dir das hier weiter hilft: https://github.com/weg-li/weg-li#installation

ansonsten stehe ich auch gerne für support bereit
