### ISSUE TITLE
Vor dem Absenden: Problem mit einer erfolgten Eingabe nach Browser-Back-Navigation

### ISSUE THREAD

**Issue by Wikinaut** [weg-li/weg-li#110]
Ich füllte alles aus und wollte vor dem Absenden das Kennzeichen korrigieren (um den "-" Strich ergänzen), benutzte vor dem Absenden "Browser Back".

Die (richtige, vormalige) Eingabe des Tatvorwurfs war zwar noch vorhanden, wurde im weiteren Schritt aber als fehlend moniert. Eine manuelle Neuauswahl desselben Tatvorwurfs behob das Problem.

Bitte mal prüfen, ob da was zu verbessern ist.

**Comment by phoet** [comment]
konnte ich nicht reproduzieren

**Comment by Wikinaut** [comment]
Ich werde bei den nächsten Meldungen versuchen, das zu reproduzieren.
* Firefox 70.0.1
* Linux 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
