### ISSUE TITLE
[Verbesserungsvorschlag] Als Option: Kennzeichen-, Tatvorwurf-Daten, Stadt für die Übernahme in https://fahrerbewertung.de vorbereiten

### ISSUE THREAD

**Issue by Wikinaut** [weg-li/weg-li#111]
Ich fände es nützlich, dass man gleich auch https://fahrerbewertung.de/Kennzeichen aufrufen könnte bzw. die Basisdaten bereits von weg-li nach fbw übernommen würden.

**Comment by phoet** [comment]
solange es keine partnerschaftliche vereinbarung mit fahrerbewertung.de gibt, wird es auch keine solche verlinkung geben.
