### ISSUE TITLE
Duplizieren: Grundsätzlich die Daten der früheren Analyse übernehmen; nur auf Anfrage neu analysieren.

### ISSUE THREAD

**Issue by Wikinaut** [weg-li/weg-li#112]
Beim Duplizieren einer Meldung sind die bisher analysierten Daten nicht vorhanden, zumindest werden diese nicht angezeigt.

Hier empfiehlt es sich, grundsätzlich die Daten der früheren Analyse übernehmen und nur auf explizite Benutzeranfrage neu analysieren zu lassen.

Das "Frühere Analysedaten immer übernehmen" bzw. "Frühere Analysedaten nie übernehmen" sollte ggfs. eine Benutzeroption werden.

**Comment by phoet** [comment]
für welchen use-case soll das gut sein?

derzeit werden die fahrzeugdaten zurückgesetzt, damit man ggf ein weiteres fahrzeug anzeigen kann, dass auf den gleichen fotos enthalten ist.

**Comment by Wikinaut** [comment]
use-case:
Mein gemeldetes Auto steht heute immer noch am gleichen Platz, das habe ich eben erneut gemeldet mit neuer "parkt seit .... " Angabe.

**Comment by phoet** [comment]
closed via 5561fd8ef6881070babca372578d7f353f29ce74
