### ISSUE TITLE
Einreichen der Anzeigen per Post statt E-Mail (PDF-Export zum selber drucken)

### ISSUE THREAD

**Issue by BjarneRest** [weg-li/weg-li#125]
Hallo,

die Stadt Karlsruhe geht Anzeigen von Ordnungswidrigkeiten nur nach, wenn diese in Schriftform eingehen. Daher wäre statt E-Mail ein PDF-Export sicher sinnvoll.

Siehe hier: https://www.karlsruhe.de/b4/buergerdienste/ordnungswidrigkeitenanzeige.de

Viele Grüße, Bjarne

**Comment by phoet** [comment]
die erfahrung zeigt, dass stetiges zuballern mit e-mails und ständiges löchern der beamten deutliche wirkung bei den ordnungsämtern zeigt. irgendwann machen die das dann doch per e-mail.

**Comment by BjarneRest** [comment]
Ich habe letztens 100 Anzeigen (231 Seiten A4) schriftliche eingereicht. Ich bin schon auf das Feedback gespannt. Vielleicht lenken sie ja einAm 01.01.2020 14:34 schrieb Peter Schröder <notifications@github.com>:die erfahrung zeigt, dass stetiges zuballern mit e-mails und ständiges löchern der beamten deutliche wirkung bei den ordnungsämtern zeigt. irgendwann machen die das dann doch per e-mail.

**Comment by phoet** [comment]
@BjarneRest ich habe hier etwas vorarbeit gemacht. wenn du das nächste mal wieder einen schwung ausdrucken willst, dann gib mir bitte bescheid, dann können wir das gemeinsam einmal durchdeklinieren https://github.com/weg-li/weg-li/pull/132

**Comment by stefanhaustein** [comment]
Heisst geschlossen hier dass das nun funktioniert? Ich versuche herauszufinden, was man in der Schweiz machen könnte, und Postversand wäre ein zentraler Aspekt. Praktisch erscheint mir eine Versand per Dienstleister z.B. pingen.com (über einen entsprechenden Account des Endnutzers)?

**Comment by phoet** [comment]
Es werden PDFs generiert.
