### ISSUE TITLE
Photos per Drag&Drop im Browser einfügen

### ISSUE THREAD

**Issue by ValerianHeints** [weg-li/weg-li#127]
es wäre (zumindest imho) eine Zeitersparnis vorhanden, wenn man mehrere Fotos, direkt mittels Drag&Drop in den Browser, einfügen könnte.

1000 Dank für deine Arbeit, Respekt!

**Comment by phoet** [comment]
Welche Zeit sparst du dabei?

**Comment by ValerianHeints** [comment]
1. Beim regelmäßigen Sichtung-/Sortier-Termin meiner Fotos wird ein OWiG-würdiges Foto optisch, im Synology-synchronisierten Uploadverzeichnis, gefunden und die Entscheidung getroffen mittels Weg-li-Anzeige zu erstellen. Die Seite als Tab ist sowieso offen -> Meldung erfassen -> 
- 2.1 "Dateien auswählen" klicken -> zum Synology-synchronisiertem Uploadverzeichnis navigieren -> Zu den Fotos scrollen und verifizieren, und bei der Mehrfachauswahl verifizieren, ob z.B. der Name korrekt ist
- 2.2 Verzeichnis ist im Windows-Explorer bereits an der richtigen Stelle offen: Drag&Drop in den Browserfenster
- 3. Öffnen klicken bzw. loslassen der linken Maustaste
Der zeitliche Unterschied zw. 2.1 und 2.2 liegt bei mir bei geschätzten 2-20 Sekunden.

**Comment by phoet** [comment]
ok, danke für die ausführliche beschreibung. ich finde es immer wichtig zu wissen welche flows die nutzer so haben für sowas.

grundsätzlich erstmal die frage, nutzt du schon den massen-upload? dieses feature erschlägt bei mir lästiges sortieren und filtern, da ich einfach alle fotos mit autos der letzten x stunden/tage/wochen hochlade und dann anschließend zuordne.

die andere frage wäre, ob du schon mal ausprobiert hast in deinem browser die datein direkt auf das file-input-feld zu ziehen. unter OSX wird das soweit ich weiß von den gängigen browsern unterstützt.

**Comment by ValerianHeints** [comment]
Zu 1. Massen-Upload noch nicht ausprobiert, werde ich mir auf jeden Fall angucken ...
Zu 2. Funktioniert! Explorer-Fenster darf die Schaltfläche natürlich nicht verdecken.
Somit wäre nur der größere Bereich für Drag'n'Drop überhaupt von Interesse: Prio: very low oder solved :)

**Comment by phoet** [comment]
ich würde das dannn erstmal schließen. auch weil drag&drop bibliotheken nur ein großer klops workarounds um html und browser sind und ich das nicht gut heißen kann.
