### ISSUE TITLE
Verjährungsfrist beim Datum berücksichtigen

### ISSUE THREAD

**Issue by ValerianHeints** [weg-li/weg-li#128]
imho sollte beim Abschicken ein Hinweis erscheinen, falls sich das Verstoß-Datum bereits außerhalb der Verjährungsfirst befindet.
In Münster (Westf) ist die Verjährungsfrist aktuell bei 3 Monaten.

**Comment by phoet** [comment]
@ValerianHeints das wäre wohl korrekt. ich frage mich nur wie viele leute anzeigen von vor 3 monaten erstatten wollen.

zusätzlich müsste man noch eine bearbeitungszeit im amt dazurechnen, denn die anzeige muss auch binnen 3 monate beim empfänger ankommen.

**Comment by ChawiBiker** [comment]
Man könnte den Request dahingehend ändern, dass lediglich eine Erinnerung erscheint wenn man Bilder hochlädt die älter als x Tage sind.

**Comment by phoet** [comment]
so funktionierts im prinzip. vielleicht verstehe ich nicht was du meinst.
