### ISSUE TITLE
"Mist, da ist was schief gelaufen."

### ISSUE THREAD

**Issue by hzulla** [weg-li/weg-li#13]
Bin eingeloggt auf dem Smartphone.
Gehe zum Desktop-Browser.
Logge mich dort ein.
Fehlermeldung "Mist, da ist was schief gelaufen", Login ist gescheitert.
Logge mich direkt erneut ein.
Klappt.

**Comment by phoet** [comment]
und du loggst dich immer per e-mail ein? der login link ist nur ein paar minuten gültig. ich werde mal das logging an der stelle aufbohren, weil ich sonst nicht sehen kann was das problem ist.

**Comment by hzulla** [comment]
Ich logge mich via github ein.

**Comment by phoet** [comment]
hm, komisch. habe eben bei mehreren versuchen auch einen fehler bekommen, konnte es aber nicht reproduzieren.

**Comment by hzulla** [comment]
Habe den Fehler nur auf dem Desktop-Browser (Firefox) erlebt, nicht aber auf dem Smartphone (Chrome/Android).

**Comment by phoet** [comment]
ah, bei mir war es genau andersherum!

**Comment by phoet** [comment]
könnte schlichtweg ein problem mit github gewesen sein, aber ich schau mir das mal genauer an.

**Comment by phoet** [comment]
habe noch ein paar käfer gefunden und behaupte jetzt mal es funktioniert alles 😄

**Comment by hzulla** [comment]
Gleiche Situation wie beschrieben, heute mit der Meldung "Mist, da ist was schief gelaufen. (redirect_uri_mismatch)".

**Comment by phoet** [comment]
Ahh! Da hat sich das zusätzliche Fehler reporting doch schon ausgezahlt! Vermutlich wird da irgendwo noch auf www und irgendwo ohne umgeleitet. Manche Browser hängen das inzwischen automatisch dran oder blenden es aus, voll der Käse für die Seitenbetreiber.

**Comment by phoet** [comment]
dieses oauth zeug ist auch figelinsch... habe jetzt in cloudflare konfiguriert, dass alles auf www ge-redirected wird. damit sollte DIESER fehler auf jeden fall nicht mehr auftreten.

**Comment by phoet** [comment]
@hzulla falls du weiterhin probleme haben solltest gerne die details weiter hier rein.
