### ISSUE TITLE
Typo | Im Massen-Upload / Edit 

### ISSUE THREAD

**Issue by ValerianHeints** [weg-li/weg-li#130]
Nach dem Upload gibt es ein kleines Typo ("all", statt "alle") im Hinweistext:
"Der Massen-Upload wird gerade verarbeitet, in kürze stehen **all** Beweisfotos zur Verfügung."

**Comment by phoet** [comment]
möchtest du einen pull-request machen und es korrigieren?

https://github.com/weg-li/weg-li/blob/master/config/locales/de.yml#L201
