### ISSUE TITLE
api für den bilder upload

### ISSUE THREAD

**Issue by phoet** [weg-li/weg-li#134]
https://twitter.com/ChaWiBiker/status/1219560541074518017

> Gibt es eine api um Bilder in seinen „Account“ zu laden? Würde dies gerne mit iOS Shortcuts automatisieren damit die Geodaten nicht verloren gehen :-)

**Comment by phoet** [comment]
es gibt bereits eine rudimentäre API https://www.weg-li.de/api-docs/index.html

diese kann mit einem persönlichen API token angesprochen werden, den man in seinem profil findet, wenn er von mir generiert wurde

<img width="580" alt="Screen Shot 2020-01-21 at 11 10 32" src="https://user-images.githubusercontent.com/48745/72795889-a9a4a500-3c3e-11ea-837e-6017d1a35a28.png">

**Comment by phoet** [comment]
da der bilder-upload momentan direkt in ein bucket stattfindet, müsste eine entsprechende API folgendermaßen angesprochen werden:

* gib mir eine URL zu der ich das bild hochladen kann -> presigned-url + attachment-id
* upload zu presigned-url
* erzeuge mir eine meldung und das hier sind die photo-anhänge

**Comment by ChawiBiker** [comment]
So, ich habe es nun auch hierher geschafft.
Könnte man das mit einem Postbefehl lösen? Sowas kann man bauen in den iOS shortcuts.

**Comment by phoet** [comment]
ja, das sollte über HTTP POST möglich sein.

**Comment by phoet** [comment]
grundsätzlich ist diese funktionalität jetzt vorhanden https://github.com/weg-li/weg-li/pull/137
