### ISSUE TITLE
Strafen hochrechnen/hinterlegen

### ISSUE THREAD

**Issue by ChawiBiker** [weg-li/weg-li#138]
Spannend wäre es, wenn passend zum Verstoß auch noch die Strafe stünde. Im Hintergrund könnte man hochrechnen wie hoch das Anzeigevolumen ist für die Statistik.
Es würde auch die Entscheidung vereinfachen welche owi man anzeigt. Oft sind es ja gleich mehrere. So könnte man leichter die teuerste wählen :-)

**Comment by phoet** [comment]
mit dem neuen bußgeldkatalog wird es vielleicht auch eine maschinenlesbare variante geben, die man als sauber datengrundlage für soetwas benutzen kann.

grundsätzlich würde ich eine solche funktionalität aber nicht mit einbauen, da sie suggeriert, dass die anzeige genau in dieser form auch stattfindet und ggf falsche anreize setzen könnte.

**Comment by Henry-Hacker** [comment]
Tolle Idee. Ich weiß auch manchmal nicht, was ich anzeigen soll, wenn z.B. ein Fahrzeug auf Sperrfläche, Radweg und Gehweg gleichzeitig parkt.

**Comment by phoet** [comment]
ich habe von mehreren seiten die info bekommen, dass anzeigen mit mehreren tatvorwürfen gleich verworfen werden. dementsprechend müssten wohl für jeden vorwurf einzelne anzeigen erstattet werden. dafür gibt es die duplizieren funktionalität.
