### ISSUE TITLE
Nach klicken in Karte zur Meldung kommen

### ISSUE THREAD

**Issue by md42** [weg-li/weg-li#140]
Wäre ein nice-to-have wenn nach klicken eines Kartenmarkers die dazugehörige Meldung angezeigt wird (siehe Screenshot)
![image](https://user-images.githubusercontent.com/857448/73598063-b88b3180-4533-11ea-806e-20dc7b20a0c2.png)

**Comment by phoet** [comment]
in der tat, für die eigene karte ist das eine gute idee.

**Comment by md42** [comment]
Danke fürs Realisieren, super flott 🥇
