### ISSUE TITLE
Integration für Google-Photos

### ISSUE THREAD

**Issue by phoet** [weg-li/weg-li#144]
Als Benutzer möchte ich gerne Beweisfotos direkt aus Google-Photos übertragen können.

**Comment by phoet** [comment]
uploader mit google photos habe ich nur den kostenpflichtigen filestack gefunden https://www.filestack.com/

die google photos API hat leider keinen ruby client https://developers.google.com/photos

die umsetzung ist dementsprechend eher unwarscheinlich.

**Comment by GoetzGoerisch** [comment]
filestack macht aber doch nur uploads?

Die Google REST API reicht hier nicht?

**Comment by phoet** [comment]
filestack VS photos api

**Comment by phoet** [comment]
habe heute einen kleinen prototyp für einen workaround erstellt. dieser funktioniert folgender maßen:

1. in google photos ein geteiltes album erstellen
2. beweisfotos im album hinzufügen
3. link zum geteilten album kopieren
4. neuen massen-upload mit diesem link erzeugen

<img width="746" alt="Screen Shot 2020-02-15 at 22 29 45" src="https://user-images.githubusercontent.com/48745/74595542-f6637c00-5042-11ea-9655-77a2fe0ddd35.png">

beta-tester müssen dafür vorher freigeschaltet werden, also ggf bescheid sagen.
