### ISSUE TITLE
Eigene Textbausteine für das Hinweisfeld

### ISSUE THREAD

**Issue by fahrradfahrer** [weg-li/weg-li#145]
Ich habe einige Textbausteine, die ich immer wieder in das Hinweisfeld schreibe. Hier wäre es schön, wenn ich mir in meinem Account Textbausteine hinterlegen könnte, die ich mit einem Klick einfüge.

**Comment by phoet** [comment]
welche wären das?

**Comment by SIGMATAFF** [comment]
Ich finde es ebenfalls eine gute Idee, wenn man im eigenen Account ein paar Textbausteine hinterlegen kann.

1) z.B. für Parken auf dem Gehweg:

"Durch das dauerhafte Parken wird der Raum für FußgängerInnen und die Barrierefreiheit sehr stark eingeschränkt. Die “Restbreite” des Gehwegs beträgt nur noch ca. 50 cm! 
Bewohner dieser Strasse, Frauen mit Kinderwagen, Kinder mit Rad oder Senioren mit Rollator - sie alle sieht man auf der Strasse ausweichen (oder Umwege laufen) weil der Bürgersteig zugeparkt ist."

2) z.B. für Parken vor abgesenkten Bordstein (§ 12 Absatz 3 Nr. 5 StVO)

"Durch das dauerhafte Parken vor der Bordsteinabsenkung wird die Barrierefreiheit sehr stark eingeschränkt. Rollstuhlfahrer sowie gehbehinderte Menschen und Personen mit Kinderwagen können dort nicht mehr einfach und ohne weitere Umstände oder Umwege vom Gehweg auf die Straße zu gelangen!"

3) z.B. Parken entgegen der Fahrtrichtung (§ 12, Absatz 4 StVO)

"Durch das Parken entgegen der Fahrtrichtung entstanden unnötige Rangiermanöver die andere Verkehrsteilnehmer in Gefahr hätten bringen können."

**Comment by phoet** [comment]
danke für die beispiele. mir ist allerdings nicht ganz klar weshalb du diese erklärungen als bestandteil der anzeige übermittelst. welchen vorteil bietet dies im gegensatz dazu es einfach wegzulassen?

würden diese informationen an den falschparker gehen, dann könnte eine erklärung hilfreich sein, dem ist aber nicht der fall.

deshalb würde ich eher vorschlagen ein [browser-plugin](https://addons.mozilla.org/de/firefox/addon/clippings/) für soetwas zu nutzen.

**Comment by SIGMATAFF** [comment]
Die Erklärungen sollen die Behinderung und Gefährdung (die manchmal aus den OWI-Bildern nicht hervorgeht) erläutern bzw. verdeutlichen.

Danke für den Tipp mit dem Browser-Plugin.
Das hilft weiter.

**Comment by phoet** [comment]
dies könnte ggf auch teile davon implementieren https://github.com/weg-li/weg-li/issues/158#issuecomment-587485685
