### ISSUE TITLE
Foto entfernen im Step "Beschreiben"

### ISSUE THREAD

**Issue by fahrradfahrer** [weg-li/weg-li#146]
Im Step "Beschreiben" kann ich Fotos aktuell nicht mehr entfernen. Hier wäre es schön, wenn ich Fotos wieder entfernen kann.

**Comment by fahrradfahrer** [comment]
Auch im Step "Melden" kann ich Fotos nicht mehr entfernen.

**Comment by phoet** [comment]
das problem kann ich nicht nachvollziehen. gibt es eine fehlermeldung, oder was passiert genau?

**Comment by phoet** [comment]
ohne genauere informationen kann ich hier leider nichts machen.
