### ISSUE TITLE
Erkennung von zweizeiligen Kennzeichen unvollständig

### ISSUE THREAD

**Issue by mstrangmann** [weg-li/weg-li#147]
Bei zweizeiligen Kennezichen wird nur die untere Reihe erkannt.
Bsp: https://www.weg-li.de/p/charge/1c0d57d33522f2436bb743d5ceb191da
Mir fehlt aber eine größere Menge an relevanten Bildern um dies ausführlicher zu testen.
![Kennzeichen zweizeilig](https://user-images.githubusercontent.com/2055898/73927541-df4dbd00-48d1-11ea-9f6b-595b77df6f4a.jpg)

**Comment by phoet** [comment]
@mstrangmann das ist sehr warscheinlich richtig und ich bin mir auch nicht sicher, ob das behoben werden kann, denn in diesem fall wäre auch das kennzeichen `B F 109` ein gültiges kennzeichen.

**Comment by mstrangmann** [comment]
Das Kennzeichen fängt aber mit dem blauen Eurozeichen an. Und endet in DE mit einer Zahl. 
Ist dann mit der Erkennung etwas komplexer, aber wohl nicht unmöglich.

**Comment by phoet** [comment]
natürlich wird es möglich sein. ich wollte dir nur feedback geben, dass du es eher unwarscheinlich ist, dass diese nummernschilder in näherer zukunft korrekt erkannt werden.
