### ISSUE TITLE
Landkarte als Anhang der Meldung und im PDF-Export

### ISSUE THREAD

**Issue by BjarneRest** [weg-li/weg-li#148]
Hi,

könnte man einen Kartenausschnitt mit an die zuständige Stelle senden? Am Besten auch noch im PDF-Export hinterlegen.

Eine API dafür gibt es zum Beispiel von Mapbox:
https://docs.mapbox.com/api/maps/#static-images

Da müsste man dann noch einen Marker auf den Mittelpunkt vom Bild setzen.

**Comment by phoet** [comment]
das halte ich für übertrieben.
