### ISSUE TITLE
Statistik pro Bezirk

### ISSUE THREAD

**Issue by md42** [weg-li/weg-li#150]
Wäre eine Top10 nach Bezirk interessant?

**Comment by phoet** [comment]
Statistik von was?

In der Kartenansicht gibt es Statistiken zu Marken und vergehen.

**Comment by md42** [comment]
Pro Bezirk also
1. Berlin 2000 / Woche
2. Hamburg 1800 / Woche
Als Idee. Wer ist der aktivste Bezirk

**Comment by phoet** [comment]
so wie hie? https://www.weg-li.de/year2020

**Comment by md42** [comment]
ja genau, sorry nicht gesehen :)

**Comment by phoet** [comment]
kein problem, ich versuche nur immer zu verstehen was genau fehlt. ggf werden die statistiken bei gelegenheit noch mal anders zusammengestellt.
