### ISSUE TITLE
FR: prepare a notice for novice users

### ISSUE THREAD

**Issue by GoetzGoerisch** [weg-li/weg-li#154]
As an experienced user I would like to prepare a notice to help new users with the creation.
The new user can then access this notice with a private link and add it to his account.

**Comment by phoet** [comment]
@GoetzGoerisch do you have a someone you would want to test this with?

**Comment by phoet** [comment]
<img width="1165" alt="Screen Shot 2020-02-16 at 12 09 20" src="https://user-images.githubusercontent.com/48745/74603580-36634700-50b5-11ea-815c-eeeb068beffd.png">

auf der "Melden" seite gibt es jetzt eine weitere funktion "Meldung weiterleiten"
