### ISSUE TITLE
Eigene Anzeigen auf Karte ausblenden

### ISSUE THREAD

**Issue by BjarneRest** [weg-li/weg-li#155]
Hi,

könnte man auf https://www.weg-li.de/map einen Schalter einbauen, der die eigenen Anzeigen verbirgt? Ich fände es sinnvoll zu sehen, was andere Nutzer so treiben aber deren Meldung gehen auf der Karlsruher Karte unter meinen vielen Meldungen leider unter.

Gruß Bjarne

**Comment by phoet** [comment]
ggf könnte man die eignen meldungen mit einem anderen icon kennzeichnen

**Comment by BjarneRest** [comment]
Oder so, geht natürlich auch 👍Am 17.02.2020 14:20 schrieb Peter Schröder <notifications@github.com>:ggf könnte man die eignen meldungen mit einem anderen icon kennzeichnen

**Comment by phoet** [comment]
<img width="98" alt="Screen Shot 2020-02-17 at 14 34 20" src="https://user-images.githubusercontent.com/48745/74658453-a267ad00-5192-11ea-8bd4-bf5f6a317244.png">

**Comment by BjarneRest** [comment]
Möchtest Du das zusätzlich zur Ausblendemöglichkeit machen, oder stattdessen? Ich fände die Ausblendemöglichkeit weiterhin praktisch.

**Comment by phoet** [comment]
die macht sich aber nicht sehr praktisch im interface, deshalb würde ich sie eher weglassen.
