### ISSUE TITLE
Telegram-Chatbot zum Meldungen einreichen

### ISSUE THREAD

**Issue by BjarneRest** [weg-li/weg-li#156]
Hi,

es gibt ja bereits bei Telegram dem wegli_bot zum Login. Könnte man dem nicht noch ein wenig mehr "Leben" geben? Ich stelle mit folgendes vor:

`/meldung`
Dann Bilder einreichen per Telegram und optional per Telegram den Standort senden
Die restlichen Abfragen könnte man auch komplett über Telegram abwickeln mit vorab definierten Antwortmöglichkeiten ist das auch sehr komfortabel.

Wenn es eine API zum Anlegen einer Meldung gibt, kann ich mich auch mal selbst daran versuchen.

Gruß Bjarne

**Comment by phoet** [comment]
@BjarneRest ich habe da schon mal was vorbereitet ☝️

**Comment by phoet** [comment]
eine API ist vorhanden, aber noch nicht sonderlich gut dokumentiert, da es bis dato keine konsumenten gibt https://github.com/weg-li/weg-li/tree/master/spec/requests/api

**Comment by phoet** [comment]
Schließe ich vorerst, da mir der Bedarf zweifelhaft erscheint.
