### ISSUE TITLE
Korrekter juristischer Begriff zum "Halten"

### ISSUE THREAD

**Issue by BjarneRest** [weg-li/weg-li#159]
Hi,

im Moment wird trotz angegebener Dauer von weniger als 3 Minuten in der Meldung ein Text wie solcher generiert:

> Verstoß: Parken vor einer Bordsteinabsenkung, ohne Behinderung

eigentlich wäre es hier juristisch korrekt den Text wie folgt zu generieren:

> Verstoß: Halten vor einer Bordsteinabsenkung, ohne Behinderung

oder wenn man es genereller fassen will (weglassen von Informationen kann auch hilfreich sein, dann ist die Interpretation Sache der Bußgeldstelle):

> Verstoß: Fahrzeug vor einer Bordsteinabsenkung, ohne Behinderung

im Zweifelsfall müsste ich vor Gericht für den Begriff des "Parkens" gerade stehen, da wäre mir der korrekte Ausdruck lieber.

**Comment by xaniox** [comment]
Das ganze ist mir auch schon aufgefallen. Prinzipiell nur eine Kleinigkeit, die aber von der Bußgeldstelle falsch interpretiert werden könnte.
Wäre gut, wenn es hierfür einen Fix gäbe. 👍

**Comment by phoet** [comment]
die bußgeldstelle interessiert das eigentlich nicht weiter. es ist von einem bürger nicht zu verlangen, dass er die feinheiten der bußgeldordnung kennt. theoretisch könnten auch die ganzen verstöße auf "falschparken" reduziert werden, dann müsste man allerdings mehr in den hinweisen erläutern.

**Comment by BjarneRest** [comment]
Aber zumindest den Unterschied vom Halten und Parken sollte jeder mit Führerschein kennen.

Der anschließende Absatz

> Meine oben gemachten Angaben einschließlich meiner Personalien sind zutreffend und vollständig.
Als Zeuge bin ich zur wahrheitsgemäßen Aussage und auch zu einem möglichen Erscheinen vor Gericht verpflichtet.
Vorsätzlich falsche Angaben zu angeblichen Ordnungswidrigkeiten können eine Straftat darstellen.

macht das aber nicht besser, da hier explizit angegeben wird, dass alle Angaben 1000% korrekt sind.

**Comment by BjarneRest** [comment]
Entweder würde ich explizit "bis zu 3 Minuten" oder "Dauer unbekannt" ausweisen, oder halt auf den Parken-Begriff verzichten, falls eine geringere Dauer gewählt wurde

**Comment by phoet** [comment]
es gibt meines wissens nach keine fixe definition für halten vs. parken.

wenn das fahrzeug verlassen war und länger als 5 minuten stand, dann scheint es da einen konsens zu geben.

**Comment by BjarneRest** [comment]
§ 12 Abs. 2 StVO definiert

> Wer sein Fahrzeug verlässt oder länger als drei Minuten hält, der parkt.

**Comment by phoet** [comment]
wäre ja schön, wenn es so einfach ist. issseeet aaaaber nicht.

z.b. https://www.polizei.bayern.de/muenchen/verkehr/recht/index.html/3712

> Wer nur aussteigt, verlässt sein Fahrzeug noch nicht. Ein Kraftfahrzeugführer verlässt sein Fahrzeug noch nicht, wenn er es so im Auge behält, dass er nötigenfalls sofort wegfahren kann. Erst dann, wenn der Fahrer sich so entfernt, dass er sein Fahrzeug und den Verkehr nicht mehr im Auge behalten und bei Bedarf unverzüglich eingreifen kann, spricht man von einem Verlassen. Verbleibt eine andere Person im Fahrzeug, die im Bedarfsfall sofort eingreifen kann, liegt noch kein Verlassen vor. 

und in manchen städten wird eine mindest haltezeit von 5 minuten gefordert, bevor ein parkvergehen verfolgt wird...

**Comment by xaniox** [comment]
Sobald ein Auto länger als 3 Minuten an einer Stelle steht, gilt es laut StVO als geparkt, selbst wenn man das Auto nicht verlassen hat.

Insofern könnte es durch Verlassen des Fahrzeugs (Nach Definition der Polizei Bayern) unter 3 Minuten natürlich auch zum Parken kommen, das ist korrekt. Allerdings würde ich die Anzahl dieser Fälle verglichen mit der Anzahl der Fälle in denen sowieso nur unter 3 Minuten gehalten wird als sehr gering einschätzen. 

Natürlich ist das Risiko, wegen dem Stichwort "Parken" eine Falschaussage vorgeworfen zu bekommen auch recht gering. Immer korrekt wäre aber der Begriff "Halten" unter 3 Minuten (oder etwas Generischeres), damit könnte niemand irgendetwas belangt werden.

In Städten in denen ein Parken erst nach 5 Minuten verfolgt wird, kann die Stadt dann ja selbst entscheiden, ob der Anzeige nachgegangen wird, auf jeden Fall können sie oder der Falschparker den Anzeigenden nicht der Falschaussage bezichtigen, da in der StVO eine 3-Minutenregel definiert ist.

**Comment by phoet** [comment]
im zuge eines neuen bußgeldkatalogs wird es hier ohnehin änderungen geben

**Comment by phoet** [comment]
hier noch ein paar ausführungen des Polizeioberkommissar Sven Weske vom Polizeiinspektion 44 in München:

> Bei einem Parken gem. § 12 II StVO in der zweiten Alternative muss nach den Ausführungen der zentralen Bußgeldstelle eine Mindestbeobachtungszeit von 4 (nicht 3!) Minuten angeführt werden. Dies bedeutet, dass der Zeuge der VOWi währenddessen das Fahrzeug beobachten muss. In der ersten Alternative, also bei dem „Verlassen des Fahrzeuges“, muss durch den Zeugen belegt werden, dass der Fahrzeugführer sich so weit vom Fahrzeug entfernt hat, dass er nicht sogleich wegfahren kann, wenn das erforderlich ist (vgl. Bouska/Leue, StVO 24. Auflage § 12, Rz. 8). Das bloße Feststellen eines stehenden Fahrzeuges z.B. auf dem Gehweg, ohne die o.g. Ausführungen zu beachten, weist somit lediglich auf ein Halten hin.
