### ISSUE TITLE
"bei Auswahl Meldung*en* bearbeiten" / Bearbeiten mehrerer Meldungen auf ein Mal

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#167]
Moin,

kaum wieder aktiv schon der nächste Vorschlag:

Ich würde wahnsinnig gerne die folgenden Felder für alle markierten Anzeigen mit den selben Werten ausfüllen. 

Anwendungsfall 1:
Man fotografiert eine Reihe mit vielen Fahrzeugen hintereinander die alle den selben Verstoß begangen haben. Dadurch muss man nicht mehr für jedes Fahrzeug den Verstoß, die Beschreibung und die Checkbox "verlassen" einzeln manuell eingeben.

Anwendungsfall 2:
Die Fotos haben kein Datum und / oder keine GPS-Koordinaten. (Ausser dass beim fotografieren das Geotagging nicht angeschaltet war, gibt es noch andere Möglichkeiten, dass diese Daten fehlen können.) Das manuelle ausfüllen von Datum und Standort für jedes Owi einzeln, macht sehr viel Arbeit.

Folgende Felder würde ich gerne per Gruppen-Bearbeiten ausfüllen:

- Adresse
- Stadt 
- PLZ
- Verstoß
- Behinderung
- Tatzeitpunkt
- Dauer
- Hinweise
- Checkbox "das Fahrzeug war verlassen"

**Comment by phoet** [comment]
hast du dir schon die "vorauswahl" angeschaut, die es beim anlegen einzelner meldungen gibt?
