### ISSUE TITLE
Firefox: Uhrzeit mit Sekunden. Kein Picker.

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#168]
Im aktuellen Firefox unter Windows wird bei der Eingabe des Tatzeitpunkts die Uhrzeit mit Sekunden gefordert.

Im Gegensatz zum Datum kann man die Uhrzeit nicht mit der Maus auswählen.

Evtl ist es möglich das html so anzupassen, dass Firefox die Zeit nur mit hh:mm abfragt und ausserdem die Auswahl der Zeit per Maus anbietet?

Firefox-Version 72.0.1

![grafik](https://user-images.githubusercontent.com/5426586/75573837-f52c4900-5a5d-11ea-8e36-c9800889fa56.png)

**Comment by phoet** [comment]
es handelt sich um ein standard-html feld. wie der browser das genau supported liegt in der hand der browser-hersteller.
