### ISSUE TITLE
Filter setzt sich nach jeder Aktion auf default zurück

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#169]
Evtl habe ich dazu schon mal ein Issue aufgemacht.

Aktuell wird nach dem abschicken einer Meldung auf die Seite "Meldungen / Übersicht" geleitet und der Filter ist immer auf "kein Filter" gesetzt. Es werden dann überwiegend Meldungen angezeigt, die bereits den Status "gemeldet" haben. Man muss also nach jeder Meldung immer wieder den Filter auf "offen" setzen, um mit der Bearbeitung der nächsten Meldung fortfahren zu können. Auch wenn das setzen des Filters nicht viel Zeit in Anspruch nimmt, finde ich das lästig und überflüssig. 

Übersicht nach dem abschicken der letzten Meldung:
![grafik](https://user-images.githubusercontent.com/5426586/75575159-e8105980-5a5f-11ea-92f4-2ebdd44eb74a.png)

Übersicht nach dem setzen des Filters auf "offen":
![grafik](https://user-images.githubusercontent.com/5426586/75575251-1ee66f80-5a60-11ea-83a5-8ff77521f721.png)

**Comment by telewolf** [comment]
Als Workaround kann man sich die Lesezeichen-Symbolleiste einblenden und dort ein Bookmark anlegen welches auf folgenden Link zeigt. Man spart dann nach jeder Meldung einen Mausklick, weil man statt 1. auf Filter und 2. auf "offen" zu klicken nur auf den Link klicken muss.

https://www.weg-li.de/notices?filter%5Bstatus%5D=open

**Comment by phoet** [comment]
https://github.com/weg-li/weg-li/issues/68

**Comment by RalphBike** [comment]
Den Vorschlag mit dem Knopf mit den offenen Meldungen finde ich wenig hilfreich. Ich fände es deutlich sinnvoller, wenn zumindest die Filter- und Sortierungseinstellungen nicht jedes Mal neu gesetzt werden müssen. Ein solches Verhalten ist in vielen Applikationen schon etabliert (z.B. Sortieren von Mails in Thunderbird). Ich sehe hier keine Nachteile in der UX.
