### ISSUE TITLE
Mehrere Zeugen angeben

### ISSUE THREAD

**Issue by BjarneRest** [weg-li/weg-li#170]
Hi,

ich gehe ab und zu auch mit anderen weg-li-Nutzern spazieren. Es wäre praktisch, wenn ich diese als zusätzliche Zeugen angeben könnte, eventuell beim PDF-Export auch mit deren Unterschrift.

Könnte man langfristig vielleicht eine Funktion einbauen, sodass ich andere Nutzer als Zeugen "einladen" kann und diese nach einer Bestätigung dann auch aufgeführt werden?

Priorität für dieses Feature würde ich nicht so hoch sehen, aber vielleicht kann man das ja in Zukunft einbauen.

Gruß und vielen Dank für Eure Top-Arbeit!

**Comment by phoet** [comment]
ich gehe nicht davon aus, dass ich das bauen werde.
