### ISSUE TITLE
Meldungen zusammenführen

### ISSUE THREAD

**Issue by fahrradfahrer** [weg-li/weg-li#173]
Wenn ich eine Stelle mehrmals am Tag passiere mache manchmal mehrere Fotos vom selben Auto zu unterschiedlichen Uhrzeiten, um nachzuweisen, dass es länger als xx Minuten dort parkte. Im Massenupload übersehe ich das manchmal. Dann habe ich zwei einzelne unvollständige Meldungen, die eigentlich eine wären. Hier wäre eine Funktion "Meldungen zusammenführen" schön: Ich markiere mehrere unvollständige Meldungen, und wähle dann als Aktion "zusammenführen" aus. Anschließend gibt es eine gemeinsame Meldung, so, als hätte ich gleich beim Massenupload die beiden Fotos zusammen gebündelt.

**Comment by phoet** [comment]
es ist einfacher, die fotos noch einmal hochzuladen und doppelte meldungen zu löschen.

**Comment by phoet** [comment]
hier schon erörtert https://github.com/weg-li/weg-li/issues/102
