### ISSUE TITLE
Mehrere gleichzeitige Verstöße in einer Meldung erfassen

### ISSUE THREAD

**Issue by SalocinHB** [weg-li/weg-li#174]
Z.B. Parken vor Bordsteinabsenkung und Parken im absoluten oder eingeschränkten Haltverbot gleichzeitig

**Comment by phoet** [comment]
danke für dein feedback @SalocinHB 

dieser wunsch kommt des öfteren vorbei. wir werden das so nicht unterstützen. du hast aber folgende möglichkeiten:

a) das hinweis feld benutzen
b) meldungen duplizieren

**Comment by SalocinHB** [comment]
Schade. Variante a) nutze ich schon dafür, aber eine Auswahlmöglichkeit für weitere Verstöße fänd ich hübscher.

**Comment by phoet** [comment]
die sachbearbeiter prüfen ohnehin die angaben auf richtigkeit, vollständigkeit und den ggf vorliegenden tatbestand. deshalb ist diese funktionalität eher überflüssig.
