### ISSUE TITLE
ZIP-Upload

### ISSUE THREAD

**Issue by BjarneRest** [weg-li/weg-li#177]
Hi,

wäre es möglich bei Massen-Uploads auch Zip-Dateien hochzuladen?
Bei den Einzeluploads könnte es auch nützlich sein.

**Comment by phoet** [comment]
in wiefern? bild-dateien lassen sich sehr schlecht komprimieren.

**Comment by BjarneRest** [comment]
Mein Workflow ist der folgende:

Ich suche mir bei Google Fotos die passenden Fotos (2-3 Stück) raus und lade mir diese herunter. Dabei packt Google das in eine ZIP-Datei.

Anstatt die Datei nun zu entpacken und die Fotos einzeln hochzuladen, fände ich es praktisch, wenn ich die ZIP-Datei direkt bei https://www.weg-li.de/notices/new hochladen könnte. Dann spare ich mir den Schritt des Entpackens.

**Comment by phoet** [comment]
genau dafür gibt es doch die möglichkeit es über einen shared album zu machen
