### ISSUE TITLE
E-Mail-Login vereinfachen, feature request: Login mit E-Mail + Passwort

### ISSUE THREAD

**Issue by foss-** [weg-li/weg-li#178]
Aktuell

Wenn ich weg li im Firefox auf iOS besuche, muss ich mich dort anmelden. Sofern ich das recht gelesen habe, alle 30 Tage. Ich bevorzuge die Anmeldung per E-Mail. Ich gebe die E-Mail ein und erhalte jedesmal einen Bestätigungslink an die E-Mail Adresse.

Erwartet

Weniter umständlich und zeitaufwändig wäre ein Login via E-Mail + Passwort. Das habe ich im Passwortmanager und bin fix eingeloggt.

Erschwerend kommt hinzu, dass iOS keine Änderung des Default-Browsers erlaubt. Ein Klick auf den Verifizierungslink in der E-Mail öffnet Safari. Ich möchte aber Firefox verwenden. Link kopieren ist hier die Lösung, aber das ist alles sehr um die Ecke.

**Comment by phoet** [comment]
@foss- danke für dein feedback. wir wollen nach möglichkeit keine passworter in unserer datenbank speichern. gibt es keinen online-dienst, den du benutzt, der auch oauth erlaubt? ich mein, einen github account hast du ja...

**Comment by foss-** [comment]
Verstehe die Problematik. GitHub habe ich, verwende aber die E-Mail nur für diesen einen zweck. Ich benutze pro service eine eigene email. Quasi das, was Apple nun eingeführt hat, nur dass ich selbst die email adressen verwalte. nun könnte ich mir natürlich ein neuen github account erstellen, für weg li und diesen nur für weg li benutzen. Aber das wäre etwas verbogen.

**Comment by phoet** [comment]
die email-adresse die du für den dienst nutzt und mit der du dich bei github einloggst, hängen nicht miteinander zusammen.

**Comment by foss-** [comment]
ok ich schließe das mal. verstehe das problem. ich würde weiter einen "ordentlichen" login via email+passwort bevorzugen, anstatt andere logins mit weg li zu verknüpfen. aber verstehe den ansatz und ist kein großes problem.

**Comment by shoeper** [comment]
Ich würde mich auch lieber mit E-Mail + Passwort einloggen.

**Comment by phoet** [comment]
@shoeper was spricht dagegen deinen github account via oauth zu verbinden?

**Comment by shoeper** [comment]
Ich nutze lieber einen Account für eine Seite.

**Comment by phoet** [comment]
einen account? was meinst du damit. bei weg-li hast du einen account und bei github einen account.

**Comment by shoeper** [comment]
Ich verknüpfe ungern die Daten zwischen verschiedenen Plattformen / Seiten. Daher ein Account (E-Mail + Passwort) pro Seite.

**Comment by phoet** [comment]
Das habe ich wohl verstanden, meine Frage ist warum du das ungerne tust.

**Comment by foss-** [comment]
@phoet Wenn ich ein Account z.b. GitHub für diverse andere Services verwende, weiß GitHub automatisch, welche Services ich noch so nutze. Ich möchte aber diese Information gar nicht mit GitHub teilen. Ansonsten gilt noch, sollte mein GitHub Zugang kompromittiert werden, wäre auch der Zugang zu allen verknüpften Services kompromittiert. Die gleichen Gedanken stehen ja auch hinter "Signin with Apple".

Abseits davon ist eben für die Nutzer die sich (aus welchen Gründen auch immer) für E-Mail login entscheiden, der Login mit Passwort einfacher, als jedes mal den Weg via E-Mail-Verification zu gehen, der ja im Grunde nur einmal zu beginn der Nutzung nötig sein sollte.

**Comment by phoet** [comment]
@lucasteinke  was genau für ein cookie brauchst du denn noch?

<img width="256" alt="Bildschirmfoto 2023-05-11 um 12 58 29" src="https://github.com/weg-li/weg-li/assets/48745/c8da2f8b-a8aa-4771-b6b0-07656ee131e9">

**Comment by phoet** [comment]
der cookie ist 30 tage gültig und wird immer frisch gesetzt, das kann also nicht sein. wer die anwendung regelmäßig nutzt muss sich nie erneut einloggen.
