### ISSUE TITLE
Beim Lesen der EXIF-Daten wird falscher Bezirk ausgewählt

### ISSUE THREAD

**Issue by K0nsch** [weg-li/weg-li#179]
Moin,

jaja ich weiß das Ruhrgebiet und seine Tücken ^^

Also ich habe folgende Anzeige aufgegeben

![image](https://user-images.githubusercontent.com/13088073/76469892-86e96e00-63ef-11ea-9b77-cf35b1d200b3.png)
(Die Rote Linie ist die Stadtgrenze. Unten Bochum, oben Herne)

Dabei habe ich leider zu spät gesehen, dass statt Bochum die Stadt Herne ausgewählt wurden. 

Kurz dachte ich an ein Fehler von Google-Maps aber dies stellte sich als falsch heraus, da sowohl auf dem Smartphone beim Einsehen der Exif-Daten Bochum gesetzt ist, als auch auf Google-Maps bei der Eingabe der Hausnummer Bochum ausgewählt wird.

Anzeigenlink: https://www.weg-li.de/p/charge/8a556af015ea27d0a8e57096f6683681

Grüßle,

K0nsch

**Comment by phoet** [comment]
Ich konnte jetzt nicht genau verstehen was hier das Problem ist. Stimmt die PLZ nicht?

**Comment by K0nsch** [comment]
Genau.

Beim Analysieren der Exif-Daten muss ein Fehler auftreten. Dieser Betrifft die ganze Röhlinghauser Straße in Bochum.

Wie oben in dem Bild gezeigt ist Herne 44651, Bochum dagegen ist 44793. Die Röhlinghauserstraße in Herne liegt auch ganz woanders als die hier in Bochum. 

Sobald ich den Standortmarker in der manuellen Auswahl einen Millimeter umsetze, wird direkt Bochum ausgewählt. Die API von Google scheint also zu funktionieren. Auch auf meinem Handy wird 44793 Bochum angezeigt. 

Ich kann dazu gerne mal ein kurzes Video machen.

**Comment by phoet** [comment]
was die diensta da zurückliefern, darauf habe ich keinen einfluss.
