### ISSUE TITLE
iOS Bug Uhrzeit „gültigen Wert eingeben“

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#18]
Auf iPhone und iPad wird in Schritt „2 beschreiben“ die Fehlermeldung „gültigen Wert eingeben“ angezeigt, obwohl eine gültige Uhrzeit angegeben ist. Wird die Uhrzeit um eine Minute erhöht oder verringert, tritt die Fehlermeldung nicht mehr auf, wenn man auf „nur speichern“ oder „speichern und weiter“ klickt.
![8A439C3C-E22B-4A3C-ADF9-5EC21D5F8EC5](https://user-images.githubusercontent.com/5426586/63023084-9843b980-bea4-11e9-9799-c75a29e7fa21.png)

**Comment by phoet** [comment]
habe eben schon mal xcode und den dazugehörigen ios simulator installiert, damit ich mir das mal anschauen kann.

**Comment by telewolf** [comment]
Danke für den Versuch mit Xcode. Ich habe heute um 20:03 Uhr getestet. Die Fehlermeldung tritt weiterhin auf. Einfachster Workaround ist weiterhin die Uhrzeit um eine Minute hoch oder runter zu setzen.

**Comment by phoet** [comment]
habe auch schon von chrome nutzern probleme mit dem zeit-feld gehört. da muss ich wohl doch einen date-time-picker einbauen. ich hätte erwartet, dass die nativen felder inzwichen einigermaßen cross browser funktionieren...

**Comment by phoet** [comment]
ich habe ein paar kleinigkeiten geändert und die probleme auf dem ipad auch reproduzieren können. es sollte jetzt funktionieren.
