### ISSUE TITLE
Notices-Seite: Sortierung und Seite beibehalten nach Transaktionen

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#188]
Um die Usability zu  erhöhen, wäre es sinnvoll, nach einer Transaktion auf der Notices-Seite die angezeigte Seite und die Sortierung beizubehalten, nach dem z.B. Meldungen gelöscht wurden.

Z.B.
1) Ich bin auf Seite https://www.weg-li.de/notices?order%5Bcolumn%5D=date&order%5Bvalue%5D=DESC&page=3
2) Ich lösche eine Meldung über die Transaktionsauswahl im Item oder mehrere auf einmal als Batch.
3) Ich lande auf https://www.weg-li.de/notices

Bei 3) wäre es deutlich besser, wieder auf der selben URL wie 1) zu landen. Das würde manuelle Navigation reduzieren.

**Comment by RalphBike** [comment]
Nachtrag: Die Sortierung und eventuell auch die aktuelle Seite sollte generell auf der Notices-Seite erhalten bleiben. Z.B. wenn man von der Seite aus eine Anzeige erfasst und anschließend an der selben Stelle weiterarbeiten möchte. Z.B. beim Abarbeiten eines größeren Batchuploads.

**Comment by phoet** [comment]
das wurde schon hier diskutiert https://github.com/weg-li/weg-li/issues/169
