### ISSUE TITLE
Zusammenfassen von Fotos aus mehreren Meldungen 

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#189]
Nach Batch-Uploads kommt es hin uns wieder vor, dass man zwei oder mehr Fotos über mehrere Meldungen verteilt hat, weil man zuerst nicht erkannt hat, dass sie zusammengehören.

Ich schlage vor, auf der Notices-Seite eine Merge-Funktion zu implementieren, die die Fotos von N Meldungen zu einer Meldung zusammenfasst.

**Comment by RalphBike** [comment]
Der bisherige Workflow ist eher umständlich: Fotos merken, Meldungen löschen, Fotos auf dem Gerät suchen, neu hochladen und zu einer neuen Meldung machen.

**Comment by phoet** [comment]
siehe https://github.com/weg-li/weg-li/issues/102
