### ISSUE TITLE
Details zum Vorwurf abhängig von BKatV Lfd Nr

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#19]
Es wäre schön, wenn zu jedem Verstoß (BKatV) nur diejenigen Optionen bzw. Details zum Vorwurf vollständig angezeigt werden, die zu dem Tatbestand im BKatV aufgeführt sind. 

Bsp.: Zur Lfd Nr 54 gibt es:
- mit Behinderung 
- länger als 3 Stunden 

Länger als 3 Stunden gibt es aktuell noch nicht.

„Das Fahrzeug stand länger als 3 Minuten“ und „das Fahrzeug war verlassen“ sind für lfd nr 54 nicht möglich, werden aktuell im GUI fest angezeigt.

Bußgeldkatalog hier: https://www.gesetze-im-internet.de/bkatv_2013/anlage.html

**Comment by phoet** [comment]
danke für den hinweis, momentan gibt es für diesen fall nur das hinweisfeld.

es wäre natürlich super, wenn die verstöße alle mit den jeweiligen optionen und bußgeldern etc hinterlegt sind. für solche detail-arbeiten fehlt mir im moment definitiv noch die zeit.

ich bei so projekten nach der 80/20 regel, also mit 20% zeiteinsatz 80% der funktionalität bauen. sonst verzettelt man sich zu stark in details.

**Comment by telewolf** [comment]
Ack. Ich wünsche mir vorläufig eine Check-Box für „länger als 3 Stunden“

**Comment by phoet** [comment]
@telewolf es geht gerade einen neue version mit einem anderen select-picker live. kannst ja mal berichten ob die in iOS besser funktioniert (https://select2.org/)

**Comment by phoet** [comment]
siehe auch https://github.com/weg-li/weg-li/issues/138

**Comment by Henry-Hacker** [comment]
Länger als 3 Stunden bedeutet, man muss als Zeuge ein Fahrzeug 3 Stunden lang beobachten. Wie will man sonst sicher sein, dass es zwischenzeitlich nicht bewegt wurde. Oder es liegt eine Parkscheibe in der Windschutzscheibe.

**Comment by phoet** [comment]
zum beispiel indem man die reifenstellung dokumentiert.

**Comment by thhartung** [comment]
Das muss man gar nicht dokumentieren.
Wenn man das selbe Fahrzeug an der selben Stelle nach mehr als 3 Stunden meldet ist das entweder ein Verstoß länger als 3h, oder der Halter argumentiert gegenüber dem Amt, das stimmt so nicht, er war zwischenzeitlich weg, dann sind es zwei einzelne Verstöße.

**Comment by phoet** [comment]
natürlich muss man das ggf vor gericht dokumentieren können. aus diesem grund weigern sich manche ordnungsämter anzeigen entgegenzunehmen, die dieser dokumentationspflicht nicht nachkommen.

**Comment by Henry-Hacker** [comment]
Ok, Ihr habt mich überzeugt. Also entweder Reifenstellung fotografieren oder argumentieren, dass es sonst eventuell mehrere Verstöße waren (vorausgesetzt man darf da gar nicht halten/parken).
