### ISSUE TITLE
Löschen von Fotos aus Meldungen

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#190]
Ich würde aus Meldungen mit mehreren Fotos gerne einzelne Fotos löschen, ohne die Meldung komplett löschen und neu machen zu müssen.

Warum? Ich verwende teilweise mehrere Fotos pro Fall, um weitere Infos zu haben, möchte diese Fotos aber zum Teil nicht an die Bussgeldstelle senden.

Ich schlage dazu einen zweiten Button vor: Trash-Icon unter dem Auge-Icon.

**Comment by phoet** [comment]
der löschen button befindet sich aus platz-gründen im popover siehe screenshot in #70

**Comment by RalphBike** [comment]
Super, funktioniert. Danke!
