### ISSUE TITLE
Validator-Message ist falsch positioniert

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#191]
Einige Validator-Messages sind falsch positioniert, sie bewegen sich beim Scrollen nicht mit dem Formular mit (vermutlich "fixed"?). Sobald man scrollt, kann man die Message daher kaum noch dem Form Field zuordnen.

Intuitiver wäre, wenn die Message beim Scrollen mitwandert.

How to reproduce: Meldung erstellen und *keinen* Verstoß auswählen, dann Daten speichern.

**Comment by RalphBike** [comment]
Browser ist ein Firefox 75.0, unter Linux.

**Comment by phoet** [comment]
die form-validation ist ein browser-feature. ggf einen bug bei firefox aufmachen.
