### ISSUE TITLE
Parken auf Baumscheibe

### ISSUE THREAD

**Issue by ChawiBiker** [weg-li/weg-li#193]
In Berlin, gibt es die OWI „Parken auf Baumscheibe“
Könnte diese hinzugefügt werden?
https://www.berlin.de/ba-tempelhof-schoeneberg/politik-und-verwaltung/aemter/strassen-und-gruenflaechenamt/strassen-gruenflaechen-verwaltung/artikel.349752.php

![439FA217-E04A-4E19-BC7E-B5E2F304A616](https://user-images.githubusercontent.com/60240729/79698674-b8751500-828a-11ea-847a-61fd13786762.png)

**Comment by phoet** [comment]
gibt's schon! https://github.com/weg-li/weg-li/blob/master/app/lib/vehicle.rb#L208

**Comment by ChawiBiker** [comment]
Hmm. Danke. Verstehe nicht wieso beim ersten Mal „Baum“ kein Ergebnis geliefert hat. Vlt war mein Internet weg oder so. Heute morgen ging, dachte wäre dann schon eingebaut worden ^^

**Comment by phoet** [comment]
oft sitzt das problem ja vor dem bildschirm 😜

**Comment by ChawiBiker** [comment]
@phoet Problem leider wieder aufgetaucht. Irgendeine Idee?
![52CDFD4E-E424-45A6-B73C-7B8F30DD53AB](https://user-images.githubusercontent.com/60240729/210156263-5253826e-1771-49ec-a2c6-4872941d29b1.jpeg)

**Comment by phoet** [comment]
wir führen nur noch vergehen des BKAT

**Comment by ChawiBiker** [comment]
Schade. Keine Möglichkeit lokale Vergehen auf Basis der Stadt anzubieten? Also eben z.B. Parken auf Baumscheibe ist nur in der Auswahl möglich wenn die Stadt die gewählt ist, Berlin ist? Es ist hier leider ein gängiges Vergehen hier und schadet den Bäumen sehr und nur sehr wenige werden sich die Ordnungsamt App herunterladen um sowas anzuzeigen.

**Comment by phoet** [comment]
"Sonstiges Parkvergehen" geht immer

**Comment by ChawiBiker** [comment]
Ach ja gute Idee. Danke das reicht mit erstmal :)
