### ISSUE TITLE
Anzahl offener/unvollständiger Meldungen anzeigen (in Mail und Portal)

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#194]
Bitte die Reminder-Mail erweitern um:
-Betreff: Anzahl offener Meldungen älter als 14 Tage
-Body: Anzahl offener Meldungen älter als 14 Tage, 30 Tage, 60 Tage
-Und: diesen Besserwisser-Smiley entfernen.
Ansonsten bekomme ich jeden Tag eine Mail mit gleichen Betreff und einer Liste mit N Links, das motiviert nicht zum Bearbeiten und Raussschicken. 

Außerdem wäre eine Anzeige der offenen/unvollständigen Meldungen auf https://www.weg-li.de/notices/ gut, um zu wissen, wieviel man noch zu tun hat, z.B. nach einem Batch-Upload. Oder sich freuen kann, was man schon abgearbeitet hat. Oder einen Hinweis auf offene Meldungen bekommt, obwohl man denkt, dass man schon alles bearbeitet hat.

**Comment by phoet** [comment]
das tägliche versenden ist sehr einfach zu bauen, weshalb es derzeit so ist wie es ist.

grundsätzlich erscheint mir ein reminder in größeren intervallen auch sinnvoller. z.b. nach 7 und 14 tagen. danach ggf noch mal bevor die frist droht auszulaufen, ich glaube so einen reminder gibts aber auch schon?

**Comment by RalphBike** [comment]
Klar, verstehe ich.

1x pro Woche klingt gut.

Das Alter 7 oder 14 Tage finde ich nicht besonders relevant. Wenn ich keine Zeit habe, um Sachen abzuarbeiten, kommt es darauf nicht an. Kritischer ist eher die Ablauffrist, dazu habe ich bisher keinen Reminder gesehen. Kann auch Zufall sein. 

AFAIK muss das Ding nach 3 Monaten beim Adressaten im Briefkasten sein. Ich versuche daher alles nach spätestens 2 Monaten bearbeitet zu haben, dann hat die Busstgeldstelle noch einen Monat. Also würde ich 60-7=53 Tage als Frist sehen, ab der ein Reminder wirklich nötig ist. Zu dem Zeitpunkt könnte auch eine Liste mit Anzahl und Alter der offenen Meldungen rausgesschickt werden.

Wenn gerade nichts kritisches vorliegt, reicht ein Reminder alle 2-3 Wochen, wenn mehr N offene Meldungen vorliegen. Gerne ebenfalls mit Anzahl der Meldungen pro Alter.
