### ISSUE TITLE
Zeitpunkt für Zeiträume unter 3 Minuten

### ISSUE THREAD

**Issue by 4s1** [weg-li/weg-li#199]
Aktuell wird in der raus gehenden Mail immer der Zeitraum angegeben, auch wenn ich die Auswahl auf unter 3 Minuten lassen.

Mein Vorschlag wäre daher bei der Standardauswahl "unter 3 Minuten" in der Mail statt Zeitraum den Zeitpunkt zu benennen.

"Zeitraum: 06:54 ~ 06:55 (bis zu 3 Minuten)"
"Zeitpunkt: 06:54"

**Comment by phoet** [comment]
bei weniger als 3 minuten spielt es keine große rolle wie lange der zeitraum war.

**Comment by 4s1** [comment]
Ich finde nur die Angabe in der Mail irreführend, weil das impliziert ich währe da genau eine Minute gewesen.
Ich finde die Angabe über einen Zeitraum halt nur sinnvoll, wenn man ihn angeben will
