### ISSUE TITLE
Login via email not working coz of sendgrid redirect

### ISSUE THREAD

**Issue by nlinn** [weg-li/weg-li#2]
Clicking the auth-link leads to "something went wrong".

Sendgrid is replacing the link with its tracking shite, and their redirect leads to this error.
Copy-pasting the link (-label), the original auth-link, does work, so I guess you just have to find and turn off link-tracking for this email in your sendgrid config or dashboard.

(also postmark is the mail provider I highly recommend for transactional emails)

**Comment by phoet** [comment]
@nlinn this should fixed, could you take another look and verify that it works for you?
