### ISSUE TITLE
8m Bereich an Mündungen mit Radwegen

### ISSUE THREAD

**Issue by 4s1** [weg-li/weg-li#200]
In der Auflistung der Tatbestände fehlt die neu eingeführte 8m Regelung für Mündungen mit Radweg
![image](https://user-images.githubusercontent.com/15968622/80794368-0dbdfa00-8b9a-11ea-80c5-8ffa679648ab.png)

**Comment by phoet** [comment]
der neue bußgeldkatalog wird demnächst hinterlegt. das kann allerdings noch ein weilchen dauern.
