### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by BjarneRest** [weg-li/weg-li#201]
Hi,

wäre es möglich eine Tagging-Funktion hinzuzufügen? Also, dass ich Meldungen mit Tags versehen kann, diese dann in der Auflistung angezeigt werden und filterbar sind.

Gruß Bjarne!

**Comment by phoet** [comment]
möglich und sinnvoll sicherlich, sehe aber keine große nutzerbasis dafür.

vielleicht kannst du beim use-case etwas mehr ins detail gehen, oft finden sich bessere lösungen wenn man weiß welches problem es zu lösen gilt.

**Comment by BjarneRest** [comment]
Ich würde das gerne dafür nutzen um später die Einträge, bei denen nur gehalten wurde, herauszufiltern und mit meinem PDF-Editor anzupassen.
Alternativ kannst du natürlich auch wie bereits vorgeschlagen die Tatbestände dementsprechend anpassen oder als Freitext eingeben lassen.
