### ISSUE TITLE
Checkbox für Fehlerhafte Umweltplakette

### ISSUE THREAD

**Issue by BjarneRest** [weg-li/weg-li#202]
Eine zusätzliche Checkbox, ähnlich zur TÜV-Checkbox.

Eine fehlende oder ungültige Umweltplakette in entsprechenden Zonen kostet 100€ und kommt zum Parkverstoß dazu.

**Comment by phoet** [comment]
ahja, das könnte man mit aufnehmen, lenkt dann auch nochmal aufmerksamkeit darauf.

**Comment by jacboy** [comment]
In Stuttgart geht das nicht nur per Umweltplakette sondern auch je nach Fahrzeugtyp / Motor, siehe: https://www.stuttgart.de/diesel-verkehrsverbot

Das kostet zwischen 20€ und 108,50€.

Ich weiß nicht, ob und wie man das als Außenstehender kontrollieren kann, aber man könnte in den Stuttgarter Bezirken für die Anzeige einen Text wie folgt ergänzen:

> Ich bitte Sie, im Rahmen der Bearbeitung meiner Anzeige auch zu prüfen, ob das Fahrzeug gegen die in der 4. Fortschreibung des Luftreinhalteplans für Stuttgart genannten Fahrverbote für Diesel-Fahrzeuge der Abgasnorm Euro 4/IV und schlechter, oder gegen das streckenbezogene Fahrverbot für Diesel-Fahrzeuge der Abgasnorm Euro 5 und schlechter, verstößt.


Das wäre sehr edel.
