### ISSUE TITLE
Massen-Upload bleibt stehen: Error creating blob for <imagename>. Status 0.

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#204]
Mein Massen-Upload bleibt stehen: mit folgender Meldung:

Error creating blog for <imagename>. Status 0.

Ich kann nach diesem Fehler nicht weiterarbeiten z.B. mit den erfolgreichen Uploads.
Grundsätzlich hat der Massen-Upload mit diesem Setup vor kurzem noch gut funktioniert (Android 10, Chrome).

**Comment by phoet** [comment]
stand da wirklich blog? oder stand da blob?

ist aber auch egal, da es auf server-seite keine fehlermeldung gab ist es wohl ein fehler auf client-seite. ggf ist die verbindung unterbrochen worden oder es gab einen timeout. einfach mal neu laden und nochmal probieren.

**Comment by RalphBike** [comment]
Sorry, blob natürlich. Trat mehrfach auf nach ca. 15-30 Bildern.  

Ich teste nochmal.

**Comment by phoet** [comment]
da der upload über eine direkte verbindung mit der gcloud funktioniert kann ich da auch nicht weiter etwas erforschen. ggf ist es dann kurz kaputt.

**Comment by RalphBike** [comment]
Cannot reproduce. Ich schließe.
