### ISSUE TITLE
Massen-Upload: Nachgeladene Fotos sollten vergrößerbar sein

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#206]
Im Massenupload kann man die Fotos hinter den Thumbails nachladen, allerdings nicht in voller Größe anschauen. 

Das wäre gut, um die Bilder sicher den Meldungen zuzuordnen.

**Comment by phoet** [comment]
im moment ist diese lösung ein workaround, da größere uploads regelmäßig die leistungsarmen handhelds (und deren bandbreite) abgewürgt haben.

das kann man sicherlich nochmal überarbeiten.
