### ISSUE TITLE
Massen-Upload: Nächstes Foto sollte ohne scrollen auf dem Bildschirm sichtbar sein. 

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#207]
Um die Fotos gut zuzuordnen sollte man sich zumindest noch das nächste Foto anschauen. Das ist leider nur nach Runterscrollen-Hochscrollen machbar. Diese beiden Schritte könnten wegoptimiert werden, wenn das Layout zwei Fotos direkt anzeigt.

**Comment by RalphBike** [comment]
Das Thema ist wohl geräteabhängig. Gemeint ist ein normales/gängiges Telefon im Portrait-Mode.

**Comment by phoet** [comment]
der massen-upload ist definitiv nicht für handhelds optimiert. das ist aber auch garnicht die idee, diese aufgabe erledigen die meisten am computer und nutzen nur die upload-funktion vom handy.
