### ISSUE TITLE
Massen-Upload: Progress Bar und/oder Nummerierung der Fotos 

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#208]
Beim Massenupload fehlt mir ein Indikator über den Upload-Fortschritt. 

Schön wäre ein Progress-Bar über *alle* Fotos im Batch, z.b. als fester Balken am unteren Displayrand.

Außerdem wären die beiden Nummern AktuellesBild / BilderGesamt gut.

**Comment by phoet** [comment]
die verarbeitung geschieht im hintergrund, weshalb man einen zusätzlichen kommunikations-kanal zum browser bräuchte um den status dort anzuzeigen. das ist natürlich möglich, allerdings technisch relativ aufwändig und aus meiner sicht unnötig, denn warten musst du ohnehin bis es fertig ist 🙃

ggf lässt sich beim neu-laden schon erkennen wie weit die verarbeitung fortgeschritten ist, das wäre dann so halber weg.
