### ISSUE TITLE
Mehr Gamification: Lokale Leaderboards

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#209]
Im Sinne der Gamification wären lokale Leaderboards nett. Z.B. Hamburg.

Dabei könnte man sich auf die aktiven Städte (ab N Poster) konzentrieren. Gut wäre dabei eine Deeplink-taugliche URL.

**Comment by phoet** [comment]
das leaderboard ist eigentlich schon etwas too much gamification für meinen geschmack. ich würde das ungern weiter treiben.
