### ISSUE TITLE
Kennzeichen Erkennung unvollständig 

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#21]
Siehe https://www.weg-li.de/notices/24b4a90784433f3cb505bc1432a56690/edit

Statt AB CD 1234 wurde nur CD 1234 erkannt.

**Comment by phoet** [comment]
siehe auch https://github.com/weg-li/weg-li/issues/8

**Comment by telewolf** [comment]
Da das aussäe bereits unter #8 behandelt wird, kann ich dieses Issue zurückziehen bzw. löschen?

**Comment by phoet** [comment]
yo

**Comment by telewolf** [comment]
Thx
