### ISSUE TITLE
Exif-Daten: Zeitpunkt der letzten Änderung, nicht der Aufnahme

### ISSUE THREAD

**Issue by maltehuebner** [weg-li/weg-li#210]
Wenn ich Fotos hochlade, wird als voreingestellter Wert bei ```Tatzeit``` der Zeitpunkt der letzten Änderung des Fotos eingetragen, nicht der Aufnahmezeitpunkt des Fotos.

**Reproduzierung**
1. Nimm ein Foto mit einer Digitalkamera auf.
2. Übertrage die Fotos ein Programm wie Apple Photos oder Adobe Lightroom.
3. Lasse automatisch die Koordinaten aus einem GPX-Track zuweisen.
4. Exportiere die Fotos unter Beibehaltung aller Metadaten.
5. Lade die Fotos bei weg-li hoch.

**Beobachtung**
Als Voreinstellung der Tatzeit wird die Uhrzeit gewählt, zu der das Foto exportiert wurde.

**Erwartung**
Es wird der tatsächliche Aufnahmezeitpunkt aus den Exif-Daten ermittelt.

**Hinweis**
Das Problem tritt nicht auf, wenn ich ein Foto direkt mit dem Handy hochlade, da dort Aufnahme- und Bearbeitungszeit identisch sind, oder wenn ich Fotos direkt von der Speicherkarte oder über den Umweg des Dateisystems hochlade, weil in diesen Fällen keine Bearbeitung stattfindet.

**Beispielwerte**
Ungefähr so sehen die Exif-Daten eines Fotos aus, das ich hochlade.

![Bildschirmfoto 2020-05-05 um 23 28 22](https://user-images.githubusercontent.com/633959/81118183-ba94d000-8f28-11ea-8c10-b9b97cfa7ef7.png)
![Bildschirmfoto 2020-05-05 um 23 28 06](https://user-images.githubusercontent.com/633959/81118185-bbc5fd00-8f28-11ea-95fb-ff47090df929.png)

**Comment by RalphBike** [comment]
Kann ich bestätigen. Hier ein einfacheres How-to-reproduce:

1. Foto aufnehmen
2. Foto auf dem Telefon bearbeiten (z.B. Crop auf einem Android 10, Samsung-Gerät)
3. Foto hochladen.

Der Zeitpunkt der Bearbeitung wird dann fälschlich als Tatzeit verwendet.

**Comment by phoet** [comment]
so wird das ausgelesen: https://github.com/weg-li/weg-li/blob/master/app/lib/exif_analyzer.rb#L8-L13

wenn aus den exif-daten nichts extrahiert werden kann, dann versuchen wir es mit dem dateinamen, da dieser auch oft einen zeitstempel enthält.

am einfachsten kann ich es mir anschauen wenn ich eine beispielmeldung mit fotos habe.

**Comment by RalphBike** [comment]
Klar:
https://www.weg-li.de/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHo0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f188590a956e6321392b2b85b64ac7a7c009ad12/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lPTVRJNE1IZ3hNamd3QmpvR1JWUTZESEYxWVd4cGRIbEpJZ2M1TUFZN0JsUTZFR0YxZEc5ZmIzSnBaVzUwVkE9PSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--4237484679f8cb095a1d00c2a47095fb1c476a66/20200506_103057.jpg

https://www.weg-li.de/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHY0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--dc26420a1d8e8ca140d82a95ecb82af0afb450ba/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MY21WemFYcGxTU0lPTVRJNE1IZ3hNamd3QmpvR1JWUTZESEYxWVd4cGRIbEpJZ2M1TUFZN0JsUTZFR0YxZEc5ZmIzSnBaVzUwVkE9PSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--4237484679f8cb095a1d00c2a47095fb1c476a66/20200506_113453.jpg

Im großen Foto: Aufnahme um 10:30 => Tatzeit um 10:30.
Im Ausschnitt: Aufnahme um 10:30, Bearbeitung um 11:34 => Tatzeit um 11:34.

**Comment by thhartung** [comment]
Wollte das auch nur bestätigen, tritt auch bei mir auf.
