### ISSUE TITLE
GPS-Positionen fehlen nach Upload mit Android & Chrome

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#213]
Hi, 

das ist eher eine Frage, kein Bug:

funktioniert die Browser-Empfehlung für Upload mit GPS-Daten unter "Android: Chrome+Filepicker" noch?

Meine Uploads sind alle ohne Daten, mit Android&Firefox funktioniert es mit den gleichen Fotos. Allerdings klappt dort der Batchupload nicht :-/

Hat jemand eine Idee dazu? Kann ich das konfigurieren? OS ist Android 10 mit aktuellem Chrome. 
Alternativ würde ich auch eine Empfehlung für Multi-Select im Android-Firefox nehmen. Danke!

**Comment by phoet** [comment]
multi-select in firefox ist seit ewigkeiten kaputt. das kümmert die anscheinend nicht: https://bugzilla.mozilla.org/show_bug.cgi?id=1355389

ich benutze täglich android mit chrome via "Durchsuchen". damit funktioniert der upload von gps daten und der multi-file-select.

**Comment by phoet** [comment]
mir ist auch nicht ganz klar warum die browser-hersteller so darauf abfahren die file-uploads kaput zu machen. vor 6 monaten konnte man weitestgehend ohne workarounds dateien bei ios und android hochladen. jetzt ist es kompliziert bis unmöglich.

**Comment by RalphBike** [comment]
Okay, mit "Durchsuchen" scheint es zu klappen. Darauf muss man erstmal kommen. Allerdings finde ich nur die 36 neuesten Fotos. Gibts da noch einen Trick?
