### ISSUE TITLE
Massen-Upload verbessern

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#214]
Der Batch-Upload ist gut, könnte aber noch etwas besser werden:

1. Zur Zuordnung mehrerer Fotos wären Datum und Uhrzeit pro Foto gut, damit man erkennen kann, ob man dieses rote Auto mehrfach in einem Zeitraum oder über eine längere Zeit fotografiert hat. 
2. Die Thumbnails laden langsam. Und zwar jedes Mal, nach dem Erstellen jeder einzelnen Meldung. Lässt sich da was am Caching machen?
3. Es ist mühsam, jede Meldung einzeln zu erfassen, auch wegen 2. Meine Idee dazu ist, eine Funktion, über die man ALLE verbleibenden Fotos aus dem Batch-Upload in einzelne Meldungen packen kann. Dann könnte man Mehrfoto-Meldungen zuerst bearbeiten und den Rest mit einem Knopfdruck abarbeiten.

**Comment by RalphBike** [comment]
zu 1. Alternativ ginge auch der Dateiname.

**Comment by phoet** [comment]
hast du den knopf "Pro Foto eine neue Meldung" übersehen?

**Comment by RalphBike** [comment]
Fuck. Ja! Bitte Punkt 1 ignorieren. Aber schön, dass wir auf die selbe Idee kamen.

**Comment by phoet** [comment]
die thumbnails sollten im browser cache liegen sobald sie geladen sind. da ist mir bis dato nichts aufgefallen. ist das auf dem handheld? ist schwierig irgendetwas daraus zu machen mit so wenig informationen.

**Comment by RalphBike** [comment]
Aktueller Firefox auf Desktop. Die Thumbnails werden jedes Mal neu geladen.

**Comment by RalphBike** [comment]
Mmmh, das Caching scheint doch zu funktionieren. Ich beobachte das mal weiter.

**Comment by phoet** [comment]
das liegt auf dem client-ende, da hat die app wenig bis garnix mit zu tun.
