### ISSUE TITLE
Bildupload geht nicht: Hochladen von einem Gerät der Freundin geht nicht

### ISSUE THREAD

**Issue by Wikinaut** [weg-li/weg-li#216]
![grafik](https://user-images.githubusercontent.com/1151915/82241384-5ae0f080-993c-11ea-8424-6b906d9cd3bd.png)

* Android 9
* Google Chrome

Ich kann leider nur per Ferndiagnose dort helfen, was könnte die Ursache sein?

Wenn ich das gleiche Foto von meinem Computer hochlade, geht das problemlos.

**Comment by phoet** [comment]
das ist ein generischer fehler auf client seite. zb wenn die verbindung abbricht. seite neu laden hilft in solchen fällen.

**Comment by Wikinaut** [comment]
okay, ich werde ihr das weiterleiten. Mache das Issue hier zu.

**Comment by Wikinaut** [comment]
Sie hat das gemacht - geht nicht.

**Comment by phoet** [comment]
@Wikinaut geht es denn bei dir?

**Comment by Wikinaut** [comment]
Das schrieb ich oben: das Foto als solches ging problemlos via Firefox/Linus hochzuladen, wie immer.

**Comment by phoet** [comment]
und wie genau soll ich dann jetzt helfen?

**Comment by Wikinaut** [comment]
Aufgrund der Fehlermeldung nachgucken, was der Grund sein könnte - wenn möglich. Kommt die oben gezeigte Meldung von Dir? Sieht doch so aus.

**Comment by phoet** [comment]
https://github.com/weg-li/weg-li/issues/216#issuecomment-630349010

**Comment by phoet** [comment]
da kann ich nicht mehr sagen als "did you try turning it off and on again"

**Comment by Wikinaut** [comment]
Macht sie gerade, habe noch keine Rückmeldung.

**Comment by phoet** [comment]
falls das nicht hilft gibt es keine weiter möglichkeit das zu debuggen es sei denn sie schickt mir das gerät.

**Comment by Wikinaut** [comment]
Hi Peter, Sie hat gemeldet:
![grafik](https://user-images.githubusercontent.com/1151915/82251240-20338400-994d-11ea-8794-52b7a15dd7ed.png)
