### ISSUE TITLE
Firefox und Chrome: vor Absenden der Anzeige, beim Zurückgehen, werden die neu eingegegebenen oder korrigierten Daten gelöscht und müssen erneut eingegeben werden.

### ISSUE THREAD

**Issue by Wikinaut** [weg-li/weg-li#219]
Auch in der aktuellen Version besteht weiterhin dieses Problem:

#### How to reproduce
* Lade ein oder zwei Fotos hoch
* EXIF/ALPR läuft durch
* Benutzer ergänzt einige fehlende Daten, wie Straßenadresse, Hinweis, Vergehen, Autotyp (*)
* Benutzer klickt weiter bis zur Vorschau der E-Mail und "Anzeige erstatten"
* Benutzer stellt vor dem Abesenden fest, dass Daten zu korrigieren sind

#### Problem
* Nach dem Browser-zurück sind die beim Schritt (*) eingegebenen oder korrigierten Daten verschwunden.

* Browser: Firefox 76.0.1 (aktuell) auf LinuxMint 19.3 (aktuell)

**Comment by Wikinaut** [comment]
Ich bitte, dafür eine Lösung zu finden, dass dies nicht mehr passiert.

Die eingegebenen Daten sollen bis zum tatsächlichen Absenden der Anzeige korrigierbar/nacheditierbar sein.

**Comment by phoet** [comment]
die daten sind korrigierbar. es handelt sich wenn überhaupt um ein problem mit dem browser-cache. ein neu-laden der seite sollte das beheben.

**Comment by Wikinaut** [comment]
ich habe es eben probiert: ja.

Es ist dann allerdings nicht richtig programmiert, denn ein "normaler" Benutzer weiß das nicht. Ich bitte Dich herzlich, eine andere Methode zu finden, damit die eingegebenen Daten dann wieder da sind. Du (das Script) kann zum Beispiel die Seite selbst neu laden.


Mit anderen Worten, was ich höflich sagen will: bitte versuche, eine befriedigende Lösung zu finden, damit auch ungeübte Benutzer nicht in dieses Problem laufen. Ich teste gerne mit Dir zusammen.

**Comment by phoet** [comment]
dieses problem tritt bei mir nicht auf und ich habe es auch noch von keinem anderen benutzer gehört.

**Comment by phoet** [comment]
schau doch mal ob das bei dir auch in anderen browsern auftritt.

**Comment by Wikinaut** [comment]
Vllt. melden es Dir andere Benutzer nicht - bitte diesen Aspekt nicht vom Tisch zu wischen, ich meine das ganz neutral.

**Comment by phoet** [comment]
hier wird nichts gewischt.

wenn es bei mir nicht auftritt und es von keinem anderen benutzer gemeldet wird, dann liegt es höchstwarscheinlich an irgendetwas auf deiner seite.

ohne die möglichkeit etwas zu reproduzieren gibt es auch keine möglichkeit etwas zu bearbeiten. du kannst bei deinem browser die javascript-console öffnen und schauen ob dort ggf ein fehler auftritt.

**Comment by Wikinaut** [comment]
Diverse:

```
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden.
```

```
Laden fehlgeschlagen für das <script> mit der Quelle "https://maps.googleapis.com/maps/api/js/AuthenticationServic.....".
```
und hier ein Teil:
![grafik](https://user-images.githubusercontent.com/1151915/82805222-ed751880-9e83-11ea-8dd8-acf6705ba232.png)

**Comment by phoet** [comment]
das sind alles nur warnings. fehler sind rot.

**Comment by Wikinaut** [comment]
* Adblock Plus
* uBlock Origin
* NoScript
*HTTPSEverywhere
*Cloud Firewall

**Comment by Wikinaut** [comment]
Speicherst Du irgendwas woanders als im Browser (bis zum endgültigen Absenden)?

**Comment by Wikinaut** [comment]
Das gemeldete Problem besteht im Chrome (Chromium) *auch*.

**Comment by phoet** [comment]
alleine schon die verwendung von NoScript ist problematisch, weil die seite ohne javascript nicht funktioniert.

**Comment by Wikinaut** [comment]
Ist vollkommen egal, weil das gleiche Problem im frisch installierten Chrome auch sofort offensichtlich ist.

**Comment by Wikinaut** [comment]
![grafik](https://user-images.githubusercontent.com/1151915/82806257-b0118a80-9e85-11ea-9212-92813afeced4.png)

**Comment by Wikinaut** [comment]
Bitte nimm' Dir die Muße, und gehe meine Punkte durch, ich bin mir sicher, Du wirst das Problem bestätigen können. Dann habe ich 10 Bier bei Dir gut.

**Comment by phoet** [comment]
Wie schon gesagt, in Firefox tritt das Problem bei mir nicht auf. Bei Gelegenheit werde ich es nochmal mit einem anderen Browser ausprobieren.

**Comment by GoetzGoerisch** [comment]
Wenn man einmal "zurück" klicke, komme ich auf die Zusammenfassungsseite. Hier würde ich dann auf "Meldung bearbeiten" gehen, um Änderungen zu machen.
Wenn man hier dann nochmal "zurück" klickt, kommt man auf die Bearbeiten Seite und die Felder sind nicht ausgefüllt. Ein Reload, wie von @phoet beschrieben, bringt alle Daten korrekt in die Felder.

Ich würde niemals auf die Idee kommen, zweimal "zurück" zu klicken und dann zu erwarten, dass Formulardaten noch da sind.

**Comment by Wikinaut** [comment]
Du könntest - neben dem Knopf "Anzeige erstatten" einen Knopf machen "Eingegebene Daten überarbeiten" (der macht dann den reload der Seite bzw. history.back()+reload ).

Das wäre sowie die richtige Lösung (Extra-Knopf zur Dateneingabe -> der automatisch reload macht).

**Comment by Wikinaut** [comment]
@GoetzGoerisch Einmal zurück -> Daten weg. Bitte, Ihr seid echt stur hier, der normale Benutzer kennt unsere Tricks gar nicht. Bitte seid nicht so developer-fixiert, versetzt Euch in die armen Leute draußen, die in dieses Problem laufen.

**Comment by Wikinaut** [comment]
> Ein Reload, wie von @phoet beschrieben, bringt alle Daten korrekt in die Felder.

dann baut einen Knopf dafür ein, bitte, "Daten überarbeiten" (= history.back() PLUS reload() )

**Comment by phoet** [comment]
@Wikinaut bitte sachlich bleiben!

**Comment by Wikinaut** [comment]
Ich bin sachlich und berichte, wie es hier an der Meldefront aussieht und gebe konkrete Hinweise zur Lösung.

**Comment by phoet** [comment]
1. es gibt schon einen "zurück" button 

<img width="348" alt="Screen Shot 2020-05-25 at 12 56 05" src="https://user-images.githubusercontent.com/48745/82807052-501be380-9e87-11ea-9010-1b740216f443.png">


2. ein reload ist überhapt nicht notwendig, die normale navigation tut genau das was sie soll

3. beim browser-back button kommt es manchmal zu problemen, weil der browser die seite aus seinem internen cache zieht. warum das bei dir dann die daten "vergisst" ist unklar und in firefox nicht nachzuvollziehen.

**Comment by phoet** [comment]
> Bitte, Ihr seid echt stur hier, der normale Benutzer kennt unsere Tricks gar nicht. Bitte seid nicht so developer-fixiert, versetzt Euch in die armen Leute draußen, die in dieses Problem laufen.

das ist unsachlich, falsch und unangemessen

**Comment by Wikinaut** [comment]
Dasselbe Problem tritt im Chrome auf. Vermutlich ist bei Deinem System etwas anders.

Du könntest "Meldung bearbeiten" beim Punkt "Anzeige erstatten" als Extrabutton präsentieren.

**Comment by phoet** [comment]
https://github.com/weg-li/weg-li/issues/219#issuecomment-633511528

**Comment by lepathie** [comment]
> hier wird nichts gewischt.
> 
> wenn es bei mir nicht auftritt und es von keinem anderen benutzer gemeldet wird, dann liegt es höchstwarscheinlich an irgendetwas auf deiner seite.
> 
> ohne die möglichkeit etwas zu reproduzieren gibt es auch keine möglichkeit etwas zu bearbeiten.  du kannst bei deinem browser die javascript-console öffnen und schauen ob dort ggf ein fehler auftritt.

Also dieses Problem ist mir jetzt auch schon mehrfach aufgefallen. Nutze Edge (Version 83.0.478.37 (Offizielles Build) beta (64-Bit)). Kann @Wikinaut auch nur zustimmen, dass das für unerfahrene User ein recht großes Problem darstellt.

Irgendwas läuft hier wohl beim Formular-Handling schief. Würden keine Prüfungen anstehen, würde ich mich wohl selber mal ins Projekt reinfuchsen.

**Comment by phoet** [comment]
> es handelt sich wenn überhaupt um ein problem mit dem browser-cache.

**Comment by phoet** [comment]
Es handelt sich, wie schon vermutet, um ein Problem mit dem Cache: https://github.com/turbolinks/turbolinks/issues/238

**Comment by Wikinaut** [comment]
Wenn Du ein Foto hochlädst, Kennzeichen und Wagentyp editierst, und dann ein zweites Foto - dann verschwinden die zuerst geänderten Daten.
