### ISSUE TITLE
Wunschliste Verstöße 

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#22]
Ich wünsche mir folgende Verstöße [(aus dem Bußgeld Katalog)](https://www.gesetze-im-internet.de/bkatv_2013/anlage.html) im Dropdown-Menü:
- BKat Nr 142a; Verbot des Einfahrens (Zeichen 267) nicht beachtet
- Bkat 139; Die durch Zeichen 215 (Kreisverkehr) oder Zeichen 220 (Einbahnstraße) vorgeschriebene Fahrtrichtung nicht
befolgt

**Comment by telewolf** [comment]
- Bkat 132; Als Kfz-Führer in anderen als den Fällen des Rechtsabbiegens mit Grünpfeil rotes Wechsellichtzeichen oder rotes Dauerlichtzeichen nicht befolgt (am liebsten mit Checkboxen für „mit Gefährdung“, „länger als 1 Sekunde“)

**Comment by telewolf** [comment]
- Parken auf dem Behindertenparkplatz für https://www.weg-li.de/notices/2ee509336b8151155b803ef540f0c140/edit

**Comment by phoet** [comment]
danke für deine vorschläge, den behindertenparkplatz habe ich gleich mit aufgenommen.

was die anderen verstöße angeht bin ich erstmal zurückhaltend. wenn ich das richtig verstanden habe, dann ist es relativ einfach und erfolgsversprechend anzeigen im ruhenden verkehr mit beweisfotos zu machen. beim fließverkehr sind in der regel andere stellen zuständig und die beweisführung ist wesentlich komplizierter. ich will nicht ausschließen, dass es mal über wegli möglich sein wird, dass wird aber erstmal warten müssen bis der rest reibungslos funktioniert.

**Comment by telewolf** [comment]
Für Hamburg kann ich die Anforderungen gerne in Erfahrung bringen. Vermutlich benötigt man ein Foto mit dem es möglich ist den Fahrer eindeutig zu identifizieren. Zusätzlich muss natürlich noch der Verstoß selbst gerichtsfest nachgewiesen werden. 

Es würde mich wahnsinnig freuen, wenn das vielleicht in ca 3 Monaten Platz für Erweiterungen in diese Richtung da sind. Insbesondere für Rotlicht-Verstöße und für Handy am Steuer.

**Comment by telewolf** [comment]
Zur Vollständigkeit:
- Blatt 246.1; Elektronisches Gerät rechtswidrig benutzt beim Führen eines Fahrzeugs

**Comment by telewolf** [comment]
Kannst Du bitte eine Checkbox „länger als 3 Stunden“ hinzuzufügen?

**Comment by telewolf** [comment]
Langfristig wäre es toll wenn man mehrere Verstöße auswählen kann und anschließend die Optionen „nur den teuersten“ und „nur den günstigsten“ anzeigen.

**Comment by phoet** [comment]
die checkbox geht gleich live

**Comment by phoet** [comment]
im moment ist die liste der verstöße von links und rechts zusammenkopiert. es wäre super, wenn man da eine echte bereinigte datenbasis hätte. daran ließen sich dann auch solche informationen hängen und anzeigen. 

wenn weg-li weiterhin so tracktion aufnimmt, dann komme ich da wohl nicht drum rum 😄

**Comment by telewolf** [comment]
Bereinigte Datenbasis = Bußgeldkatalog in Datenbank?

**Comment by phoet** [comment]
bußgeldkatalog in einer bereinigten form, also mit allen möglichen fällen und idealer weise auch noch beispiel bildern

**Comment by phoet** [comment]
anstatt datenbank würde ich verallgemeinert mal "maschinenlesbar" setzen, z.b. JSON oder so

**Comment by hzulla** [comment]
Neuer Eintragswunsch: Verbrenner parkt auf Parkplatz vor Ladesäule, der für Elektrofahrzeuge reserviert ist.

**Comment by phoet** [comment]
@hzulla "Fahrzeug blockiert Elektroladesäule" geht gleich mit live

**Comment by hzulla** [comment]
Dann erzähle ich mal den Elektroautofahrern davon.

**Comment by phoet** [comment]
💸

**Comment by telewolf** [comment]
Auf längere Sicht wäre es toll wenn man alle in Frage kommenden Verstöße eintragen kann und man weg-li dann auffordern kann entweder nur den teuersten oder nur den günstigsten zu verwenden.

Bsp. Ein Fahrzeug parkt entgegen der Fahrtrichtung auf dem Fussweg im absoluten Halteverbot. Sind 3 Verstöße. Es wird aber nur einer gehandet. Deswegen möchte man entweder den teuersten oder den günstigsten auswählen.

**Comment by K0nsch** [comment]
Bei Parken auf Radfahrstreifen fehlt der Zusatz (Zeichen 237) 

Ich brauche aber für eine verfahrensfeste Anzeige das entsprechende Zeichen dazu. 

Ich nutzte bisher Radfahrstreifen auch für benutzungspflichtige Radwege aber das ist jetzt nicht mehr möglich, da Radwege sowohl unbeschildert als auch beschildert sein können. Entsprechend sind das auch andere Tatbestände im BKatV. 

Wie ich mal anmerkte "Radweg-/fahrstreifen Zeichen 237" und "unbeschildeter Radweg" bitte dringend einführen. Danke :)

**Comment by K0nsch** [comment]
Was ebenfalls in der Liste noch fehlt ist "Gemeinsamer Geh- und Radweg Zeichen 240" und "Radweg Zeichen 241"

**Comment by phoet** [comment]
als kleine zwischen-konstruktion bis zu einer vollständigen abbildung (inkl. der zusätze und kosten) habe ich folgende liste aus dem bussgeldkatalog extrahiert:

```
Sie parkten auf einem unbeschilderten Radweg
Sie hielten/parkten auf einem Fußgängerüberweg
Sie hielten/parkten auf einem Radweg (Zeichen 237)
Sie hielten/parkten auf einem Geh- und Radweg (Zeichen 240/241)
Sie hielten/parkten auf einer Fahrradstraße (Zeichen 244.1/244.2)
Sie parkten verbotswidrig auf einem Schutzstreifen für den Radverkehr (Zeichen 340)
Sie hielten/parkten verbotswidrig auf einem Gehweg
Sie parkten in einem verkehrsberuhigten Bereich (Zeichen 325.1, 325.2) verbotswidrig außerhalb der zum Parken gekennzeichneten Flächen
Sie parkten in einem Fußgängerbereich, der durch Zeichen 239/242.1, 242.2/250) gesperrt war
Sie hielten/parkten in einem Abstand von weniger als 5 Meter vor einem Fußgängerüberweg
Sie parkten weniger als 5 Meter vor/hinter der Kreuzung/Einmündung
Sie hielten/parkten im absolutem Haltverbot (Zeichen 283)
Sie parkten unzulässig im eingeschränkten Haltverbot (Zeichen 286).
Sie hielten/parkten an einer engen/unübersichtlichen Straßenstelle
Sie hielten/parkten im Bereich einer scharfen Kurve
Sie hielten/parkten unzulässig in der zweiten Reihe
Sie hielten/parkten vor oder in einer amtlich gekennzeichneten Feuerwehrzufahrt
Sie parkten verbotswidrig und verhinderten dadurch die Benutzung gekennzeichneter Parkflächen
Sie parkten im Bereich einer Grundstückseinfahrt bzw. -ausfahrt
Sie parkten auf einer schmalen Fahrbahn gegenüber einer Grundstückseinfahrt/Grundstücks-ausfahrt
Sie parkten vor einer Bordsteinabsenkung
Sie hielten/parkten verbotswidrig auf der linken Fahrbahnseite/dem linken Seitenstreifen
Sie hielten/parkten nicht am rechten Fahrbahnrand
Sie hielten/parkten im Fahrraum von Schienenfahrzeugen
Sie hielten/parkten links von einer Fahrbahnbegrenzung (Zeichen 295)
Sie hielten/parkten auf einem durch Richtungspfeile (Zeichen 297) gekennzeichneten Fahrbahnteil
Sie hielten/parkten innerhalb einer Grenzmarkierung (Zeichen 299) für ein Haltverbot
Sie hielten/parkten näher als 10 Meter vor einem Andreaskreuz (Zeichen 201)/Zeichen 205 (Vorfahrt gewähren!)/Zeichen 206 (Halt! Vorfahrt gewähren!) und verdeckten dieses
Sie hielten/parkten innerhalb eines Kreisverkehrs (Zeichen 215)
Sie parkten in einem Abstand von weniger als 15 Metern von einem Haltestellenschild
Sie parkten, obwohl zwischen Ihrem Fahrzeug und der Fahrstreifenbegrenzung (Zeichen 295/296) ein Abstand von weniger als 3 Metern verblieb
Sie parkten innerhalb einer Grenzmarkierung (Zeichen 299) für ein Parkverbot
Sie parkten bei zulässigem Gehwegparken (Zeichen 315) nicht auf dem Gehweg
```

alles was nicht innerstädtisch oder irrelevant ist habe ich entfernt.
