### ISSUE TITLE
Update des Tatbestandskatalogs (18.05.2020)

### ISSUE THREAD

**Issue by hollma** [weg-li/weg-li#221]
Der Tatbestandskatalog beim KBA wurde am 18.05. bzw. 19.05. aktualisiert. Der neue Link ist:

https://www.kba.de/DE/ZentraleRegister/FAER/BT_KAT_OWI/bkat_owi_18_05_2020_pdf.pdf?__blob=publicationFile&v=4

Der Link unter dem Auswahlmenü der Tatbestände bei der Seite für die Meldungen zeigt noch auf das alte PDF.

**Comment by phoet** [comment]
Danke für den Hinweis
