### ISSUE TITLE
Feauture Request: unkenntlich machen

### ISSUE THREAD

**Issue by tipuraneo** [weg-li/weg-li#222]
Erklärung:
Bildteile unkenntlich machen, um Personen und unbeteiligte Kfz-Kennzeichen zu schützen.

Vorschlag:
Möglichkeit der Verwendung von Stift oder Rechteck in den Bildbearbeitungsprozess integrieren.

**Comment by phoet** [comment]
Dieses Feature wurde schon evaluiert und ist zu aufwändig. Bildbearbeitung sollte möglichst vorher passieren, Mobiltelefone haben inzischen alle nötigen Werkzeuge dafür integriert.
