### ISSUE TITLE
Weitere Anzeigen zu einem Nummernschild anzeigen

### ISSUE THREAD

**Issue by marhei** [weg-li/weg-li#224]
Es wäre sicher interessant, wenn man auf der Seite einer Meldung direkt weitere Meldungen, die man bereits zu diesem Nummernschild abgegeben hat, angezeigt bekommt. Der aktuelle Weg über die Suche ist leider etwas umständlich.

**Comment by phoet** [comment]
Danke für das Feedback. In wiefern wäre das interessant? Welche Informationen sollten dort stehen und warum?

**Comment by marhei** [comment]
Einfach um direkt zu sehen, ob man das Auto bereits mehrfach gemeldet hat. Das ist bestimmt keine lebenswichtige Information, aber man hat ja hin und wieder das Gefühl, dass man immer die gleichen Autos meldet und das würde das einem dann bestätigen.

**Comment by phoet** [comment]
Sollte für ein Kennzeichen bereits eine Anzeige für das gleiche Datum vorliegen wird eine Warnung angezeigt um versehentliche Doppelmeldungen zu vermeiden.
