### ISSUE TITLE
Mail-Adresse für Füssen nicht mehr aktuell

### ISSUE THREAD

**Issue by sgruendel** [weg-li/weg-li#225]
Die Anzeige ist wohl leider nicht angekommen:
mail.fuessen.de Mail delivery failed : returning message to sender

Siehe https://www.weg-li.de/notices/253c42aacddd8bbedd38cfd0ee607da6

**Comment by phoet** [comment]
Da dort eine personalisierte E-Mail Adresse hinterlegt ist, liegt der Verdacht nahe, dass sie nicht mehr aktuell ist. Am besten beim örtlichen Ordnungsamt nachfragen, an welche Adresse das übermittelt werden soll.
