### ISSUE TITLE
Ich möchte den E-Mail-Text vor dem Absenden noch korrigieren können.

### ISSUE THREAD

**Issue by Wikinaut** [weg-li/weg-li#229]
Ich muss den E-Mail-Text vor dem Absenden noch korrigieren, das geht derzeit leider nicht. Ich denke aber, dass das leicht möglich ist und bitte um Implementierung.

Konkretes Beispiel:
Der Tatbestand für "HALTEN" auf einem Radweg ist nicht auswählbar. Ich habe deshalb "PARKEN" auf Radwweg gewählt und wollte das dann nachkorrigieren, geht leider nicht.

Hilfsweise habe ich dann im Freitextfeld aus dem Bkat den Text reinkopiert.

```
Tabellen-Nr.:       Sie hielten/parkten auf einem Radweg (Zeichen 237) 741033
Tatbestand                                  BKat               TBNR              FaP-Pkt                   Euro
Halten                                      --                 141070                      0               50,00
- mit Gefährdung                            --                 141572                      0               70,00
```

**Comment by phoet** [comment]
Dazu gab es schon ein paar Anfragen, es wird aber aus unterschiedlichen Gründen so ein Feature nicht geben.

Für Freitext das Hinweis feld benutzen.

**Comment by Wikinaut** [comment]
Dann ändere bitte Deine Tatbestandstexte, denn (Beispiel), diese haben prinzipiell die Form   "Halten/Parken auf Radweg" - und nicht, wie bei Dir - "Parken auf einem Radweg..."

Benutzer können das nicht in "Halten" abändern, das ist das Problem auf Deiner Seite.
