### ISSUE TITLE
Meldungen / Übersicht - Miniatur-Bilder werden nicht angezeigt

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#23]
Moin, ich hatte jetzt immer wieder mal das Problem, dass trotz guter Funkverbindung (WLAN oder LTE) die Vorschaubilder teilweise nicht angezeigt werden. Nach einem Reload werden die selben Bilder nicht angezeigt. Also unverändert.
![782DC207-ED9C-4600-B252-935D7EDA644C](https://user-images.githubusercontent.com/5426586/63085742-83236500-bf4e-11e9-9201-1caf96529d37.png)

**Comment by phoet** [comment]
die bilder werden aus der google cloud geladen, damit hat die app nur relativ wenig zu tun. ich habe dieses verhalten aber auch schon beobachtet und es hat möglicher weise etwas mit dem caching zu tun. die bilder werden mit einer sogenannten pre-signed-url geladen, die nur eine gewisse lebensdauer hat. 

ich gucke mal, ob das ggf am CDN liegt https://github.com/rails/rails/issues/32236#issuecomment-383690067

**Comment by phoet** [comment]
<img width="395" alt="Screen Shot 2019-08-15 at 12 59 49" src="https://user-images.githubusercontent.com/48745/63090783-a228f380-bf5c-11e9-98fc-ee0cff26f166.png">

das müsste es heile machen

**Comment by telewolf** [comment]
Kommt mit dem nächsten Release oder ist die Korrektur schon live? Ich hatte den fehler gerade nochmal.

**Comment by phoet** [comment]
das ist schon live, es kann aber sein, dass im browser noch irgendwas gecached rumliegt.
