### ISSUE TITLE
Handeditierte Feldinhalte werden u.U. überschrieben/gelöscht. Bitte nicht tun.

### ISSUE THREAD

**Issue by Wikinaut** [weg-li/weg-li#230]
Wir diskutierten bereits mehrfach (bspw. in #219 ) über verschwundene Feldinhalte.

Ich möchte vorschlagen, dass Du das Skript so änderst, 

* dass Feldinhalte
* die bereits benutzereditierten Content haben 

**nicht mehr - wie jetzt - mit neuen programmatisch generierten Inhalten wie ALPR, EXIF-Data, sonstiges überschrieben werden**. Dies kann vermutlich einfach durch entsprechende Dummy-Belegung oder hidden Contents programmiert und errreicht werden und wäre eine echt große Hilfe.

#### Use case
Ich lade ein erstes Bild hoch, clicke alle Angaben zusamme, korrigiere die Adresse und füge noch freien Text hinzu.

Nun lade ich weitere/s Bild/er hoch. Augenblicklich werden die mühsam von mir getippten und geklickten Daten wieder zurückgesetzt bzw. überschrieben.

**Comment by phoet** [comment]
Es werden keine Inhalte überschrieben.

**Comment by Wikinaut** [comment]
Doch, meine eingebenen Daten - Adresse, Ort, Datum, Zeit - werden gelöscht, wenn ich das zweite Foto hochgeladen habe.

Das ist 100% reproduzierbar.

**Comment by phoet** [comment]
Speicherst Du deine Eingaben denn ab bevor Du ein weiteres Foto hochlädst?

**Comment by Wikinaut** [comment]
Nein, ich lade einfach - nach meinen Texteingaben - ein weiteres Foto hoch, da ich davon ausgehe, dass Dein Server sämtliche eingegebenen Daten selbsttätig bei onchange() speichert.

**Comment by phoet** [comment]
Das nächste mal vorher abspeichern (oder erst das Foto hinzufügen)

**Comment by Wikinaut** [comment]
Und warum speicherst Du nicht vor dem Hochladen bzw. bei der Eingabe?

**Comment by capacityHH** [comment]
Das Problem hatte ich am Anfang auch einige Male. Ist schon sehr frustrierend wenn man viel geschrieben hatte und es dann plötzlich weg ist. Jetzt versuche ich gleich zu Beginn alle Fotos hochzuladen, und gehe dem Problem aus dem Weg. Aber es wäre natürlich schön wenn man ein weiteres Bild hochladen möchte, weg-li automatisch alle vorherigen Eingaben speichert.

**Comment by Wikinaut** [comment]
@capacityHH Danke für Deine klare Ansage! Dafür bekommste das Logo von mir:
![grafik](https://user-images.githubusercontent.com/1151915/84603739-04aa9300-ae91-11ea-8b5c-10fd830a0fcd.png)

**Comment by phoet** [comment]
@Wikinaut ich habe deinen Kommentar gelöscht. Bitte lade hier keine irrelevanten Inhalte hoch.

**Comment by Wikinaut** [comment]
Wie Du meinst.

Ich dachte, Dir gefällt das Logo - das Du gerne verwenden kannst - auch so gut wie den anderen.

**Comment by phoet** [comment]
@capacityHH wäre es Hilfreich in dem Zusammenhang einen Warnhinweis zu bekommen "Bitte erst speichern vor dem hinzufügen"?

Grundsätzlich sollten alle Bilder gleich zu Anfang hinzugefügt werden, weil die automatische Erkennung dann präziser ist und alle optimierungen darauf ausgelegt sind.

**Comment by capacityHH** [comment]
Dieser Hinweis hätte mir als weg-li Anfänger etwas Arbeit erspart.
Ich finde die Lösung gut.
Vielleicht sogar mit dem Hinweis:"Grundsätzlich sollten alle Bilder gleich zu Anfang hinzugefügt werden, weil die automatische Erkennung dann präziser ist und alle optimierungen darauf ausgelegt sind." Das war mir am Anfang noch nicht klar.
