### ISSUE TITLE
Bildformate: bittte auch png erlauben

### ISSUE THREAD

**Issue by Wikinaut** [weg-li/weg-li#231]
Ich speichere alle meine Screenshots im png-Format: weil nur png auch scharfe Linien und Schriften - wie Time/Datestamp ohne Kodierungsartefacte speichert.

Leider unterstützt weg-li zur Zeit nur jpeg. Ich wünsche mir, dass auch png erlaubt ist.

**Comment by phoet** [comment]
Unterstützung von PNG ist sehr unwahrscheinlich
