### ISSUE TITLE
Chronologische Sortierung nach Datum innerhalb einer Meldung

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#233]
Hi, es wäre nett (und weniger irritierend), wenn die Fotos innerhalb einer Meldung nach Datum sortiert wären, statt nach Einfügereihenfolge, sonst verwirrt das ziemlich.

Die Fotos sind z.B. durcheinander, wenn man zuerst eine Meldung mit einem Foto erstellt und später noch ein Bild hinzufügt, also Upload innerhalb der Meldung.

**Comment by phoet** [comment]
Das stimmt natürlich. Ich weiß aber gerade garnicht ob wir das Datum überhaupt zur Verfügung haben. Das müsste man erst aus den Metadaten extrahieren und zusätzlich abspeichern.

**Comment by RalphBike** [comment]
Ein Quick-and-dirty-Ansatz könnte Sortierung nach Dateinamen sein. Mit den meisten Handy-Fotos sollte das klappen, aber da gibts sicher auch krude Ausnahmen.

**Comment by phoet** [comment]
Diese Annahme ist leider Falsch, iOS hat keine sortierbaren Dateinamen.

**Comment by RalphBike** [comment]
Warum war mir das klar... :-)

**Comment by carstenhag** [comment]
Wäre es möglich das manuell zu machen? Ich kann ja manuell ins exif schauen bzw weiß, wann ich was aufgenommen habe. Momentan kann ich zb nicht auf /notices/....id..../edit die Fotos sortieren/anordnen. Wenn ja, erstell ich ein neues issue dafür :)

**Comment by phoet** [comment]
Die EXIF-Daten speichern wir zwar inzwischen in der Datenbank, allerdings sind diese nicht so aufbereitet, dass sie für eine Sortierung an dieser Stelle geeignet wären. Rails hat da keine besonders hilfreiche Abstraktion, mit der man das einfach implementieren könnte.

Womöglich lässt sich das auf Client-Seite mit JavaScript lösen, wenn die GPS-Daten in den Thumbnails erhalten bleiben.

**Comment by carstenhag** [comment]
Wollen wir dann das ticket wieder aufmachen?
