### ISSUE TITLE
Direkte Eingabe von TBNR (Profi-Modus)

### ISSUE THREAD

**Issue by BjarneRest** [weg-li/weg-li#236]
Hey,

ich fände es nützlich direkt die TBNR eingeben zu können, anstatt aus dem Dropdown für den Tatbestand zu wählen. Ich kann dadurch wesentlich besser beschreiben, welcher Tatbestand vorlag. Beispiel:

|  Verstoß | Nahestliegende Auswahlmöglichkeit bei weg-li  |  TBNR | somit Tatbestand |
|---|---|---|---|
| Ein Fahrzeug hält auf dem Radfahrschutzstreifen und behindert mich als Radfahrenden  | ~Parken~ verbotswidrig auf einem Schutzstreifen für den Radverkehr (Zeichen 340)  | 142671 | Sie hielten verbotswidrig auf einem Schutzstreifen für den Radverkehr (Zeichen 340) und behinderten dadurch Andere. |
| Ein Fahrzeug hält auf dem Gehweg und behindert mich als Fußgänger  | ~Parken~ verbotswidrig auf einem Gehweg  | 112051 | Sie hielten verbotswidrig auf dem Gehweg und behinderten dadurch Andere. |
| Ein Fahrzeug hält auf dem Gehweg und behindert mich als Fußgänger  | ~Parken~ verbotswidrig auf einem Gehweg  | 112051 | Sie hielten verbotswidrig auf dem Gehweg und behinderten dadurch Andere. |
| Ein E-Auto parkt an einer Ladesäule, lädt aber nicht und versperrt Anderen den Zugang  | Parken mit ~Verbrenner~ vor Elektroladesäule  | 142284 | Sie parkten unberechtigt auf einem Parkplatz für elektrisch betriebene Fahrzeuge (Zeichen 314/315)) mit Zusatzzeichen. |

Im ersteren Fall wird es besonders deutlich, denn der aktuelle Bußgeldkatalog kennt gar keinen Parkverstoß für Radfahrschutzstreifen, sondern nur den Halteverstoß.

Aktuell schreibe ich die TBNR immer manuell in das Feld für die Beschreibung. Das hilft der Bußgeldstelle bei der Ahndung.

### tl;dr
Ich wünsche mir, **zusätzlich** zur aktuellen Lösung einen Profi-Modus mit Eingabemöglichkeit der TBNR. Die Felder Verstoß und Behinderung fallen dann weg, oder werden, falls das möglich ist, automatisch ausgefüllt mit dem Text aus dem Bußgeldkatalog.

Grüße!

**Comment by phoet** [comment]
Danke für den detaillierten feature request. 

Grundsätzlich halte ich nichts davon, dass der Anzeigende eine so tiefe Kenntnis der Tatbestände haben muss. Das geht auch dem Ziel zuwieder, dass es möglichst einfach sein sollte für den Zeugen eine Anzeige aufzugeben. Die Auswahl des Tatbestandes obliegt ohnehin dem jeweiligen Sachberbeiter.

Ich würde mich nicht grundsätzlich dagegen sperren, wenn so ein feature als PR hinzugefügt wird und es die Anwendung für normale Nutzer nicht verkopmliziert. Ich werde definitiv keine resourcen dafür aufwenden soetwas zu implementieren.

Was jedoch in diesem Zuge interessant sein sollte: Es liegt bei mir schon seit geraumer Zeit ein aktueller, digitalisierter Bußgeldkatalog herum. Diesen möchte ich gerne im 1. Schritt als eine Art Refernz auf der Seite einbinden, damit man überhaupt schon mal sehen kann was Sache ist. Parkvergehen sind natürlich nur ein kleiner Teil, aber die Rohdaten wären dann theoretisch schon hinterlegt.

**Comment by BjarneRest** [comment]
Kannst du mir den digitalen BKat mal senden? Ist der auf dem aktuellen Stand?

Vielleicht kann ich mich ja daran versuchen

**Comment by phoet** [comment]
Habe meinen WIP mal hier hin geworfen https://github.com/weg-li/weg-li/pull/237/files

Die Daten müssten aktuell sein, ist von hier geklaut https://www.govconnect.de/Downloads

**Comment by BjarneRest** [comment]
Komplett aktuell ist der Datensatz leider auch nicht. Die Änderungen aus Mai fehlen noch. Vielleicht frage ich mal beim KBA die Daten als CSV oder ähnlichem an

**Comment by phoet** [comment]
@BjarneRest 🤣 vielleicht hast du mehr Glück als ich beim KBA...

Was die Daten angeht, evtl kann man da schon etwas neueres herunterladen. Eigentlich sollten die Daten von da aktuell sein.

**Comment by BjarneRest** [comment]
Vielleicht klappt das ja so https://fragdenstaat.de/a/189544

**Comment by BjarneRest** [comment]
Ich habe nun vom KBA die "Datenbank" der Tatbestände übersandt bekommen:
[https://fragdenstaat.de/anfrage/bundeseinheitlicher-tatbestandskatalog-bt-kat-owi-in-maschinenlesbarer-form/#nachricht-499093](https://fragdenstaat.de/anfrage/bundeseinheitlicher-tatbestandskatalog-bt-kat-owi-in-maschinenlesbarer-form/#nachricht-499093)

**Comment by phoet** [comment]
👍 nice, hörnchen-separierte daten :) natürlich nicht UTF-8 codiert...

`101000^Sie kamen von der Fahrbahn ab und verursachten Sachschaden.^ ^ ^ ^ ^§ 1 Abs. 2, § 49 StVO; § 24 StVG; -- BKat^^B^1^  35^00^^^^2014-04-30^2002-01-01^^ ^4^^^^Sie kamen von der Fahrbahn ab und verursachten Sachschaden.^^^^^§ 1 Abs. 2, § 49 StVO; § 24 StVG; -- BKat^`

**Comment by BjarneRest** [comment]
Nicht die Hörnchen sind der Separator, sondern ein Byte 0xA7 ist unsichtbar dazwischen

**Comment by phoet** [comment]
kleiner spoiler

<img width="1208" alt="Screen Shot 2020-08-26 at 23 15 27" src="https://user-images.githubusercontent.com/48745/91357779-10e89000-e7f2-11ea-934a-8544e82673e3.png">

**Comment by BjarneRest** [comment]
Wird hier noch entwickelt? Wenn jetzt die Tabelle eingelesen ist, könnte man ja den Dropdown beim Meldungsformular ersetzen (oder optional halt TBNR eingeben und es wird automatisch der Vorwurf geladen)

**Comment by phoet** [comment]
beim hinzufügen des bkat sind mir diverse dinge aufgefallen wegen derer man genau das nicht "einfach" machen kann.

grundsätzlich werde ich aber die liste irgendwann mit den daten aus dem bkat ersetzen, dann sollte auch das auswählen per TBNR möglich sein. das wird aber frühestens passieren wenn dann mal fest steht welcher bkat gilt.

**Comment by phoet** [comment]
btw, die daten vom KBA sind so schlecht strukturiert, dass ich doch auf die eines drittanbieters ausweichen musste.

**Comment by BjarneRest** [comment]
Kannst du mir die andere Datenquelle mitteilen? Ich könnte sie für ein anderes Projekt auch gebrauchen

**Comment by phoet** [comment]
die sind von govconnect https://github.com/weg-li/weg-li/issues/236#issuecomment-647454071

habe die hier schon ins csv-format konvertiert: https://github.com/weg-li/weg-li/tree/master/bkat/data

**Comment by jomo** [comment]
Ich habe das Datenbankformat™ hier beschrieben und in CSV konvertiert: https://github.com/jomo/bkat-owi

Die Datei enthält zum derzeitigen Zeitpunkt die Version 2020-05-18 (mit Daten, die ab dem 2020-04-28 gültig sind).

Viel Spaß!

_(PS @BjarneRest: `0xA7` ist lediglich `§` im Windows-1252 encoding)_

**Comment by der-eismann** [comment]
Gibt's für den BKAT eine Aktualisierung oder so? Ich weiß leider nicht, wie ich `Ein E-Auto parkt an einer Ladesäule, lädt aber nicht und versperrt Anderen den Zugang` aktuell auf weg.li eintragen soll.

**Comment by phoet** [comment]
Wahlweise den Catch-All "Sonstiges Vergehen" nehmen und im Hinweisfeld beschreiben. Die Anzeige wird ohnehin von einem Sachbearbeiter bearbeitet und geprüft.

**Comment by der-eismann** [comment]
Ah, daran hab ich nicht gedacht. Hab versucht selbst etwas einzutippen, aber dann kam nur "No results found".
