### ISSUE TITLE
FR: Ausweitung auf die Schweiz?

### ISSUE THREAD

**Issue by stefanhaustein** [weg-li/weg-li#238]
Wäre das möglich? 

Hab's mal durchgespielt... 

- Die Postleitzahlen sind hier nur vierstellig (habe eine 0 vorangestellt, ok als "Workaround")
- Die Vergehen sind anders kategorisiert (Workaround: habe das "passenste" ausgewählt)
- Bei der Auswahl des Bundeslandes (um einen neunen Bezirk zu erstellen) habe ich aufgegeben, da ich kein "passendes" Bundesland auswählen konnte und die Datenbank nicht zumüllen wollte...

Empfehlungen? Pull-Request? Fork?

**Comment by phoet** [comment]
👋  Hi Stefan,

da ich weder Interesse noch Zeit dafür habe den Support für die Schweiz zu machen, müsste das jemand anderes übernehmen. Bevor dieses Thema nicht geklärt ist, würde ich an Deiner Stelle gar nicht erst anfangen etwas zu programmieren! Ich verwende täglich mindestens 30 bis 60 Minuten darauf Anfragen zu beantworten und Daten zu aktualisieren.

Aus technischer Sicht würde ich denken, dass ein Fork hier wohl die einfachste Variante ist mit irgendetwas zu starten. Sowohl die Inhalte, als auch die Workflows sind warscheinlich etwas unterschiedlich und sollten möglichst nicht Deutschland und die Schweiz durcheinanderwerfen. Zusätzlich hättest Du wohl noch das Sprachproblem in der Schweiz.
