### ISSUE TITLE
Phishing warning in Gmail

### ISSUE THREAD

**Issue by GoetzGoerisch** [weg-li/weg-li#239]
Weg-Li Mails are classified as phishing lately in Gmail:
![Phishing](https://user-images.githubusercontent.com/47734341/85603033-42a57500-b650-11ea-912a-ae276e9cbc8a.png)

Anything you can do to prevent this?

SPF and DKIM looks fine, but you are using the full name and the individual @anzeigen.weg-li.de sender address.

**Comment by phoet** [comment]
No idea, @mnin ?

**Comment by mnin** [comment]
@GoetzGoerisch bitte leite mir mal an mnin@mnin.de die gesamte Mail samt Header weiter.

**Comment by mnin** [comment]
@GoetzGoerisch thanks, Google is detecting your name as sender with an email address that Google does not manage.

**Comment by GoetzGoerisch** [comment]
Correct, this is also my observation after further inspection.
@phoet could you change the **From** to something like Weg-Li Anzeige (Username)?

Send me testmails if you like?
