### ISSUE TITLE
Eine API für native Clients bereitstellen

### ISSUE THREAD

**Issue by phoet** [weg-li/weg-li#24]
> gerne Rest, oder Rest-artig. Und möglichst simpel. Wenn du noch ne Postman oder Paw Paket zusammenschnürst wo ein mal jeder request drin steht, wäre ich mega happy.

**Comment by telewolf** [comment]
Verstehe ich richtig, dass das Ziel ist z.B. eine Android oder iPhone App zu bauen, welche dann per API auf die Bilderkennung etc zugreifen kann?

**Comment by phoet** [comment]
ja, genau. es gibt schon 2 freiwillige, die da interesse bekundet haben und ggf etwas bauen möchten.
