### ISSUE TITLE
Daueranzeige bei mehreren Fotos sollte echte Zeiten enthalten.

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#242]
Wenn ich zwei Fotos hochlade, werden zur Dauer seltsame Zeiten angegeben. Ich fände es besser, wenn die angezeigten Zeiten sich nach den echten Foto-Daten richtet.

Beispiel: 20200621_102641.jpg und 20200621_122406.jpg

Dann erhalte ich folgenden Zeitraum:
Zeitraum: 10:26 ~ 11:26 (länger als 1 Stunde)

Besser wäre:
Zeitraum: 10:26 - 12:24 (länger als 1 Stunde)

**Comment by phoet** [comment]
Die Zeiträume sind in diskreten Einheiten, also zb. 1 Stunde. Wenn Du einen anderen Beobachtungszeitraum angeben möchtest, dann kannst Du dazu das Notizfeld nutzen.

**Comment by RalphBike** [comment]
Die diskreten Dauern anhand der Intervalle aus dem BKAT finde ich gut, aber die daraus resultierende zweite Uhrzeit ist für mich ein Fantasiewert. Hier würde ich mir eher min(Erstellungsdatum aller Fotos) bis (max(Erstellungsdatum der Fotos) vorstellen. 

Zum Beispiel oben: ich war um 11:26 einfach nicht da und habe um die Zeit nichts beobachtet, sondern eben um 12:24. Da ich hier eine Zeugenaussage mache, fände ich es gut, wenn sie einigermaßen korrekt dargestellt ist.

**Comment by phoet** [comment]
Wie gesagt, Du kannst dafür das Notizfeld benutzen. Falls eine Zeugenaussage notwendig werden sollte, bekommst Du ohnehin meines Wissens nach ohnehin einen Anhörungsbogen zugeschickt.

**Comment by Nakaner** [comment]
Ich habe gerade auch so einen Fall. Ein Fahrzeug stand von 17:56 Uhr an Tag 1 bis 08:59 Uhr an Tag 2 (eigentlich sogar länger, aber das hat für das Bußgeld keine Relevanz). Weg-li schreibt als Tatzeit nun "17:56 ~ 20:56 (länger als 3 Stunden)". Ich finde es sehr ungeschickt, wenn ich im Kommentarfeld bei solchen Fällen so etwas schreiben muss:

> Die obige Angabe zur Tatzeit ist falsch. Richtig ist stattdessen 17:56 bis 08:59.

Das ist für Sachbearbeiter doch irreführend, oder? Sie lesen erst das oben und dann stellen sie beim Lesen des Kommentars fest, dass der Text oben ihnen Märchen erzählt. Da überlege ich mir ernsthaft, ob ich solche Anzeigen nicht einfach von Hand schreibe (so Langzeitparker erwische ich eher selten).

**Comment by RalphBike** [comment]
Ja, geht mir ähnlich, Ich war (in deinem Beispiel) um 20:56 nicht vor Ort und möchte in Bezug auf diese Uhrzeit keine Aussage machen. Ich weiß z.B. nicht, ob das Auto zu der Zeit dort stand.

**Comment by phoet** [comment]
1. Die Tatzeit muss ein konkretes Datum sein
2. Der Beobachtungszeitraum muss eine Zeitspanne sein

Wenn Du das Auto garnicht so lange beobachtest, z.b. weil Du es erst Abends und dann morgens wieder siehst, dann solltest Du daraus 2 Anzeigen machen.

**Comment by mark-kubacki** [comment]
Das ist so nicht ganz vollständig: Stehen die Ventile vorher und nachher gleich, ist es nun am Antragsgegner nachzuweisen, dass das Auto zwischenzeitlich bewegt worden ist.
