### ISSUE TITLE
Besserer Workflow für Autofill-Meldungen für bessere QA

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#243]
Autofill-Meldungen wirken komplett, enthalten aber oft falsche Infos und der Workflow passt nicht richtig.

Bei manchen Meldungen schafft die Plattform es, "fertige" Meldungen zu erstellen: Kennzeichen, Marke, Farbe, Tatvorwurf, Dauer, "Wagen war verlassen", alles drin. Leider sind die Daten oft nicht korrekt und die Kontrolle geht nur über den Fließtext der share-Seite, was umständlich ist und zu viel Interaktion erfordert.

Aus meiner Sicht sollte der Benutzer hier besser in die Lage versetzt werden, die Anzeige zu prüfen und dann ggf. zu bearbeiten.
Bei solchen Anzeigen könnte z.B. über dem Mail-Text nochmal kurz das wichtigste zusammengefasst angezeigt werden, plus Bearbeiten-Button.

**Comment by phoet** [comment]
Solche Meldungen werden nicht gesondert gekennzeichnet, aber im allgemeinen scheint es wohl der Erwartung zu entsprechen, dass man erstmal auf der bearbeiten Seite landet.

**Comment by RalphBike** [comment]
Wäre auch okay für mich.
