### ISSUE TITLE
Sortierung nach Tatzeit sollte auch den Sekunden-Anteil der Aufnahmezeit verwenden

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#246]
Die Sortierung nach Tat- bzw. Aufnahmezeitpunkt ist nicht chronologisch, wenn man mehrere Fotos in der gleichen Minute aufnimmt. Meine drei Fotos von "02.07.2020 20:43" sind falsch sortiert.

Daher bitte die Sekunden des Aufnahmezeitpunkts mitverwenden. Anzeige ist IMHO nicht nötig.

Warum finde ich das wichtig? Weil dann aufeinanderfolgende Fotos des gleichen Wagens nebeneinander liegen und man besser mehrere Fotos einer Anzeige zusammenfügen kann.

Danke!

**Comment by phoet** [comment]
Du meinst die Sortierung im Massen-Upload, oder wovon sprichst du? Ein Screenshot sagt oft mehr als tausend Worte.

**Comment by RalphBike** [comment]
Cannot reproduce. Ich schließe.
