### ISSUE TITLE
GMail Hinweis

### ISSUE THREAD

**Issue by 4rne** [weg-li/weg-li#25]
Die GMail-App auf meinem Handy meldet bei der CC-Email zur Anzeige Folgendes:
![Unbenannt](https://user-images.githubusercontent.com/9700864/63091516-e3220780-bf5e-11e9-9850-1c03068c2582.png)

**Comment by phoet** [comment]
hi arne, danke für den hinweis.

weg-li schickt die emails mit deiner adresse im "from" wodurch es von google als spam klassifiziert wird. ich werde mal schauen ob es noch bessere wege gibt, die für die user einfach zu benutzen sind (und nicht irgendwelche DNS settings erforderlich machen).

https://postmarkapp.com/guides/best-practices-for-sending-on-behalf-of-your-users
https://support.google.com/mail/answer/1311182?hl=en

**Comment by phoet** [comment]
habe heute noch diverse änderungen gemacht, die hoffentlich dafür sorgen, dass die emails etwas weniger aggressiv von google als spam eingestuft werden.

**Comment by hzulla** [comment]
Wie wäre es mit dem Reply-To Header?

**Comment by phoet** [comment]
@hzulla meine befürchtung war, dass die behörden die dann nicht annehmen, wenn die nicht "from" benutzer sind. technisch gesehen sind die jetzt sauber, dann dort ist anzeigen@weg-li.de als sender hinterlegt, und die domain ist mit DKIM validiert durch sendgrid.

zudem möchte ich die reply-to adresse gerne verwenden um zukünfit automatische antworten zurück ins system zu speisen.

![Screen Shot 2019-08-20 at 11 05 02](https://user-images.githubusercontent.com/48745/63333844-69ad5f00-c33a-11e9-9f42-246c819e421b.png)

**Comment by phoet** [comment]
"Domain-based Message Authentication, Reporting and Conformance" geht halt nur mit einer adresse wo einem die domain gehört.

**Comment by phoet** [comment]
nutze jetzt personalisierte user email adressen von "@anzeige.weg-li.de" über die dann zukünftig auch automatisierte antworten im system verarbeitet werden können.

damit sollten jetzt keine SPAM klassifikationen mehr auftreten. allerdings könnte es jetzt sein, dass die behörden z.b. die absenderdomain ignorieren oder dergleichen. man wird sehen...

<img width="974" alt="Screen Shot 2019-08-22 at 18 43 03" src="https://user-images.githubusercontent.com/48745/63533304-ce201800-c50c-11e9-8e5d-943dcc1767c1.png">

**Comment by udkde** [comment]
Ein ähnliches System nutzt FragDenStaat.de, die E-Mail-Adressen durch welche auf ihrer eigenen Domain zu ersetzen und in die Adresse dann eine Ticketnummer einzubauen. Das hat bei FrageDenStaat jedenfalls noch zu keinen Problemen mit der Kommunikation mit den Behörden bei mir geführt.
