### ISSUE TITLE
Zeitraum und Tatzeit

### ISSUE THREAD

**Issue by mannih** [weg-li/weg-li#251]
Hallo Peter.

Was mir bei Meldungen oefter mal auffaellt: Waehle ich einen Zeitraum/ eine Dauer, deutlich ueber 3 Minuten, rechnet weg-li das scheinbar zur aktuellen Uhrzeit (oder dem Zeitstempel des Fotos?) dazu, so dass sich dann gerne mal eine Tatzeit ergibt, die in der Zukunft liegt.
Fiktives Beispiel: 

- Ich beobachte einen Verstoss um 7h
- Um 10 mache ich ein Foto und erstelle eine Meldung bei weg-li
- als Dauer gebe ich 'mehr als 3h an'
- weg-li errechnet 13h als Tatzeit

Mach ich da was falsch oder hab ich einen Denkfehler?

**Comment by phoet** [comment]
Die Tatzeit wird automatisch aus dem Beweisfoto ausgelesen (woher auch sonst). Wenn der Beobachtungszeitrum davor liegt musst Du die Uhrzeit entsprechend anpassen, in Deinem Fall 3 Stunden vorverlegen. Ist doch logisch oder?

**Comment by sfo** [comment]
Hier würde ich gern noch einmal einsteigen: Jeder hat sicher eine andere Erwartung, wie das Zeitfenster berechnet wird. Ich würde beispielsweise davon ausgehen, dass eine Foto gegen Ende der Tatzeit gemacht wird, da viele es sicher erst knipsen, wenn die 3 Minuten um sind, oder wie oben erwähnt nach längerer Beobachtung.

Eine andere (von weg-li) genutzte Möglichkeit ist, den Zeitpunkt des Fotos als Startzeit zu nehmen. 

Mir ist es jetzt schon passiert, dass ich die Nachbearbeitung vergessen habe, da dieses (meiner Erwartung widersprechende) Verhalten für mich nicht offensichtlich ist, und es keinen Hinweis darauf gibt, dass die Startzeit angepasst werden muss.

Es wäre schön, wenn es einen Hinweis auf den berechneten Zeitraum bereits in der Eingabemaske gäbe, sodass dies direkt ersichtlich ist und man die Zeit anpassen kann. Oder man kann irgendwo eine Option / ein Häkchen setzen, welche Variante bevorzugt wird.
