### ISSUE TITLE
PDF-Export: Überlappungen zwischen Unterschifts-Scan und URL bzw. Datum und Grußformel

### ISSUE THREAD

**Issue by Nakaner** [weg-li/weg-li#256]
Danke für das tolle Tool. In Karlsruhe [rät](https://ka-radler.blogspot.com/2020/02/harte-zeiten-brechen-fur-falschparker.html) @BjarneRest dazu, die Anzeige als PDF an das Ordnungsamt zu mailen. Deshalb nutze ich den PDF-Export.

Wenn man etwas Text als zusätzliche Anmerkungen angibt, wird ein Teil der URL durch die gescannte Grafik der Unterschrift verdeckt. Ebenso sind Grußformel (MfG) und Datum übereinander.

Das sieht dann so aus (Seite 2 enthält Fotos):

![text-ueberlappt](https://user-images.githubusercontent.com/3611273/90345870-b6e31000-e024-11ea-9937-95b0fe0b0517.png)

@phoet Schau dir einfach mit deinen Rechten eine meiner Anzeigen als PDF an, wenn du den Bug ohne Verpixelungen sehen möchtest.

**Comment by phoet** [comment]
PDF sind immer etwas fickelinsch... Schaue ich mir nach dem Urlaub mal an

**Comment by Nakaner** [comment]
Danke, jetzt sieht es gut aus.
