### ISSUE TITLE
Tippfehler im Verstoß 10 Meter Lichtzeichen

### ISSUE THREAD

**Issue by Maddosaurus** [weg-li/weg-li#257]
Eben aufgefallen:
Der Verstoß wird in der Auswahl und der Email als "Parkten näher als 10 Meter vor einem Lichtzeichen, mit Gefährdung (z.B. Ausweichen in Fließverkehr)" ausgegeben - sollte das nicht "Parken" (ohne t) sein?

**Comment by phoet** [comment]
gut gesehen
