### ISSUE TITLE
Adresse

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#26]
Sammle-Issue zum Feld „Adresse“

- bei der ermittelten Adresse steht meistens die Hausnummer vor der Straße. Amerikanisches Format? Wird das von den Behörden so akzeptiert?

-  Toll wäre ein Button neben dem Feld um sich die ermittelte Adresse bei OpenStreetMap anzeigen zu lassen und zu kontrollieren ob die Adresse stimmt. Bei Google Maps werden die Hausnummern nicht angezeigt.

- Toll wäre eine Batchverarbeitung um eine bestimmte Adresse bei mehreren Owi einzufügen, statt die Adresse bei jeder Owi einzeln einzufügen.

**Comment by telewolf** [comment]
- bei dem Verstoß „parken im kreuzungs- / Einmündung“ wäre es schön wenn als Adresse ein einheitliches Format für „Kreuzung:  Antonstraße Ecke Bertastraße“ bzw „Kreuzung: Antonstraße / Bertastraße“

**Comment by phoet** [comment]
arbeite gerade an einer karten integration 

<img width="894" alt="Screen Shot 2019-08-15 at 17 11 25" src="https://user-images.githubusercontent.com/48745/63104771-e1b50700-bf7f-11e9-8781-32835cb83789.png">

das format der adresse wird in dem zug auch angepasst.

**Comment by Maddosaurus** [comment]
Ich hatte mich bei den ersten Erfassungen auf die Input Placeholder verlassen und keine PLZ & Stadt angegeben. Dadurch werden die Fälle auf der Karte dann komplett anderen Städten zugeordnet.  
Vielleicht erweitert man den Placeholder auf  _Beispielstrasse 7, 1234 Stadt_

**Comment by phoet** [comment]
@Maddosaurus guter hinweis, ich habe da noch die stadt ergänzt, das sollte für das geocoding ausreichend sein.
