### ISSUE TITLE
Bei bestimmten Ordnungsämtern die Anzeige in PDF statt in Textform

### ISSUE THREAD

**Issue by BjarneRest** [weg-li/weg-li#260]
Moin Peter und co,

in Karlsruhe verlangt das Ordnungsamt die Anzeige als PDF, weil ihr die Unterschrift wichtig ist.

Bisher nutze ich den PDF-Export und sende die Datei dann selbst weg. Könnte man den Schritt nicht automatisieren?

Grüße!

**Comment by phoet** [comment]
Natürlich lässt sich das automatisieren!

**Comment by BjarneRest** [comment]
Ich bekomme einen Fehler 500, wenn ich den Haken setze

**Comment by phoet** [comment]
das ganze PDF serialisiert an den background job zu schicken war eine doofe idee, da hätte ich auch früher drauf kommen können.

**Comment by BjarneRest** [comment]
Sagst du Bescheid, wenn das erledigt ist?

**Comment by phoet** [comment]
https://github.com/weg-li/weg-li/commit/057db96b5329c6ade30a066bd0fb31a78d6db294
