### ISSUE TITLE
Android Chrome Abstürze

### ISSUE THREAD

**Issue by DorfNKB** [weg-li/weg-li#266]
![Screenshot_2020-09-23-19-46-33-638_com android chrome](https://user-images.githubusercontent.com/45639090/94049672-8fc2ef80-fdd5-11ea-8535-ab6e56d75fa3.jpg)
Auf meinem Android Handy stürzt Chrome reproduzierbar vor dem Hochladen von Fotos ab. Der Browser stoppt, sobald ich auf das "+" drücke. 

Handy: Xiaomi Mi9
Chrome Version 85.0.4185.101

**Comment by phoet** [comment]
Das hört sich nach einem Problem von Chrome an. Eine Website sollte niemals dazu führen, dass der Browser abstürzt.

**Comment by DorfNKB** [comment]
Ja, da stimme ich dir voll zu. Allerdings ist diese Seite die einzige die ich kenne bei der es passiert. Siehe GitHub.
Hatte lange keine Probleme mit der Seite. Leider kann ich dir aber kein genaues Datum nennen ab dem es nicht mehr funktionierte. ( Hab zwischenzeitlich nix gemeldet)
Hab mein Handy schon ein mal komplett zurückgesetzt... Keine Änderung.
Firefox scheint zu funktionieren.

Warum der Screenshot so bescheiden ist, weiß ich leider nicht, aber das Handy versucht den FilePicker zu laden.

**Comment by phoet** [comment]
Da kann ich leider überhaupt nicht weiterhelfen.
