### ISSUE TITLE
Sortierung in Übersicht auch nach Status

### ISSUE THREAD

**Issue by mstrangmann** [weg-li/weg-li#269]
Aktuell wird die Sortierung in Meldungen/Übersicht nach Erstellt und Tatzeit sortiert. Meiner Meinung nach wäre der Status noch wichtiger, denn gemeldete Meldungen sind sicher nicht mehr so von Bedeutung wir offene oder analysierte Meldungen, da dort aktiv noch Arbeit notwendig ist.

**Comment by phoet** [comment]
Das zu verallgemeinern halte ich für schwierig. Nutzer haben unterschiedliche workflows, siehe auch diese Diskussion https://github.com/weg-li/weg-li/issues/169

**Comment by phoet** [comment]
Stattdessen könnte man darüber nachdenken, was hier genau das Ziel ist. Will möglichst viele Meldungen in einem Schwung abarbeiten? Wäre dann ein dafür optimierter workflow besser geeignet anstatt Sortierungen zu ändern?
