### ISSUE TITLE
Fair Use Automatic / warnung

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#27]
„With great power comes great responsibility“

Obwohl das ständige zuparken von Fuss und Radwegen etc eine Rücksichtslosigkeit ist, möchte ich ungerne über das Ziel hinaus schiessen und mehrere Owi für das selbe Fahrzeug abschicken, bevor der Halter die erste Owi erhalten hat. Deswegen würde ich gerne eine Warnung erhalten, wenn ich für ein Kennzeichen eine Owi erfasse, für das ich innerhalb z.B. der letzten 4 Wochen bereits eine Owi abgesendet habe.

**Comment by phoet** [comment]
ja, das ist ein guter hinweis

**Comment by telewolf** [comment]
Wenn man noch höflicher sein möchte, hängt man dem fahrer eine gelbe karte ans auto mit einer letzten warnung und trägt das Kennzeichen mit status „verwarnt“ in weg-li. Owi dann nur wenn bereits ein Mal verwarnt.

**Comment by phoet** [comment]
😁 bei mir stehen wegli "spuckies" schon auf der Liste

**Comment by phoet** [comment]
Hoppi, falsch geclickt

**Comment by phoet** [comment]
Ab 5 Meldungen pro Monat erscheint ein Hinweis

**Comment by telewolf** [comment]
Danke!
