### ISSUE TITLE
Nach Massenupload: Gruppieren von Fotos durch Drag&Drop nach *links*

### ISSUE THREAD

**Issue by dbermbach** [weg-li/weg-li#275]
Wenn man viele Bilder hochlädt, muss man im Browser sehr weit rauszoomen, damit man Bilder vom unteren Ende der Liste noch in das Gruppierfeld oben "ziehen" kann (aka es ist sonst einfach nicht mehr auf dem selben Screen). Das passiert bei mir recht häufig, wenn Autos, die auf dem Hinweg da standen, auf dem Rückweg auch noch standen. Eine einfache Lösung dafür wäre, dass das Feld zum Droppen der Bilder entweder nicht oben sonder links oder alternativ in umgedrehter U-Form oben, links und rechts ist. Aktuell ist die Bildschirmbreite ja ohnehin nur bedingt genutzt.

**Comment by phoet** [comment]
Dass man den Button dafür benutzen kann hast Du gesehen?

**Comment by dbermbach** [comment]
Welchen meinst du? Den unten rechts für "je Foto eine Meldung"? Der ist zwar sehr praktisch, aber hilft dafür nicht weiter.

**Comment by phoet** [comment]
Neben jedem Bild ist ein ansehen und ein auswählen Knopf

**Comment by dbermbach** [comment]
Den hatte ich bisher nicht registriert, weil ich zum Ansehen immer das Previewbild angeschaut habe. Danke für den Tipp. Vlt. kann man den irgendwie sichtbarer machen oder beschriften statt Icon?

**Comment by phoet** [comment]
Steht schon ob im Hinweis drinne 😉 

<img width="847" alt="Screenshot 2020-10-04 at 21 20 34" src="https://user-images.githubusercontent.com/48745/95111914-7ceadc00-0740-11eb-8486-37e26960dfd4.png">
