### ISSUE TITLE
Emails werden von Google als Phishing wahrgenommen

### ISSUE THREAD

**Issue by jhohlfeld** [weg-li/weg-li#276]
Die Email einer Meldung wird von Google Mail mit Verdacht auf Phishing eingestuft, weil der Absender auf meinen Namen lautet, Google jedoch die Absender-Email als nicht zu meiner Organisation gehörend erkennt. Ich vermute, das könnte Weg-Li auf Dauer schaden.

<img width="1494" alt="Screenshot 2020-10-07 at 08 33 04" src="https://user-images.githubusercontent.com/497141/95295889-22549b80-0878-11eb-9b5c-6e722a017c47.png">

**Comment by phoet** [comment]
Das ist leider ein bekanntes Problem von Gmail. Zum Glück verwenden Ämter keine Google Produkte 😜

Wir implementieren alle Sicherheitsstandards für Email. Die Warnung siehst nur Du, weil Google dich natürlich kennt.
