### ISSUE TITLE
Hinweise etc werden gelöscht wenn zusätzliche Fotos hochgeladen werden

### ISSUE THREAD

**Issue by carstenhag** [weg-li/weg-li#280]
1. Hab Fotos hochgeladen
2. Wollte dann die Meldung bearbeiten und Hinweise schreiben. Mir ist eingefallen, dass noch ein Foto fehlte.
3. Hab ein Foto hinzugefügt, die Seite hat neu geladen
4. Hinweise und alles unten war weg :(

**Comment by phoet** [comment]
Das lässt sich technisch nicht so ohne weiteres anders lösen. Ein Lösungsansatz könnte ein Hinweis sein wie hier beschrieben https://github.com/weg-li/weg-li/issues/230#issuecomment-643951733

**Comment by carstenhag** [comment]
Ich stelle mir das so vor, dass man beim klicken auf das + icon (zum hinzufügen von Fotos) ein Dialog angezeigt bekommt in dem steht, dass man zuerst speichern muss. Also quasi wie du es geschrieben hast in dem Kommentar.
