### ISSUE TITLE
Editierung des finalen Anzeigentextes ermöglichen

### ISSUE THREAD

**Issue by carstenhag** [weg-li/weg-li#281]
Momentan füllt man ja die einzelnen Felder aus und kann nur bei "Hinweise" noch zustätzliche Infos hinzufügen.

Das passt soweit auch, außer, wenn ich mehrere Verstöße auf einmal oder eine genauere Tatzeit angeben möchte. Damit ich die Infos nicht wiederholt habe, würde ich gerne den "gerenderten" Text nochmal vorm Abschicken editieren, auf https://www.weg-li.de/notices/df247d379a89043a4d9f286c014325b9/share.

Beispiel: Es wird `Zeitraum: 15:23 ~ 15:33 (länger als 10 Minuten)` gerendert, ich hätte aber gerne `Zeitraum: 15:23 ~ 15:35 (länger als 10 Minuten)` geschrieben um Präzise zu sein.

**Comment by phoet** [comment]
Hallo Carsten, hierfür gibt es bereits einige Issues wie zb https://github.com/weg-li/weg-li/issues/42 in der erläutert wird warum es das als Feature nicht gibt und stattdessen zusätzliche Informationen im Hinweisfeld angefügt werden müssen.

Hier geht es in erster Linie darum, dass dann nicht mehr sichergestellt werden kann, dass die Anzeigen korrekt formuliert sind und alle wesentlichen Informationen enthalten.

**Comment by carstenhag** [comment]
Falls dann etwas fehlt wäre es ja das Problem des Nutzers (der eben zu viel gelöscht hat) und nicht durch weg-li verursacht. Ich sehe weg-li eher als Hilfstool, nicht als Anzeigen-Sherrif :).
