### ISSUE TITLE
Gruppieren/Sortieren von Fotos nach GPS-Koordinaten oder Kennzeichen

### ISSUE THREAD

**Issue by moeffju** [weg-li/weg-li#282]
Während der Pandemie gehe ich öfter und länger spazieren und komme bei diesen Gängen natürlich auch immer an vielen Kampfparkern vorbei. Häufig sehe ich die selben Fälle auch mehrmals am Tag. Bei Massenuploads kann ich bei Weg-li allerdings nur nach Datum oder Dateiname (der auf dem Datum basiert…) sortieren, was eine Zuordnung zu den selben Meldungen unnötig erschwert (als Beispiel, vorgestern war ich morgens 15 und abends 20 Minuten unterwegs und kam mit fast 170 Fotos zurück).

Es wäre super, wenn beim Massenupload auch nach GPS-Koordinaten (einfache euklidische Distanz gerechnet vom “ältesten” Foto sollte reichen) oder Kennzeichen sortiert/gruppiert werden könnte. Für letzteres wäre ein Zwischenschritt denkbar, bei dem man en masse Kennzeichen/Fabrikat/Farbe glattziehen kann.

Ein möglicher Flow wäre zB:

- Massen-Upload starten
- Analyse beginnt im Hintergrund nach jedem hochgeladenen Bild
- Wenn Upload fertig, kann ich in einem Zwischenschritt zu allen Fotos die erkannte Position, Kennzeichen, ggf. Hersteller/Farbe sehen und en masse ändern (zB Dropdowns, Multi-Select)
- Danach kommt der bekannte Sortieren/Gruppieren-Schritt

(Und als side note, auf manchen Fotos sind mehrere Verstöße zu sehen, super wäre das auch gleich markieren zu können - behelfe mir jetzt mit Duplikat der Meldung, aber das ist umständlich und verwirrend weil man die Warnung ignorieren muss und so…)

**Comment by moeffju** [comment]
Ich clone mir jetzt mal den Code und schau mal, ob ich da einen Ansatz finde, das irgendwie mit wenig Aufwand zu implementieren, freue mich aber auch über Hinweise wie sowas in der Codebase am besten “richtig” umgesetzt würde.

**Comment by phoet** [comment]
Die Infos werden erst nach dem Gruppieren Schritt extrahiert, die stehen also da noch nicht zur Verfügung.

**Comment by moeffju** [comment]
Ja, das würde ich halt mit ändern müssen 😅Am Aufwand (bzw den Kosten für GCV) sollte das nichts ändern, oder? Bzw. könnte mir auch vorstellen, erst nur die lokale Analyse zu machen (Exif), dann Clustern, dann den Rest. Wdyt?

**Comment by phoet** [comment]
Es würde den ganzen Prozess auf jeden fall deutlich verlangsamen. Auch um Exif zu machen muss das Bild erstmal aus der GCloud geladen werden, auch das ist zeitaufwändig und geschieht momentan im Hintergrund. Da müsste man erstmal eine synchronisation der Prozesse bauen.

Vielleicht macht es sinn einen anderen Weg neben den bisherigen zu bauen, der so funktioniert wie du es beschreibst, wo dann zu jedem Foto schon die Daten analysiert wurden und man "nur" noch für 170 Fotos alles korrigieren muss. Dann könnte man auf "OK" drücken und die Gruppierung würde dann automatisch von statten gehen anhand des Kennzeichens.

**Comment by phoet** [comment]
Das würde ich dann unterscheiden als "visuell/manuell Gruppieren" "automatisch Gruppieren"

**Comment by moeffju** [comment]
Werden die Bilder z.Zt. direkt zu GCS hochgeladen? Oder könnte man erst/parallel lokal EXIF extrahieren, Thumbs erzeugen etc. und dann alles hoch schieben?

**Comment by phoet** [comment]
Die werden über eine presigned URL direkt hochgeladen. Das wäre sonst auch ziemlich tödlich für heroku so viele große bilder da durchzuschleifen.

**Comment by moeffju** [comment]
Hmm. Gibt’s in der Google Cloud vielleicht etwas, um Exif direkt vom Storage auszulesen, ohne down/upload? “serverless” functions oder was in GCP vielleicht?

**Comment by moeffju** [comment]
https://github.com/firebase/functions-samples/tree/master/exif-images looks like it should work, wdyt?

**Comment by phoet** [comment]
Wie oben bereits beschrieben würde ich denken, dass nur eine komplette Änderung des Flows eine sinnvolle Alternative ist.

BTW, deine E-Mail Adresse bei weg-li scheint falsch/kaputt zu sein, zumindest mag der mailserver da nichts zustellen.

**Comment by moeffju** [comment]
Hm, vor ner Stunde ging's noch, das hier ist der selbe Mailserver. Schaue nachher in die Logs, gerade unterwegs, aber könnte es sendeseitiges debouncing sein?

**Comment by dbermbach** [comment]
Zwei Kommentare dazu (auch wenn es ein nettes Feature ist):
1) streng genommen darfst du zwei Fotos vom Morgen und Abend nicht zu einer Meldung zusammenfassen, sofern du nicht bspw. mittels Dokumentation der Ventilposition beweisen kannst, dass sich Kfz nicht bewegt hat. Meistens wird der Halter nicht bestreiten, dass das Kfz nicht dazwischen bewegt wurde, aber falls doch könntest du rechtliche Probleme wegen Falschaussage bekommen. Der einfache Workaround ist dann die beiden Situationen einzeln anzuzeigen. Entweder fasst dann das Ordnungsamt die zusammen oder es gibt zwei Tickets...
2) für die Situation mit den mehreren Verstößen funktioniert es mit dem aktuellen Workflow ganz gut, einfach das gleiche Bild mehrmals zu machen.
