### ISSUE TITLE
Add i18n so people who don’t speak German can join the fight :)

### ISSUE THREAD

**Issue by moeffju** [weg-li/weg-li#285]
I have recommended weg-li to a bunch of friends, but not all of them are fluent or comfortable in German, especially when it comes to legalese. It would be helpful to mark all text etc. up for i18n so that the UI of weg-li can be made available in other languages such as English (or simplified German?).

**Comment by phoet** [comment]
Since the legalese has to be in german, I was always hestiant to provide a translated version. It would also not be very high on my priority list.

**Comment by carstenhag** [comment]
Found [this tweet](https://twitter.com/lehtimaeki/status/1441853781004767238) the other day about not 100% understanding the german content.

I think the most critical party are the descriptions of violations & the final *Anzeigentext*. These two parts would need disclaimers that it's a best-effort translation, but apart from that, it's probably fine.

**Comment by axalandra** [comment]
I'd love to contribute by translating to English! Some localization tools offer free services for open source projects, e.g. [Crowdin](https://crowdin.com/page/open-source-project-setup-request), [Lokalise (last paragraph)](https://docs.lokalise.com/en/articles/1400453-free-plan)

**Comment by phoet** [comment]
The critical texts can not be easily translated as it is legalese. I'm not sure it's feasible to translate things like the offenses into english. As it is the most critical point, i'd probably start there. Translating the rest of the page into english is mostly a technically annoying sisyphus task.

**Comment by sgauert** [comment]
If you provide a little docu where to find the texts I'd be happy to help translating.

**Comment by phoet** [comment]
You would need to translate the BKAT and provide detailed explanation in english https://weg.li/charges?classification=5
