### ISSUE TITLE
Wie importiert man die Districts etc. für local dev?

### ISSUE THREAD

**Issue by moeffju** [weg-li/weg-li#287]
Da ich dazu weder in der README noch etwas offensichtliches im Code gefunden hatte – wie kann ich für lokale Entwicklung & Testen die Districts etc. am besten importieren, um zu einem voll lauffähigen Weg-li zu kommen? Ich vermute, diese Daten sind nicht einfach unter einer stabilen URL downloadbar, so dass man einen Task dafür machen könnte…?

**Comment by phoet** [comment]
Ich generiere die Daten entweder hiermit https://github.com/weg-li/weg-li/blob/master/lib/tasks/development.rake#L5 oder erstelle sie von Hand.

**Comment by phoet** [comment]
Die Bezirke kann man über diesen Endpunkt laden: https://www.weg-li.de/districts.json oder https://www.weg-li.de/districts.csv

**Comment by moeffju** [comment]
Ahh, top, den Fabricator hatte ich gefunden, wollte aber für die GPS-Clusterung lieber “echte” Daten. Die API-Endpoints sind aber super. Ich würde das auch gleich mal in die README schreiben, damit alle lokal ein möglichst “echt-nahes” Env hinkriegen können.

**Comment by moeffju** [comment]
#288 bringt die Info(s) in die README
