### ISSUE TITLE
500 on clicking an email provider login link again

### ISSUE THREAD

**Issue by serioushaircut** [weg-li/weg-li#3]
Hi P,
I just clicked on an email login link again, apparently one that I clicked before and got a 'something went wrong'.
Reproducible with invalid/non-present tokens.
From here: https://github.com/weg-li/weg-li/blob/master/app/controllers/sessions_controller.rb#L5

But I did not dig deep into what is going on. Gonna fork and try it out myself later.
Cheers,
B

**Comment by phoet** [comment]
👍 true, the token validation is not handled in detail, not sure why it actually 500.

this is an oauth strategy https://github.com/weg-li/weg-li/blob/master/app/extensions/omni_auth/strategies/email.rb#L10-L23

**Comment by phoet** [comment]
fixed it along the way
