### ISSUE TITLE
Bilder im Hochformat werden gedreht

### ISSUE THREAD

**Issue by hzulla** [weg-li/weg-li#30]
Siehe Meldung 16.08.2019 08:07 - Bilder im Hochformat zeigt weg-li jetzt gedreht im Querformat an. Dies war früher nicht so, siehe Meldung vom 10.08.2019 17:58. Ich glaube, dieses Problem tritt auf, seitdem die Bildauswahl eine Vorschau vor dem Upload hat. Vermutlich interpretiert irgendeine beteiligte Library das Rotations-Exif-Tag falsch.

**Comment by phoet** [comment]
grmpf! es gibt nur kaputte javascript libraries...

**Comment by phoet** [comment]
mit was für einem browser benutzt du das gerade?

anscheinend gibt es da problemchen im iOS safari

http://plugins.krajee.com/file-input/plugin-options#autoOrientImage

**Comment by hzulla** [comment]
Chrome / Android. Es gab aber auch einen Schwung App-Updates für mein Telefon und das Verhalten der Kamera könnte sich geändert haben. Die Bildvorschau-App auf dem Telefon zeigt das Bild im Hochformat, die Bildvorschau auf weg-li ist beim gleichen Bild gedreht.

**Comment by phoet** [comment]
Da werden Varianten generiert, evtl muss man denen noch die Orientierung beipulen

**Comment by phoet** [comment]
yo, das hat bei diesem foto geholfen! hoffen wir mal, dass dadurch nicht andere fotos kopf stehen 😄
