### ISSUE TITLE
In Meldung Foto hinzufügen schlägt fehl wenn kein TB ausgewählt ist

### ISSUE THREAD

**Issue by moeffju** [weg-li/weg-li#307]
Wenn man bei einer bestehenden Meldung, die noch unvollständig ist (keinen Verstoß ausgewählt) ein neues Foto hochladen will, schlägt es “still” fehl: Das Overlay verdeckt die kleine Validation-Meldung, dass ein Verstoß ausgewählt werden muss.

Ich schätze, dass das ein Versuch war, den Verlust eingegebener, aber noch nicht gespeicherter Daten bei Upload zu verhindern. In dem Fall sollte dann ggf. ein Speichern ohne Validierung ermöglicht werden oder so?

**Comment by phoet** [comment]
Ja, in der Tat, das ist eher unpraktisch
