### ISSUE TITLE
Option cc: emails an Nutzer zu deaktivieren

### ISSUE THREAD

**Issue by foss-** [weg-li/weg-li#321]
Da die Fall Historie im weg-li Konto dokumentiert ist, benötige ich die Fälle nicht in meinem E-Mail Konto. Daher wäre eine Option schön, um cc: global zu deaktivieren.

**Comment by phoet** [comment]
Wir schicken die E-Mail immer im CC. Das ist die einzige Möglichkeit den Versand zu dokumentieren. Diese Option werden wir deshalb nicht anbieten. Wenn die E-Mails stören kann man einen Filter im E-Mail Programm konfigurieren.
