### ISSUE TITLE
GPS-Icon in Meldungsübersicht

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#325]
Ich schlage hiermit ein Icon vor, das Meldungen in der Übersicht kennzeichnet, bei denen die GPS-Auswertung geklappt hat. Alternativ ein Icon, das Fehlschläge kennzeichnet.

Dann könnte man frühzeitig erkennen, dass und wie oft/bei welchen Fotos die Auswertung gescheitert ist und man ggf. den Upload korrekt wiederholen sollte. Das spart im Fehlerfall Zeit.

**Comment by phoet** [comment]
Meinst Du jetzt beim Bearbeiten des Massen-Upload? Bei den Meldungen selber gibt es schon einen Hinweis wenn keine GPS-Daten vorhanden sind. Da die EXIF-Metadaten erst nach dem Anlegen einer Meldung ausgelesen werden können diese Daten noch nicht beim Massen-Upload angezeigt werden.

Aus meiner Sicht würde es nur Sinn machen dies dort anzuzeigen, weil dann sämtliche Bilder keine GPS-Daten enthalten, denn die gehen ja nicht irgendwie manchmal bei einzelnen Bildern verloren. Eigentlich müsste man eine Warnung schon VOR dem Hochladen anzeigen.

**Comment by RalphBike** [comment]
Hi, ich kann nicht genau beurteilen, wann und so der richtige Ort ist.

Mein Wunsch ist: im Massenupload *früh* den GPS-Status *mehrerer* Fotos auf einen Blick Infos zu kriegen und dann entsprechend reagieren zu können. Für mehrere Fotos gleichzeitig, nicht einzeln.

Ätzend ist vor allem, nach dem Upload von xxx Fotos festzustellen, dass sie alle kaputt waren und sie einzeln finden und löschen zu müssen, dabei was zu übersehen und nach Dublette oder Lücken zu haben und die wieder finden und reparieren zu müssen.

BTW, die neuen blauen Buttons und das neue Logo sind nett!
