### ISSUE TITLE
Mehr Statistik zu den eigenen Meldungen

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#326]
Hi, die bisherige Statistik ist gut, aber zeitlich leider zu begrenzt. Ich fände es gut, sehen zu können, in welchem Jahr ich wieviel gemacht habe und wieviel ich pro Monat gemacht habe, um grob das Jahr rekapitulieren zu können. Diese Angaben wären über einen unbegrenzten Zeitraum gut.

Die Statistiken nach Kennzeichen, Tatvorwürfen, etc. muss nicht für die ganze Zeit verfügbar sein, aber für das laufende und eventuell das letzte wären sie ebenfalls gut.

Warum? Gamification! Ich finde es spannend und motivierend zu sehen, wann ich wie aktiv war. Oder wer im Lauf eines Jahres wieviel Zuwendung bekommen hat. Die Anzahl der Anzeigen pro Kennzeichen erleichert auch die Argumentation gegenüber der Bussgeldstelle zu Vorsatz.

**Comment by phoet** [comment]
Grundsätzlich spricht da nichts dagegen, steht aber nicht weit oben auf der TODO-Liste.

**Comment by phoet** [comment]
ich war gerade zufällig an der stelle zu gange, da konnte ich das gleich mit hinzufügen

https://github.com/weg-li/weg-li/pull/328
