### ISSUE TITLE
Spalte „Zeitpunkt Verstoß“

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#33]
Ich würde die Meldungen gerne nach dem Zeitpunkt des Verstoßes sortieren und hätte deswegen gerne diese zusätzliche Spalte.

**Comment by phoet** [comment]
in der tat. leider ist dieser wert erst da, wenn man die daten ausgefüllt hat. sobald die analyse der bilder automatisch angestoßen wird und damit auch das datum sofort verfügbar ist, werde ich diese mit in die übersicht aufnehmen.

**Comment by telewolf** [comment]
Kann man den Wert nicht anhand der ctime der Bilder vorausfüllen. Bzw was würde dagegen sprechen?

**Comment by phoet** [comment]
Das ist eine metainformation von Unix. Das steht nicht in den Dateien selber und der Browser hat soweit ich weiß keine Möglichkeit darauf zuzugreifen.
