### ISSUE TITLE
Mehr Statistik zu den eigenen Meldungen über Jahre und Monate (zweiter Versuch)

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#336]
Hi, mein Ticket #326 ist leider schon geschlossen und ich finde keinen Weg, es wieder zu öffnen. 
Die Umsetzung aus #326 ist gut, allerdings betrifft sie nur das Nice-to-have und nicht meinen Haupt-Wunsch. Daher kommt hier ein partieller Klon, sorry.

------------------

Ich fände es gut, sehen zu können, in welchem Jahr ich wieviel gemacht habe und wieviel ich pro Monat gemacht habe, um grob das Jahr rekapitulieren zu können. Diese Angaben wären über einen unbegrenzten Zeitraum gut.

Warum? Ich finde es spannend und motivierend zu sehen, wann ich wie aktiv war.

**Comment by phoet** [comment]
Es ist eher unwarscheinlich, dass diese detaillierten Statistiken für viele nutzer relevant sind, weshalb die Umsetzung keine hohe Priorität hat.

Die Seite kann mit unterschiedlichen Query-Parametern aufgerufen werden, z.b. das Jahr https://github.com/weg-li/weg-li/blob/190de0d7d4645c80ab7276a23ac5882e14da977a/app/controllers/notices_controller.rb#L76

Wenn es dir sehr wichtig ist, kannst Du Dir eine Statistik auch selber basteln. Deine kompletten Daten kannst Du dir so herunterladen https://www.weg-li.de/notices/dump.json

**Comment by RalphBike** [comment]
Den Controller muss ich mir noch anschauen. Das JSON ist aber schon mal sehr nett und eine gute Basis für beliebige lokale Auswertungen. Bitte beibehalten! :+1:
