### ISSUE TITLE
„Dateien auswählen“ reagiert nicht

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#34]
Wenn man auf „Hochladen und weiter“ klickt, ohne vorher ein foto hichgeladen zu haben, gibt es zu recht eine Fehlermeldung. Anschließend reagiert der Button „Dateien hochladen“ nicht mehr. Evtk gemeinsamkeit mit dem Issue „nicht funktionierender Mülleimer“?

**Comment by phoet** [comment]
kann ich beides nicht nachvollziehen. die anwendung hängt momentan manchmal etwas. das liegt daran, dass die asynchrone verarbeitung noch mit in den web prozessen passiert, das baue ich aber gerade noch um.

**Comment by telewolf** [comment]
Bei mir liess sich das gestern Abend zuverlässig reproduzieren. Hab eine Video davon, dass Dateiformat kann ich bei Github aber nicht hochladen. Workaround war abmelden und wieder anmelden.

**Comment by phoet** [comment]
Wenn's sich mit sowas wie ein und ausloggen beheben lässt, dann ist es in der Regel irgendwo im Browser kaputt gegangen. Ich werde es im Auge behalten, hatte selbst aber noch nicht so ein Problem

**Comment by phoet** [comment]
Habe übrigens gerade die Background Queue live gestellt, dadurch sollte die Anwendung deutlich schneller reagieren
