### ISSUE TITLE
Bitte um Eingangsbestätigung und Aktenzeichen optional machen

### ISSUE THREAD

**Issue by Nakaner** [weg-li/weg-li#346]
E-Mails an die Behörde enthalten folgenden zwei Sätze:

> Bitte bestätigen Sie Ihre Zuständigkeit und den Erhalt dieser Anzeige mit der Zusendung des Aktenzeichens an local-part@domain.tld.
> Falls Sie nicht zuständig sein sollten, leiten Sie bitte meine Anzeige weiter und informieren Sie mich darüber.

Die Bestätigung der Zuständigkeit ist überflüssig, wenn man schon ein paar Anzeigen an die jeweilige Behörde geschickt hat. Wer viel anzeigt und Indizien oder gar Beweise hat, dass den Anzeigen nachgegangen wird, interessiert sich (zumindest ist das bei mir so) nicht mehr für den Einzelfall und dessen Ausgang. Entweder nervt man damit die Behördenmitarbeiter, fördert deren Verdruss oder macht die E-Mails unnötig lang. Manche Behörden antworten nur bei Rückfragen (z.B. Karlsruhe), dort sind diese Sätze überflüssig.

Ich würde gerne meine E-Mails an die Behörde i.d.R. ohne die oben zitierten Sätze versenden. Dafür schlage ich eine Option vor, diese zwei Sätze deaktivierbar zu machen. Standardmäßig dürfen sie gerne aktiv sein (so wie die Versand-als-PDF-Option).

**Comment by phoet** [comment]
Die E-Mails sind standardisiert und werden von den Ämtern als Massenware verarbeitet. Ein Customizing ist nicht zielführend.
