### ISSUE TITLE
Mapbox/OSM Kacheln werden sehr klein angezeigt

### ISSUE THREAD

**Issue by chk1** [weg-li/weg-li#348]
Die Kacheln der neuen Mapbox-Karten werden bei mir zu klein angezeigt, so dass Hausnummern und Straßennamen fast nicht mehr lesbar sind.

Ich vermute, dass dies an dem fehlenden Parameter `tileSize` liegt, der beim Leaflet Aufruf `L.tileLayer` noch ergänzt werden muss. Standard tileSize bei Leaflet ist 256x256 aber die z.Zt. verwendeten Kacheln sind 512x512 groß

https://github.com/weg-li/weg-li/blob/53b1a0cdbe70dcf4b87b5964b8e46cfb077560c5/app/javascript/src/maps.js#L36

Aus der Mapbox Doku:

>If you do not include the `tileSize: 512` and `zoomOffset: -1` options, your map will still load but labels, icons, and other features may appear much smaller than expected.

https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/

Screenshot der Falschparker-Karte auf max. Zoomlevel in Firefox 84.0.2, Windows 10:

![image](https://user-images.githubusercontent.com/828496/104357025-f1d26c80-550c-11eb-8e65-f1eb7a998653.png)

**Comment by phoet** [comment]
Danke für den Hinweis. Auf Retina-Displays fällt das garnicht weiter auf.
