### ISSUE TITLE
WiNOWiG XML: Für Ort/PLZ des Anzeigenden werden fälschlicherweise Ort/PLZ des Tatorts gesetzt

### ISSUE THREAD

**Issue by localh0rzd** [weg-li/weg-li#350]
Während Name, Straße und Hausnummer korrekt sind, werden die PLZ und Ort des Tatorts übernommen.

**Comment by phoet** [comment]
@localh0rzd 👏 gut gesehen! zum glück wird es in der mehrzahl der fälle kein großes problem gewesen sein.
