### ISSUE TITLE
Bild Upload via API

### ISSUE THREAD

**Issue by Lergin** [weg-li/weg-li#352]
Die API ermöglicht es, wenn ich es richtig verstanden habe, neue Meldungen zu erstellen. Hierfür ist es notwendig, dass ein entsprechendes Bild bereits hochgeladen wurde. Dieses hochladen muss allerdings direkt zu Google Cloud Storage geschehen und der uploads Endpunkt erhält dann lediglich Informationen über das hochgeladene Bild. Dieses hochladen zu Google Cloud Storage ist bei der Verwendung der API nur sehr schwer umsetzbar. Es wäre also sehr hilfreich wenn Bilder direkt zu einem API Endpunkt hochgeladen werden könnten ohne hierfür den Google Cloud Storage direkt zu verwenden.

**Comment by phoet** [comment]
Welches Problem besteht beim Hochladen zu einem Server von Google im Gegensatz zu einem anderen Server (von Google)?

**Comment by Lergin** [comment]
Zum direkten Hochladen zu Google Cloud Storage wird eine Authentifizierung für den entsprechenden Bucket benötigt. Diese ist mit dem API Token, soweit ich das erkennen kann, nicht möglich.

**Comment by phoet** [comment]
Über den uploads endpoint werden pre-signed urls für den generiert mit denen dann die authentifizierung erfolgt.

Vielleicht ist es sinnvoller darüber zu sprechen was genau du vor hast, bzw welche Probleme Du bei der Benutzung der API hast.

Derzeit gibt es keinen aktiven Nutzer, der mir bekannt wäre. Da muss sicherlich noch etwas getan werden um das vollumfänglich einzusetzen.

**Comment by Lergin** [comment]
Ah so funktioniert das, danke! Dann werde ich es damit mal weiter probieren :) Ich melde mich wenn ich wieder auf Probleme stoße oder ich irgendwann dazu komme damit erfolgreich eine Anzeige erstellt zu haben :)

**Comment by phoet** [comment]
@Lergin ich arbeite gerade etwas an den rauhen ecken der api. habe hier mal ein beispiel in ruby implementiert wie das zu benutyen wäre.

**Comment by Lergin** [comment]
Das wird sicherlich hilfreich sein wenn ich es mir nochmal ansehe, vielen dank!
