### ISSUE TITLE
Filter Meldungsübersicht

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#36]
Ein Filter für die Anzeige der Meldungen wäre natürlich auch klasse. Nach Kennzeichen, Zeitraum, PLZ, Status...

**Comment by phoet** [comment]
gute idee, sehe ich aber im moment eher mit niedriger priorität

**Comment by telewolf** [comment]
Ist da im Moment Platz um in der Meldungsübersicht einen Kennzeichenfilter einzubauen oder ist das noch zu früh?

**Comment by telewolf** [comment]
Nach Kennzeichen geht ja schon (mega geil!) und nach Status geht ja auch schon. 

Ticket erst Mal schliessen?

**Comment by phoet** [comment]
siehe auch https://github.com/weg-li/weg-li/issues/99
