### ISSUE TITLE
Support for 1Password to fill email login on iOS

### ISSUE THREAD

**Issue by foss-** [weg-li/weg-li#360]
With 1Password installed on iOS 14.4 and selecting email login, it is currently not possible to use 1Password to autofill the email address. Would be nice to support this to simplify the login. Tested with Firefox 30 and Safari.

Works fine on Firefox desktop.

**Comment by phoet** [comment]
<img width="1076" alt="Screenshot 2021-01-31 at 13 25 12" src="https://user-images.githubusercontent.com/48745/106383730-d5b54300-63c7-11eb-9f56-18c942a6893c.png">

**Comment by foss-** [comment]
Tried resaving existing email in new 1P entry on desktop. But problem persisting.

Currently works via workaround: press "…" left of URL bar > Share page with… > 1Password but this is more complicated than it should be.

Would expect to have 1P entry show above the iOS keyboard.

![1p](https://user-images.githubusercontent.com/5708172/106383893-9b987100-63c8-11eb-87ca-aaa254b30bde.jpeg)

**Comment by phoet** [comment]
I have no idea how 1Password decides to store or suggest login form info TBH. The login form had an `autocomplete=off` attribute that I just removed. 🤷‍♂️

**Comment by foss-** [comment]
Not sure what is missing.
Looking at https://support.1password.com/ios-autofill/ and https://support.1password.com/1password-extension-ios/ the latter referring to workaround method. I do not understand why for other websites 1Password instantly shows the corresponding login above the keyboard. Maybe some web app thing? For the associated domain tried both https://weg.li and https://www.weg.li
