### ISSUE TITLE
Karte: Cluster-Count nicht lesbar (fehlender Kontrast)

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#366]
Hi, die Anzahlen in den Cluster-Markern sind leider kaum lesbar.

Betroffen ist:
Rot-Orange (schlecht lesbar)
Gelb (sehr schlecht)
Grün (sehr schlecht)

Tritt auf mit FF und Chrome unter Windows und Linux.

URL: https://www.weg-li.de/map?display=cluster&district=Hamburg&since=90

Außerdem vermisse ich den Fullscreen-Button für die Karte. Gibts den noch? Der war super! Andernfalls ist die Karte doch sehr schießschartenartig. Danke!

**Comment by phoet** [comment]
Der Text der Marker hat inzwischen einen besseren Kontrast.
