### ISSUE TITLE
Nachträgliches hinzufügen von bildern zu einer Meldung 

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#37]
Ist im Moment nicht möglich? Dann Meldung löschen und neu anlegen?

**Comment by phoet** [comment]
Wenn alle Fotos gelöscht sind kommt erneut der filepicker. Das ist im Moment der Einfachheit halber, damit Schritt 2 nicht zu kompliziert wird.

**Comment by phoet** [comment]
ist jetzt möglich
