### ISSUE TITLE
Zeugenaussage nicht durch Wiederverwendung von alten Informationen verfaelschen

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#372]
Hi, aktuell ist es so, dass bei bekannten Kennzeichen (?) einige Daten aus vorherigen Anzeigen wiederverwendet werden.

Das finde ich als "lucky guess" beim Tatvorwurf okay. Bei spezifischeren Daten wie Zeitraum und Kommentar verfälscht es potentiell meine Zeugenaussage, erhöht die Fehlerquote und vergrößert den Bearbeitungsaufwand.

Konkret:

- Ich lade ein einziges Foto hoch, das Kennzeichen wird automatisch erkannt und anscheinend gab es schon eine Anzeige mit diesem Kennzeichen. In der neuen Anzeige steht ein Zeitraum "mindestens 3h", was nicht sein kann, da ich nicht zwingend eine solche Aussage machen möchte, schon gar nicht mit nur einem Foto.

- Ich lade ein Foto hoch und in meinem Kommentar stehen sehr spezifische Infos aus einer anderen Anzeige, in meinem Fall die Beschreibung eines alten Beobachtungszeitraums. Ich muss den Text von Hand löschen.

Besser wäre aus meiner Sicht:

- Nur Tatvorwurf wiederverwenden

- Die echten Zeiträume aus mehreren Fotos berechnen und exakt angeben (mindestens 3h, von 17:01 bis 08:35), dann kann auch die manuelle Angabe im Kommentar entfallen.

**Comment by phoet** [comment]
Ja, so unterschiedlich sind die Geschmäcker! Die Übernahme des Hinweises haben wir vor kurzen erst auf Wunsch von anderen Usern eingebaut. Wir werden in Kürze ohnehin dieses "gerate" etwas umbauen, damit klar ist welche Daten woher kommen.

Was den Zeitraum angeht, so wird dieser automatisch aus den Beweisfotos extrahiert. Sollte dem nicht so sein, bitte ein Beispiel einfügen, wo das nachvollzogen werden kann.

**Comment by phoet** [comment]
Ein Link zu einer unbearbeiteten Anzeige, am besten per E-Mail

**Comment by RalphBike** [comment]
Okay, ich habe extra 2 Fotos gemacht, Mail ist raus.

**Comment by phoet** [comment]
Die Suggestions werden anders funktionieren, deshalb ist soetwas nicht mehr nötig.

**Comment by Nakaner** [comment]
Ich finde die Vorauswahl der Parkdauer ebenfalls bedenklich. Bei der Erstanzeige des Fahrzeugs wird diese aus den EXIF-Headern der Fotos ermittelt. Das ist nachvollziehbar und ein Verhalten, das ich auch so erwarte. Ich prüfe diese Angabe deshalb nicht noch einmal genau nach.

Wenn ich eine Anzeige eines Wiederholungstäters anlege, muss ich jedes Mal die Bilder öffnen und im Kopf die Dauer berechnen, weil der Wert aus einer früheren Anzeige stammt. Mindestens ein Warnhinweis "aus deiner letzten Anzeige übernommen" wäre sinnvoll. Gerade dann, wenn ich bei regelmäßigen Veranstaltungen regelmäßig Falschparker aufschreibe und regelmäßig meine "Stammkunden" zur Kasse bitte, nervt es (diese Fälle sind nicht umsetzungswürdig).

Dass das Kommentarfeld bei Wiederholungstätern vorausgefülllt ist, stört mich nicht, da ich sowies dort jedes Mal die TBNR eintrage (die wichtigen hängen als Zettelchen am Bildschirm).
