### ISSUE TITLE
„Du hast schon eine Meldung für dieses Datum mit identischem Nummernschild“ und Zeitzone?

### ISSUE THREAD

**Issue by maltehuebner** [weg-li/weg-li#373]
**Reproduzierung**
1. Lege eine Anzeige für einen Falschparker an. Die Tatzeit sei beispielsweise der 15. Februar um 1:43 Uhr.
2. Lege eine weitere Anzeige für den gleichen Falschparker an. Die Tatzeit sei dieses Mal der 16. Februar um 0:32 Uhr.

**Beobachtung**
Es erscheint der Hinweis „Achtung, du hast schon eine Meldung für dieses Datum mit identischem Nummernschild, falls es OK ist einfach fortfahren.“

**Erwartung**
Da es sich offenkundig nicht um das gleiche Datum handelt, erscheint auch kein Hinweis.

**Vermutung**
Ich vermute mal, dass im Hintergrund die Datumsangaben nach UTC umgerechnet werden, so dass beide Taten am 15. Februar begangen wurden? Dafür spricht, dass nach meiner Beobachtung diese Meldung nur auftaucht, wenn zwei Anzeigen mit dem gleichen Kennzeichen an aufeinanderfolgenden Tagen zwischen Mitternacht und 2 Uhr morgens aufgenommen wurden.

**Comment by phoet** [comment]
Ja, der Datumsvergleich wird in der Datenbank gemacht. Ich denke mit diesem Tradeoff kann man leben, es ist ja lediglich ein warnhinweis als Plausicheck.
