### ISSUE TITLE
Verstoß ergänzen: Sie <hielten/parkten> nicht Platz sparend.

### ISSUE THREAD

**Issue by Nakaner** [weg-li/weg-li#377]
Folgender Verstoß kann nicht ausgewählt werden:

Vorwurf: Sie <hielten/parkten> nicht Platz sparend.

TBNR: 112456

Regelsatz: 10 Euro

https://www.weg.li/charges/112456

**Comment by phoet** [comment]
Der Übersichtlichkeit halber sind nicht alle Verstöße enthalten. Für solche Fälle bitte "sonstige" auswählen und im Hinweisfeld erklären.
