### ISSUE TITLE
Versendete Anzeigen sollten nicht mehr editierbar sein.

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#379]
Der Bearbeiten-Link zu einer versendeten Anzeige funktioniert weiterhin und ermöglicht auch das Bearbeiten und Abspeichern. Außerdem ist es auf der Edit-Seite nicht zu erkennen, ob die Anzeige bereits versendet wurde.

Das halte ich aus mehreren Gründen für unsinnig:
* Die Eingabe wird nachträglich verfälscht.
* Eventuell geht auch doppeltes Versenden? Mag ich lieber nicht testen.
* Bearbeiten von versendeten Anzeigen ist eine Zeitverschwendung.

How to reproduce:
* Meldung in einem neuen Tab öffnen, bearbeiten, absenden.
* die gleiche Meldung vom ersten Tab ohne Refresh nochmal öffnen. Bearbeiten, speichern, absenden(?)

Besser wäre eine der folgenden Optionen:
* Man erhält auf der Edit-Seite einen Warnhinweis, dass die Meldung bereits versandt wurde, kann aber noch bearbeiten.
* Die edit-Seite kann geladen werden, die Felder sind aber gesperrt.
* Die edit-Seite existiert nicht mehr und leitet zur Meldung weiter.
* Ein Update einer versendeten Meldung ist nicht mehr möglich (durch Check im Backend)

Beispiel-URLs:
* https://www.weg.li/notices/xxxx 
* https://www.weg.li/notices/xxxx/edit

**Comment by phoet** [comment]
Ja, das ist absicht könnte man sagen. Ein warnhinweis erscheint mir eher unnötig, weil man auf diese seite nicht von alleine kommt.

**Comment by RalphBike** [comment]
Sobald man mit mehreren Tabs arbeitet, kommt man leider regelmäßig da hin. Ein doppeltes Abschicken sollte IMHO vermieden werden.

**Comment by phoet** [comment]
Wenn man unterschiedliche Tabs offen lässt spielt es keine Rolle was man auf der Seite macht, dafür müsste es erstmal einen refresh des users geben. 

Ein doppeltes abschicken wäre ja nochmal etwas anders.

Beide Funktionen sind möglich, aber nur über entsprechende URLs zu erreichen. Damit können Nutzer bei Fehleingaben nochmals Dinge verändern und erneut abschicken. Das ist durchaus gewünscht, zb. wenn sich eine Bezirk-Zuordnung ändert.
