### ISSUE TITLE
Meldungen in Köln abschicken

### ISSUE THREAD

**Issue by jkfm** [weg-li/weg-li#38]
Hi,

welche Schritte wären nötig, um auch in Köln Verstöße zu melden? 

Das Kölner Ordnungsamt bearbeitet Verstöße per Email (an owi-anzeigen@koeln.de), weist aber daraufhin, dass man das "aktuelle Onlineformular" nutzen soll.

Das ist hier zu finden: https://formular-server.de/Koeln_FS/findform?shortname=32-F68_AnzVerkOrdWi&formtecid=3&areashortname=send_html

Kann die App sich da eventuell dranhängen? Ansonsten denke ich müsste es ausreichen, darauf zu achten, alle erforderlichen Angaben aus dem Formular zu befüllen.

**Comment by phoet** [comment]
genau dieser schritt war nötig 😸 

habe diese email hinterlegt und es geht in kürze live.

diese unterschiedlichen formulare, die von den städten angeboten werden möchte ich mit wegli ablösen. die städte können die informationen gerne in aufbereiteter maschinenlesbarer form von wegli bekommen.
