### ISSUE TITLE
Anzahl der Anzeigen im aktuellen Jahr

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#380]
Mir fehlt eine eine einfache Möglichkeit zu sehen, wieviele Anzeigen ich im laufenden Jahr schon erstellt und wieviele ich versendete habe. 

Aus meiner Sicht wäre der ideale Ort dafür die Header-Zeile der notices-Seite, statt der Anzeige aller Anzeigen. Diese Information kann entweder entfallen oder weniger prominent dargestellt werden.

**Comment by phoet** [comment]
Aus meiner Sicht wäre dafür die Statistik Seite besser geeignet https://www.weg.li/notices/stats

**Comment by RalphBike** [comment]
Wäre nicht mein präferierter Ort, aber fuck it, auch okay.

**Comment by phoet** [comment]
closed via 467634139d57efb8cd58a6f9bdb5d1a5e2b0e3e2
