### ISSUE TITLE
Leaderboard sollte den Zeitpunkt des Versendens verwenden, nicht den Tatzeitpunkt

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#381]
Das Leaderboard verwendet aktuell vermutlich den Tatzeitpunkt der Anzeigen. Dies sollte geändert werden auf das Einsende-Datum.

Warum? Weil das Einsenden deutlich mehr Arbeit ist als das Aufnehmen eines Fotos und damit stärker honoriert werden sollte.
Das würde ermöglichen, dass man nach einer aktiven Session schneller an die spitze kommt und mehr Dynamik in die Top10 kommt. Und damit mehr Motivation zur Bearbeitung, oder eben bessere Gamification.

Beispiel: ich habe heute abend ca. 93 Anzeigen versendet, komme aber nicht auf Top1 der Wochenliste, weil nur ein Drittel der Anzeigen aus der aktuellen Woche stammt.

**Comment by phoet** [comment]
Korrekt, der Tatzeitpunkt bestimmt das Leaderboard und alle anderen Statistiken bei weg.li das werden wir auch nicht ändern.
