### ISSUE TITLE
Zoomstufen bei Fotoansicht erhöhen um Details (Kennzeichen) besser zu erkennen

### ISSUE THREAD

**Issue by pixelbrackets** [weg-li/weg-li#383]
Als Anzeigenerstatter 
möchte ich mehrere Zoomstufen nutzen können,
um bei großformatigen Bildern das Kennzeichen besser erkennen zu können.

Szenario: Ich hab manchmal Fotos bei denen das Kennzeichen nur einen kleinen Teil des Fotos einnimmt. Da das Foto in ausreichend hoher Qualiät vorliegt, ist das aber eingentlich kein Problem. Ich klicke auf das Foto und hover dann mit der Maus über das Bild. Die Zoomstufe ist hier aber noch zu gering. Bzw. wird das Kennzeichen auf dem Display verpixelt dargestellt, obowhl es das ja eigentlöich nicht ist. Ich würde mir einen hörer Zoomstufe oder mehrere Stufen wünschen.

Workaround: Foto herunterladen, gespeichertes Foto öffnen, im Bildeditor zoomen, Kennzeichen merken und zurück zur Webapp.

**Comment by phoet** [comment]
Im Foto-Dialog wird das Foto in Originalauflösung angezeigt. Wenn das nicht ausreichend sein sollte bieten alle Browser eine integrierte Zoom Funktion. Ist ein Nummernschild unter der Lupe verpixelt, dann ist die Auslösung des Fotos zu gering.

**Comment by phoet** [comment]
Im allgemeinen gilt die Daumenregel: ist das Nummernschild im Foto-Dialog nicht zu erkennen, dann wird es auch von der Bußgeldstelle höchstwahrscheinlich nicht akzeptiert. In dem Fall das Foto lokal nachbearbeiten und hinzufügen.

**Comment by pixelbrackets** [comment]
Bei großformatigen Bildern (meint hohe Auflösung  4000x4000 Pixel) skalieren Browser leider schlecht.

Beispiel:

Lightbox Wegli:
![Bildschirmfoto von 2021-04-01 21-07-16 (Kopie)](https://user-images.githubusercontent.com/1592995/113343914-b8054b00-9330-11eb-904a-57bd4541f16c.png)

Hover-Zoom in Lightbox Wegli:
![Bildschirmfoto von 2021-04-01 21-07-22 (Kopie)](https://user-images.githubusercontent.com/1592995/113344001-d408ec80-9330-11eb-98d9-acf1c6b2326f.png)

Zoom in lokaler Bildanzeige:
![Bildschirmfoto von 2021-04-01 21-08-29 (Kopie)](https://user-images.githubusercontent.com/1592995/113344024-da976400-9330-11eb-832d-f76d8ba6c8cb.png)

**Comment by pixelbrackets** [comment]
Ach, mir fällt gerade auf, dass Wegli nicht »Originalauflösung« verwendet, sonder auf 1280x960 Pixel runterskaliert. War mir bisher nicht bewusst, ich dachte da gehen die Originalbilder raus. 
Dann ist die [Daumenregel](https://github.com/weg-li/weg-li/issues/383#issuecomment-811872313) auch vollkommen korrekt.

**Comment by phoet** [comment]
Ein Großteil der Ordnungsämter akzeptiert nur eine sehr begrenzte Menge an Daten, so 10MB sollten die Beweisfotos nicht übersteigen. Dementsprechend müssen die Bilder herunterskaliert werden.
