### ISSUE TITLE
Gespeichertes Kennzeichen geht beim Neuöffnen der Meldung verloren

### ISSUE THREAD

**Issue by pixelbrackets** [weg-li/weg-li#386]
*Was hab ich gemacht*

1. * Meldung angelegt, Kennzeichen wird nicht automatisch erkannt
2. * Kennzeichen erfassen & Farbe erfassen
3. * Speichern - Keine Anzeige absenden, sondern Tab schließen
4. * Meldung aus Übersicht aller Meldungen erneut öffnen
 
*Was habe ich erwartet?*

* Meldung wird im zuletzt gespeicherten Zustand angezeigt (mit Kennzeichen, Farbe etc)

*Was passiert stattdessen?*

* Meldung wird erneut mit leerem Feld fürs Kennzeichen angezeigt, es ist wieder notwendig das Kennzeichen zu erfassen

*Zusätzlicher Hinweis*

* In der Übersicht aller Meldungen (Punkt 4) ist das zuvor erfasste Kennzeichen noch vorhanden - erst wenn ich die Meldung zum Bearbeiten öffne gehen die Daten im Formular wieder verloren
* Ich kann den Fehler zuverlässig reproduzieren - bei Meldungen wo das Kennzeichen nicht beim ersten Mal schon erkannt wird

**Comment by phoet** [comment]
Ja, das ist mir auch schon aufgefallen. Werde ich die Tage mal schauen was da bei der letzten Änderung schief gelaufen ist.
