### ISSUE TITLE
Bei Auswahl eines Kennzeichenvorschlags die bekannten Features übernehmen

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#388]
Das neue Feature mit den wählbaren Kennzeichenvorschlägen ist sehr cool, danke!

Noch netter wäre es, wenn bei der Wahl eines Vorschlags auch Marke und Farbe übernommen würden, wenn diese bekannt sind.

Beispiel:

Automatisch erkennt wird: HH - AB 123, Audi, rot
Korrekt wäre: HH - XY 9876, VW, Braun. 

Wenn ich den Kennzeichenvorschlag per Klick auswähle, bleibt Audi, rot stehen. Besser wäre es, die bekannten Features des anderen Kennzeichens ins Formular zu übernehmen.

**Comment by phoet** [comment]
Die Auto-Suggest (ich liebe dieses Wortspiel) liefert die Daten anhand der persönlichen Historie. Diese Daten sind nicht mit den automatisch erkannten Daten verknüpft. Natürlich wäre es wünschenswert, dass diese Vorschläge auch gleich dort auftauchen, dafür muss aber die Visualisierung ggf noch einmal angepasst werden. Es wird dort in nächster Zeit ohnehin noch weitere Umbauten geben.
