### ISSUE TITLE
Upload von Fotos mit mehr als 5 MB?

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#393]
Moin, seit heute verweigert Weg.li den Upload von Fotos, die größer als 5,0 MB sind. Aus meinem Telefon fallen leider Fotos raus, die auch 6,x MB groß sind. 

Wird die Beschränkung dauerhaft sein? Wenn ja, gibt es eine Idee, wie ich als Anwender mir einen passenden Workflow bauen kann? Ich verwende mein Telefon auch für andere Sachen und will die Auflösung ungern dauerhaft reduzieren, noch jedes Mal umschalten.

**Comment by phoet** [comment]
Die Beschränkung wird dauerhaft sein, aber ggf nochmal angepasst. Das kann aber auch heißen, dass wir die größe noch weiter Reduzieren müssen.

Einige Benutzer haben eine zweite Foto-App mit der Beweisfotos aufgenommen werden.

**Comment by RalphBike** [comment]
Okay, hab ich befürchtet. Gibts Empfehlungen für die Alternativ-App, für Android?

**Comment by phoet** [comment]
Natenom hat allerlei weg.li Tips in seinem Wiki https://wiki.natenom.de/verkehr/projekte/weg-li

**Comment by RalphBike** [comment]
Cool, danke!
