### ISSUE TITLE
EXIF-Informationen werden nicht mehr ausgelesen

### ISSUE THREAD

**Issue by Nakaner** [weg-li/weg-li#395]
Bei zwei Anzeigen, die ich heute gestellt habe, ist mir aufgefallen, dass aus meinen Fotos keine EXIF-Informationen zu Zeit und Ort ausgelesen werden. Exiftool kann sie aber auslesen. Meine Bildvorverarbeitung-Software ist dieselbe.

**Comment by phoet** [comment]
Beispiele?

**Comment by Nakaner** [comment]
Eines der Beispiel-Bilder:

[IMG_20210412_094636](https://user-images.githubusercontent.com/3611273/114448207-8b282200-9bd3-11eb-8922-f6ecd632738c.jpg)

**Comment by phoet** [comment]
Klappt. Vielleicht gab es zwischendurch Probleme bei der Verarbeitung. Es sind nicht immer alle Dienste jederzeit verfügbar.
<img width="388" alt="Screenshot 2021-04-12 at 22 50 54" src="https://user-images.githubusercontent.com/48745/114460139-ac900a80-9be1-11eb-8134-66dc14b7d247.png">
