### ISSUE TITLE
LocationPicker sollte mit Position aus den Metadaten geladen werden.

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#399]
Moin, 

der Location Picker wird nicht mehr mit dem bekannten Wert aus den Metadaten geladen, sondern mit einem Standard-Wert. Das macht es aufwändiger und fehleranfälliger, die Location zu prüfen oder zu verändern, weil man erst den Ort finden und hinnavigieren muss. Das passiert auch in Anzeigen, bei denen das AutoSuggest für die Adresse funktioniert, daher gehe ich davon aus, dass Location-Infos vorhanden sind.

Gewünschtes Verhalten: DatePicker in der Karte mit bekannter GPS-Position laden, falls vorhanden.

**Comment by phoet** [comment]
Habe den Map-Picker heute verwendet und mir ist nichts aufgefallen. Schau ich mir bei gelegenheit noch mal an.

**Comment by phoet** [comment]
Konnte ich jetzt so nicht nachvollziehen, falls ein Vorschlag besteht werden die Koordinaten des Vorschlags verwendet, anderenfalls die Ortsdaten des Nutzers. Hast Du ein Beispiel?

**Comment by RalphBike** [comment]
Ist gestern wiederholt aufgetreten, aber heute kann ich es nicht reproduzieren. Ich schließe das Ticket.
