### ISSUE TITLE
Batchabarbeitung von Meldungen

### ISSUE THREAD

**Issue by dbermbach** [weg-li/weg-li#401]
Wenn man den Massenupload von Fotos nutzt, hat man danach manchmal recht viele Meldungen. Ich behelfe mich da aktuell mit einem Browserbookmark in der Symbolleiste auf die jeweils aktuelle Meldungsseite, aber was echt cool wäre, wenn man einfach alle Meldungen hintereinander abarbeiten könnte (am besten von alt nach neu). Der Flow wäre dann wie folgt:
1. irgendwie Batchbearbeitung starten
2. älteste Meldung wird angezeigt und von mir bearbeitet. Sobald ich auf "abschicken" geklickt habe, wechselt der View direkt zur Bearbeitung der zweitältesten Meldung (statt zur Meldungsübersicht auf Seite 1).

Das würde bei sehr vielen Meldungen mindestens 2-3 Klicks plus Scrollen pro Meldung vermeiden (und teilweise merke ich bei vielen Meldungen dann schon den Mausarm...). Das wäre großartig :).

**Comment by phoet** [comment]
Soetwas habe ich schon öfter ausprobiert und wieder verworfen. Die effizienteste Möglichkeit ist es offene Meldungen jeweils im neuen Tab zu öffnen.

**Comment by dbermbach** [comment]
Mach das mal mit 5-7 Seiten voller Meldungen ;-).
Weswegen hast du die Idee verworfen?

**Comment by phoet** [comment]
Ich hab zwar nur halb so viele Meldungen wie Du, aber dafür benutze ich die Funktionen aus "beruflichen Gründen" deutlich häufiger 😄 

Keine der Ideen war für die Usability eine Verbesserung zu "Dingen in Tabs öffnen".

**Comment by phoet** [comment]
Die letzte kleine Verbesserung in diese Richtung ist übrigens der click-bare "ungelesene Meldungen" Filter auf der Übersicht mit dem man unmittelbar die zu bearbeitenden Nachrichten angezeigt bekommt.
![Uploading Screenshot 2021-04-26 at 21.36.52.png…]()

**Comment by dbermbach** [comment]
Naja, das wären immer noch mindestens ein Klick pro Meldung (plus die Seitenwechsel). Könnte man nicht einfach (optional) einstellen, dass er nach dem Abschicken einer Meldung statt in die Übersicht zur nächsten Meldung (oder zumindest auf die gleiche Seite wie vorher) springt?
