### ISSUE TITLE
Anmeldung mit Email und Password

### ISSUE THREAD

**Issue by BoltCitizen** [weg-li/weg-li#402]
Anmeldung mit Bestätigungsmail ist sehr nervig und verhindert die Nutzung. Ganz "normal" per Email und Passwort fände ich viel besser. Am besten natürlich per App, aber da seid ihr ja schon drann :)

Danke für euer tolles Engagement!

**Comment by GoetzGoerisch** [comment]
Damit muss "Wegli" ein potentiell aufwändige Userverwaltung bauen und pflegen. Daher finde ich die Authentifizierung mit OAuth und trusted Providern viel besser.
Den Auth Token per Mail zu bekommen, der nach ein paar Wochen abläuft halte ich hier für eine guten Zwischenweg.

**Comment by GoetzGoerisch** [comment]
> Danke für euer tolles Engagement!

❤️

**Comment by BoltCitizen** [comment]
> Den Auth Token per Mail zu bekommen, der nach ein paar Wochen abläuft halte ich hier für eine guten Zwischenweg.
Das funktioniert für mich nicht. Da ich ein VPN benutze und im Browser viele Privatsspäreneinstellungen auf strikt sind, muss ich mich jedesmal neu mit der Email einloggen. Das dauert auch immer ein Weilchen bis die bei mir ankommt. Das ist sicherlich Benutzerabhängig, aber für mich ist das eine Barriere die mich von der Nutzung abhält.

**Comment by GoetzGoerisch** [comment]
Dann nutze doch GitHub als OAuth Dienst?

**Comment by phoet** [comment]
Aus Gründen der Datensicherheit werden wir keine Passwörter speichern.

**Comment by BoltCitizen** [comment]
> Dann nutze doch GitHub als OAuth Dienst?

Das funktioniert nicht. Wenn mich über GitHub einloggen will muss ich mich neu registrieren. Außerdem, aus Gründen der Datensicherheit, sind OAuth Dienste zu vermeiden.

**Comment by GoetzGoerisch** [comment]
> Außerdem, aus Gründen der Datensicherheit, sind OAuth Dienste zu vermeiden.

Vermute du meinst Datenschutz hier?

Ja, GitHub weiss dann, das Du Weg.Li nutzt.

**Comment by some-user123** [comment]
Ich finde die Anmeldung per Mail sehr nervig, weil ich auf dem Smartphone dann immer noch eine weitere App öffnen muss.

> Damit muss "Wegli" ein potentiell aufwändige Userverwaltung bauen und pflegen.

Ich verstehe diesen Punkt nicht. Weg.li hat doch jetzt auch schon eine Benutzerverwaltung. Ich habe ein Profil, habe meine Daten gespeichert etc. Das einzige was fehlt, wäre ein Passwort-Hash. Da das quasi jede App macht, muss man da auch nicht das Rad neu erfinden...

> Den Auth Token per Mail zu bekommen, der nach ein paar Wochen abläuft halte ich hier für eine guten Zwischenweg.

Meinst Du das als Vorschlag? Oder war das früher anders? Aktuell läuft der Token nach 15min ab. Und auch die Session im Browser hält deutlich kürzer als alle anderen Dienste, die ich kenne. (Gleichzeitig sehe ich deutlich geringeres Missbrauchspotential als bei anderen Accounts.)

> Dann nutze doch GitHub als OAuth Dienst?

Meine E-Mail-Adresse, die ich für private Projekte auf Github verwende, ist nicht die Adresse, die ich Strafverfolgungsbehörden von mir mitteilen möchte. Mit der Verwendung mehrerer Github-Konten habe ich leider schon schlechte Erfahrungen gemacht. 

> Aus Gründen der Datensicherheit werden wir keine Passwörter speichern.

Kannst Du erklären, wie Du das meinst?
Natürlich sollte man kein Passwort speichern, sondern einen gesalzenen Hash.
Oder eben neuere Methoden wie Passkeys einsetzen.

**Comment by phoet** [comment]
Der remember-me token ist einen Monat gültig und wenn in dieser Zeit eine weitere Session läuft, dann gibt es gar keinen Grund sich erneut einloggen zu müssen.
