### ISSUE TITLE
Private GPS-Location entfernen

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#408]
Meine private GPS-Location taucht als Default-Position in Anzeigen auf, bei denen keine GPS-Position gefunden wurde.
Wenn ich also bei einem Foto NICHT von Hand die Location via Picker ändere (z.B. wegen Texteingabe der Adresse) häufen sich an meinem Wohnort (?) die Pins in der Karte. Das ist alles ziemlich unschön, weil ich meinen Wohnort ungerne publizieren möchte. Wer weiß, wen das interessieren könnte. 

Schöner wäre eine Default-Position, die sich an kurz zuvor und kurz danach aufgenommenen Fotos orientiert.
Oder eine Default-Position für den Ort, wie meinetwegen "Hamburg Rathausplatz".

Zusatzfrage: woher kommt diese Position eigentlich? Kann die weg?

**Comment by phoet** [comment]
Sind keine GPS-Tags im Foto enthalten, dann werden in der Anzeige auch keine Geo-Koordinaten übernommen.

Wird der Map-Picker verwendet, dann werden die Daten aus der Karte übernommen. Der Map-Picker steht standardmäßig auf der Adresse des Nutzerprofils.

Wird kein Map-Picker verwendet, dann werden die Daten aus der eingetragenen Adresse übernommen wenn sie nicht schon anderweitig gesetzt wurden.
