### ISSUE TITLE
Kennzeichen-Eingabe sollte Caps-Only sein

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#411]
Braucht wirklich jemand Kleinbuchstaben in der Kennzeichen-Eingabe? Gibt es Kleinbuchstaben auf Kennzeichen? 

Wenn nein, fände ich Caps-Only in der Eingabe deutlicher besser.

**Comment by phoet** [comment]
Bei normalen deutschen Kennzeichen eigentlich nicht, aber wir enforcen auch kein spezielles Format, wie es eigentlich notwendig wäre "HH-PS 123". Somit können auch Mofas oder sonstige KFZ über das selbe Formular angezeigt werden.

**Comment by RalphBike** [comment]
Dieses Verhalten finde ich soweit gut, bis eben auf die für mich Lowercase-Zeichen, die man per default mit jeder Mobile-Tastatur eingibt. Ich habe noch nie Kleinbuchstaben auf einem Kennzeichen gesehen.

**Comment by phoet** [comment]
https://www.the-art-of-web.com/html/input-field-uppercase/
