### ISSUE TITLE
Vorwochen-Lead und Vormonats-Lead noch etwas anzeigen

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#413]
Die Zeitraum-Leaderboards für Woche und Monat sind eigentlich nie vollständig zu sehen. Entweder der Monat läuft, die Zahlen sind also unvollständig, oder er ist vorbei und die Zahlen sind weg. Schöner wäre, den Endstand noch etwas bewundern zu können.

Ich schlage vor:

- Vorwochenlead bis Mittwoch anzeigen.
- Vormonatslead bis zum zehnten des Monats anzeigen.

**Comment by phoet** [comment]
Die Vergänglichkeit dieser Daten ist Absicht, wir möchten möglichst wenige Informationen über das Nutzungsverhalten unsere Nutzer publizieren. Die Gamification ist bereits jetzt in einem grenzwertigen Bereich und wir werden es nicht noch weiter steigern.
