### ISSUE TITLE
Im Leaderboard sollte auch der eigene Wert und die resultierende Position sichtbar sein

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#415]
...dann könnte man sehen, wie wo man selbst im Jahresranking steht und wie weit der Weg zu Platz 1 noch ist. Oder gewesen wäre.

Für Wochen-Lead (sofern eigener Wert > 0)
Für Monatslead (sofern eigener Wert > 0)
Für alle Jahres-Leads (sofern eigener Wert > 0)
Für alle Alltime-Lead (sofern eigener Wert > 0)

**Comment by phoet** [comment]
Auf deiner Profil-Seite werden die individuellen Rankings bereits angezeigt.
