### ISSUE TITLE
Feature Request: Anonymisierung von Bildern (Gesichter, Kennzeichen)

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#416]
Okay, das ist aufwändig und schwer zu realisieren. Mach das Ticket gerne zu, wenn es Quatsch ist. 

ABER: Wegli kann auch andere Dinge, die wirklich cooler Scheiß sind, wie Kennzeichen und anderes Zeug erkennen. 

Daher: Ich hätte gerne die Möglichkeit, Gesichter und andere (!) Kennzeichen automatisch oder nach Userinput effizient auszublenden (Blur oder Schwärzen). 

Hintergrund: In Hamburg werden OWIs nur noch bearbeitet, wenn sie keine "Daten Dritter", wie andere Kennzeichen oder Gesichter enthalten. Siehe https://fragdenstaat.de/dokumente/8533-microsoft-word-dok1docx/

**Comment by phoet** [comment]
Es gibt grundsätzlich Probleme damit Fotos hochzuladen, auf denen Passanten oder die Kennzeichen unbeteiligter zu sehen sind. Wir empfehlen deshalb Beweisfotos so zu machen, dass dies möglichst vermieden wird. Sollte das doch mal passieren haben heutige Smartphones Software zur Bildmanipulation vorinstalliert, die weit besser funktioniert als alles was bei uns eingebaut werden würde.

Duplikat https://github.com/weg-li/weg-li/issues/416
