### ISSUE TITLE
Ranking in der Userstatistik ist nicht nachvollziehbar

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#418]
Hi, wie kommt diese User-Statistik unter https://www.weg.li/user/ zustande?
Ich kann die Zahlen nicht nachvollziehen.

**"Rang 3 in der Tageswertung: 14 vs 37 Anzeigen"**
* Ich habe heute noch gar nichts gemeldet. => 0/x Anzeigen.  Platzierung unbekannt. Letzter Platz mit vielen anderen heute inaktiven?

**"Rang 2 in der Wochenwertung: 110 vs 154 Anzeigen"**
* Laut Leaderboard: Platz 1 mit 96/96 gemeldeten Anzeigen.

**"Rang 2 in der Monatswertung: 197 vs 310 Anzeigen"**
* Laut Leaderboard: Platz 2 mit 183/205 gemeldeten Anzeigen.

**"Rang 5 in der Jahreswertung: 1.364 vs 2.294 Anzeigen"**
* Laut Leaderboard: Platz 4 mit 1344/2291 gemeldete Anzeigen.
* Laut https://www.weg.li/notices/stats 1340 gemeldete Anzeigen.

**"Rang 7 in der Allzeitwertung: 2.054 vs 5.110 Anzeigen"**
* Laut /notices/stats:  2034 gemeldete Anzeigen von (laut Leaderboard) 5103 Anzeigen. Platzierung unbekannt.

**Comment by pixelbrackets** [comment]
Der Fehler in der Tagswertung ist mir auch schon mehrmals aufgefallen.

Heute: „23 vs 37 Anzeigen“ = Rang 3. Wenn ich 23 von gesamt 37 hab, sind nur noch 14 übrig von anderen. Diese können dann ja gar nicht Rang 1 und 2 einnehmen.

![Bildschirmfoto von 2021-11-24 12-03-21](https://user-images.githubusercontent.com/1592995/143226799-623dc018-b7fd-4e54-a4c6-8a3b4277750c.png)

**Comment by phoet** [comment]
Da steht "versus", nicht "von". Du hast 23, versus 37 von Rang 1.

**Comment by phoet** [comment]
@RalphBike ja, an dieser stelle werden die erstellten Meldungen genutzt, was nicht einheitlich ist. Das sollte ich einmal anpassen.
