### ISSUE TITLE
Editierbare Mailvorschau

### ISSUE THREAD

**Issue by Maddosaurus** [weg-li/weg-li#42]
Die Mail als Preview anzuzeigen, die aus den Bausteinen generiert wird, finde ich sehr gut.  
Allerdings fände ich es super, wenn man den vorgeschlagenen Text an dieser Stelle noch mal editieren könnte.  

Warum?  
Ich hatte das ein oder andere Mal das Problem, dass der Text nicht 100% passt oder eine Kleinigkeit geändert werden müsste, damit es sich "runder" liest. Beispiel: Wenn man einen falsch geparkten Anhänger melden möchte, so liest sich die entstandene Mail doch etwas holprig :)  
Nicht zuletzt ist es aus UX-Sicht für einen User frustrierend, einen potentiellen "Fehler" in der Mail entdeckt zu haben, die in Namen des Users verschickt wird, der nicht behoben werden kann.

**Comment by phoet** [comment]
danke für das feedback. ich kann die idee nachvollziehen, sehe das aber eher als ausnahme denn als regel.

natürlich soll der text in der email möglichst rund und fehlerfrei sein, wenn man seinen namen daruntersetzt.

noch wichtiger finde ich allerdings die vollständigkeit hinsichtlich der enthaltenen informationen. wenn der text editierbar ist hätte ich die befürchtung, dass dann benutzer womöglich fehler machen. 

eine alternative variante wäre zu probieren ob man die email auch über einen button in gmail öffnen kann, ich denke aber, dass es mit den fotos schwierig sein wird.
