### ISSUE TITLE
Massen-Upload: Löschen eines Fotos führt zu Reset der Foto-Auswahl

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#423]
Im Massen-Upload führt das Löschen eines Fotos zum Reset der Foto-Auswahl für die neu anzulegende Meldung.

How to reproduce:
1. Upload von N Fotos (nennen wir sie A-Z). Foto A ist automatisch ausgewählt.
2. Unselect von A, Select von z.b. drei Fotos (B, C, D)
3. Löschen eines Fotos (z.b. C)
4. Das Bild wird gelöscht, die Auswahl zurückgesetzt. Es ist wieder A ausgewählt.

Expected Behaviour:
B und D bleiben nach dem Löschen ausgewählt, der User wird im Workflow nicht unterbrochen.

**Comment by phoet** [comment]
Die Auswahl wird nicht zwischengespeichert und bei einem Seiten-Reload entsprechend verworfen. Das Zwischenspeichern ist auch in den allermeisten Fällen nicht notwendig.
