### ISSUE TITLE
Foto ersetzen wäre sehr hilfreich

### ISSUE THREAD

**Issue by chrissikay** [weg-li/weg-li#427]
Beim Bearbeiten der Meldungen nach einem Massen-Upload möchte ich immer wieder mal Teile eines Fotos entfernen (z.B. ungewollte Pasanten). Dazu ist es nötig das Foto zu aktualisieren. Bisher muss ich ein neues hinzufügen und das alte löschen. Eine Funktion "Foto aktualisieren" wäre sehr hilfreich. Das könnte so aussehen: 
![grafik](https://user-images.githubusercontent.com/24270714/120147798-85b88280-c1e7-11eb-9ce1-23bf487fdb64.png)
Das verwendete Icon ist `glyphicon glyphicon-refresh`.

**Comment by phoet** [comment]
das könnte man sich mal anschauen.

**Comment by RalphBike** [comment]
Fände ich auch gut!

**Comment by phoet** [comment]
Zwei schritte erscheinen hier gut genug.
