### ISSUE TITLE
Ladebalken beim Hochladen von Fotos aus der Detailansicht fehlt

### ISSUE THREAD

**Issue by chrissikay** [weg-li/weg-li#428]
Wenn ich ein Foto in einer Meldung ergänzen möchte, wird der Ladebalken beim Hochladen nicht angezeigt. Man kann nur hoffen, dass der Upload verarbeitet wird. Nach etwas Wartezeit (abgeschlossener Upload) schließt sich dann das Fenster automatisch, alternativ wird eine Fehlermeldung sofort angezeigt.

Bitte den Ladebalken, oder eine andere Rückmeldung für den laufenden Upload ergänzen.

**Comment by phoet** [comment]
Guter Hinweis.
