### ISSUE TITLE
Massen-Upload Fotos gruppieren

### ISSUE THREAD

**Issue by chrissikay** [weg-li/weg-li#429]
Ist es möglich vor dem Erstellen der Meldungen die Fotos auf Kennzeichen hin zu analysieren und gleiche Kennzeichen zu einem Meldevorschlag zu gruppieren? 
Alternativ evtl. nach der Position gruppieren. Das könnte aber bei einer Kreuzung mit 8 Kreuzungsparkern ungünstig sein...

Gelegentlich kommen mir Falschparker mehrfach am Tag an der gleichen Stelle vor die Linse, ohne dass ich das mitbekomme. Insofern wäre das Erweitern der Parkdauer auf meist >3 Std. schön dokumentiert.

**Comment by phoet** [comment]
Siehe auch https://github.com/weg-li/weg-li/issues/282

Dafür müsste der komplette Analyse-Prozess geändert werden. Das halte ich eher für unwahrscheinlich.
