### ISSUE TITLE
Warnmeldung um eine Prüfung der Adresse erweitern

### ISSUE THREAD

**Issue by chrissikay** [weg-li/weg-li#430]
Bitte die Warnung `Achtung, du hast schon eine Meldung für dieses Datum mit identischem Nummernschild, falls es OK ist einfach fortfahren` um eine Prüfung der Adresse erweitern. Es kommt besonders bei Zustellfahrzeugen zu Mehrfachtreffern am Tag.

Nicht ganz ernst gemeint:
Lustig wäre ein Statistikfilter "Zusteller des Tages" mit den meisten Meldungen am Tag

**Comment by phoet** [comment]
Diese Warnmeldung soll Doppel-Meldungen verhindern. Es gibt zu viele Edge-Cases um eine allgemein-gültige Lösung dafür zu bauen, deshalb leben wir hier mit einer 80/20 lösung
