### ISSUE TITLE
Routing nach dem Löschen und Absenden einer Meldung

### ISSUE THREAD

**Issue by chrissikay** [weg-li/weg-li#431]
Aktuell wird fix nach `/notices` geroutet. Schöner wäre aber eine Route auf die vorherige URL, um z.B. auf `/notices?page=3` zurück zu kommen, wo man in diesem Moment war.

**Comment by phoet** [comment]
ja das macht sinn, das könnte man einfach ändern

**Comment by spiii** [comment]
Das Gleiche würde Sinn machen wenn man den Filter gesetzt hat #463 
es wäre wirklich super hilfreich.

**Comment by spiii** [comment]
> ja das macht sinn, das könnte man einfach ändern

wäre wirklich toll. Danke im Voraus

**Comment by spiii** [comment]
Hat sich hier was getan?

**Comment by phoet** [comment]
Nein, es hat sich nichts getan.

**Comment by phoet** [comment]
auf eine bestimmt page zu springen ist nicht sinnvoll, da sich das in der zwischenzeit geändert haben kann, aber dieses feature ist wahrscheinlich durch 095d1045bb02d925fb8aee55edec37b0f75483a6 gelöst

**Comment by spiii** [comment]
Danke danke danke das wird die Erledigung der Anzeigen mindestens 3x schneller machen und 1000 mal bequemer.

Danke danke danke
