### ISSUE TITLE
Bug beim Löschen von Bildern

### ISSUE THREAD

**Issue by chrissikay** [weg-li/weg-li#432]
Wenn in dem Meldeformular Bilder gelöscht werden, wird das Formular zurückgesetzt. Das kann sehr ärgerlich sein, wenn während des Bearbeitungsvorganges die Bilderzusammenstellung nochmal geändert wird.

**Comment by phoet** [comment]
Ja, das ist leider derzeit ein Workaround für iOS Geräte, vielleicht ist der inzwischen überflüssig.
