### ISSUE TITLE
Mobile Friendly Design

### ISSUE THREAD

**Issue by ChawiBiker** [weg-li/weg-li#433]
Problem:
When used on a mobile phone, the list is not usable because you have to scroll horizontally.

Solution:
When on a mobile screen, don’t show the column Kennzeichen and erstellt.
Additionally wrap the text of Tatzeit on two rows.

This would avoid horizontal scrolling while on a mobile phone.

**Comment by phoet** [comment]
I'm using it on a mobile phone, so would not say it's not usable. There is no proper solution to the space constraint, because it can be used in various screen sizes. the horizontal scolling is a reasonable workaround here.

**Comment by ChawiBiker** [comment]
Could we have a configuration of columns? This would also help :)
