### ISSUE TITLE
Popups / Modale Dialoge (?) sollten innerhalb des Bildschirms angezeigt werden

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#434]
Hi, ein paar der Popups sind bei mir teilweise außerhalb des Bildschirms. Dabei sind immer die unteren Buttons außerhalb des Bildes, was bedeutet, dass man Scrollen muss. Das stört besonders bei Dialogen mit Scrollfunktion innerhalb des Dialoges, wie dem Date Picker.

Expected Behaviour: die Dialoge passen sich an die Bildschirmgröße an. Kein Scrollen mehr nötig.

Tritt auf bei den Dialogen:
- Fotoansicht (in Meldung und Massen-Upload)
- Date Picker

Tritt auf mit dieser Hardware:
- Aktuelles  Android-Telefon (2960×1440 px), mit Chrome
- auf meinem (zugegeben) nicht ganz aktuellen Linux-Notebook mit 1366x768 px, mit den Browsern Chrome und Firefox.

**Comment by carstenhag** [comment]
Ist mir heute auch aufgefallen. Ich hatte das Problem, dass ich den Löschen-Button nicht gefunden hatte. Benutze ein 1080p-Screen:

![Bildschirmfoto 2021-09-27 um 14 54 16](https://user-images.githubusercontent.com/3776997/134915159-9afa187b-f73d-46f7-b41c-0044f2bd2692.png)
