### ISSUE TITLE
Zeichen aus Verstößen als Bild anzeigen

### ISSUE THREAD

**Issue by naderman** [weg-li/weg-li#437]
Für neue Nutzer kann die Liste der möglichen Verstöße erstmal sehr unübersichtlich sein und man ist sich leicht mal nicht sicher ob man nun die richtige Option gewählt hat. Zum prüfen hat es mir geholfen das jeweilige zeichen dann einmal im Web zu suchen und zu überprüfen ob die Bilder dem Verkehrszeichen entsprechen, dass ich erwartet habe. Es wäre super, wenn in der Benutzeroberfläche auf weg.li ein Bild des entsprechenden Verkehrszeichens angezeigt wird, so denn beim jeweiligen Verstoß eins oder mehrere hinterlegt sind.

**Comment by phoet** [comment]
Hallo Nils, danke für dein Feedback! Leider sind die Regeln vielfältig, mehrdeutig, regional und Interpretationssache. Natürlich möchten wir gerne mehr Informationen anbieten, aber unsere Resourcen sind beschränkt. Wenn Du uns gerne dabei unterstützen willst, dann bist du gerne herzlich willkommen. Es gibt zwar ein paar Bemühungen aus der Community, aber leider ist bis dato nur wenig vorzeigbares dabei entstanen.

**Comment by Morl99** [comment]
Vielleicht reicht es ja für den Anfang, für jeden Tatbestand optional ein Bild hinterlegbar zu machen? Mit ein wenig Fleißarbeit kommt man doch bestimmt recht schnell zu einer guten Abdeckung.

In der Webanwendung kann das Bild dann nach Auswahl eines Tatbestands zur Kontrolle angezeigt werden. 

Wäre das für dich @phoet eine gute Lösung? Kann mir vorstellen hier mitzuhelfen.

Vermutlich führt das zu duplikaten, da viele Tatbestände ja das gleiche Zeichen referenzieren. Man könnte das entkoppeln, wenn man die Liste der Tatbestände um das darin enthaltene Zeichen ergänzt (ist das 0,1..n Beziehung, oder gibt es Tatbestände die mehr als ein Zeichen referenzieren?). Dann braucht man natürlich noch eine Liste aller Zeichen und der dazugehörigen Bilder.

**Comment by phoet** [comment]
@Morl99 du kannst gerne bei soetwas helfen indem du die Vorarbeit der Bildersuche übernimmst. Dafür würde es schon reichen einen Dropbox-Ordner mit Bildern mit entsprechender Benamsung oder ähnlichem zu hinterlegen. Da könnte man auch mit einer handvoll anfangen und über die Qualität und Aufmachung der Bilder diskutieren.

**Comment by Morl99** [comment]
Die Bilder hab ich oben schon verlinkt, die sind fertig.

Hilft es einen kleinen Webserver bereit zu stellen der das entsprechende Bild ausliefert, wenn man /311.1 aufruft (als Beispiel)

**Comment by phoet** [comment]
Ah, das hatte ich überfliegen der E-Mail übersehen. Habe mir die mal angeschaut und ein bißchen geweint, weil die als JPG bereitgestellt sind und nicht als PNG oder Vector... Wenigstens nicht als Word-Datei oder so 😸 

Hilfreicher wäre es die Dateien mit in der Anwendung zu haben, das wäre als Vector sicherlich unproblematisch, da die Datein dann höchstens ein paar byte haben drüften...

**Comment by Morl99** [comment]
Finde dafür aber keine SVG Quelle. Wir brauchen die Bilder ja aber letztlich auch nicht in einer großen Auflösung. Was denkst du ist die maximale Größe der längsten Seite der Bilder in der wir sie brauchen? Dann könnte ich sie in PNG umwandeln und entsprechend resizen, natürlich nur, wenn das so in Frage kommt.

**Comment by phoet** [comment]
Vielleicht gibt es irgendeinen service den man dafür missbrauchen kann. Mit portrace und imagemagick bekommt man immerhin schwarz-weiß svgs hin

![101-10](https://user-images.githubusercontent.com/48745/196270347-f4b32fbb-b21a-4258-ba5b-04534ca3699a.svg)

**Comment by Morl99** [comment]
Das klingt messy, die Umwandlung von Raster in Vektor kann kaum fehlerfrei gelingen, zumindest nicht, wenn man hinterher wirklich was daraus gewinnen will.

Ich wollte ohnehin mal das eleventy image Modul ausprobieren und hab daraus eine Website gebaut. Musst du auch nicht einbauen, aber ich fand es so oder so eine gute Idee, dass es im Internet irgendwo einen Webserver gibt, der einzelne Verkehrszeichen liefert ;)

https://verkehrszeichen.netlify.app/

**Comment by Morl99** [comment]
Also um das Thema nochmal aufzugreifen, es gibt nun zwei greifbare Möglichkeiten:

1. Den service nutzen um die Bilder zur Laufzeit einzubinden
2. Ein Export aller Bilder nehmen und hier ins Projekt aufnehmen. Da eleventy die Bilder ja zur Build Time runter rechnet, kann ich ein zip mit Bildern in beliebiger Auflösung erstellen.

Kommen eine (oder beide) Möglichkeiten in Frage, mal ganz unabhängig davon, ob du das selbst einbaust, oder wir das Issue dann auf help-wanted stellen?

**Comment by phoet** [comment]
@Nakaner danke für den hinweis. es ist sicherlich hilfreich solche beispiele aufzubereiten. wir haben nicht die bandbreite dafür, so etwas zu pflegen. wenn jemand anfängt ein wiki oder dergleichen dafür zu starten, dann können wir das einfach verlinken.

**Comment by Morl99** [comment]
Wir reden hier nun aber plötzlich über unterschiedliche Dinge.

Die Intention des Issues war es, Verkehrszeichen, die in Verstößen explizit referenziert werden, anzuzeigen. Das erscheint mir _immer_ sinnvoll zu sein. Darüber hinaus kann es natürlich auch hilfreich sein, Illustrationen für Verstöße anzuzeigen, die über das bloße Verkehrszeichen hinaus gehen. Das wäre für mich dann aber ein anderes Issue, welches man separat angehen könnte.

**Comment by phoet** [comment]
![Bildschirmfoto 2024-11-23 um 16 37 17](https://github.com/user-attachments/assets/187667b2-020c-4aee-8394-426c6f5eb00f)
