### ISSUE TITLE
Abgeschickte Meldungen sollten nicht löschbar sein.

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#441]
Ich habe leider 9 abgeschickte Meldungen gelöscht, auch wegen #169.

Ist es wirklich sinnvoll, dass abgeschickte Meldungen gelöscht werden können? So geht IMHO die Verbindung zum Amt für Rückfragen, etc. kaputt.

Und gezählt werden sie natürlich auch nicht mehr. *heul*

**Comment by phoet** [comment]
Natürlich muss es möglich sein Meldungen zu löschen.
