### ISSUE TITLE
Anpassbare Paginierung / Notices per Page

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#442]
Da ich gerade 120 Anzeigen von Hand löschen musste, schlage ich vor, die Notices per Page durch den User einstellbar zu machen. Z.b. 15, 50, 100, 250

**Comment by phoet** [comment]
Die Anzahl der Meldungen pro Seite hatte einen Performance-Constraint. Da wir inzwischen keine Bilder mehr on the fly umrechnen müsste dieser Constraint eigentlich wegfallen können. Dementsprechend könnte man auf jeden fall etwas großzügiger beim Paginieren sein.
