### ISSUE TITLE
Massen-Upload: Anlegen von Single-Photo-Notices mit einem Klick, ohne Reload.

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#443]
Können Anzeigen auf der Seite Bulk-Upload-Edit asynchron (?) oder im Hintergrund anlegt werden? D.h. ohne Reload der Seite und Unterbrechung des Users? Wenn ja, schlage ich vor, pro Foto einen Dritten Button einführen, der aus diesem Foto direkt eine Anzeige mit diesem Bild macht, ohne weitere Interaktion.

Warum? 

Ich habe oft Mischungen aus Ein-Foto-Pro-Anzeige (1x) und Mehrere-Fotos-Pro-Anzeige (Nx). Wobei wichtig ist, im Fall Nx die Fotos nicht versehentlich auf mehrere Anzeigen zu verteilen, die Fotos eines Falls sind aber oft nicht zusammen in der Liste platziert, was viel Suchen bedeutet. Es wäre daher sehr hilfreich, die 1x-Fälle schnell und unkompliziert weg-createn zu können. Dann blieben die wenigen Nx-Fälle übrig und die könnte man schnell manuell zuordnen.

Ja, ich kenne den Button "Pro Beweisfoto eine Meldung", der hilft aber nur, wenn man die Nx-Fälle schon zusammengesucht hat.

**Comment by phoet** [comment]
Grundsätzlich wäre das möglich, wir werden jedoch in absehbarer Zeit keine Änderungen an der Bulk-Edit funktion durchführen, da sie unserer Meinung nach "good enough" ist.
