### ISSUE TITLE
Heute keine Meldungen per CC erhalten

### ISSUE THREAD

**Issue by hzulla** [weg-li/weg-li#45]
Hallo,

meine heutigen Meldungen kamen nicht mehr - wie sonst - als Mail per CC bei mir an.

**Comment by hzulla** [comment]
Aha, landen im Spam-Filter.

```
X-Spam-Flag: YES
X-Spam-Score: 5.006
X-Spam-Level: *****
X-Spam-Status: Yes, score=5.006 required=4 tests=[BAYES_00=-1.9,	DKIM_SIGNED=0.1, DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1,	FROM_LOCAL_DIGITS=0.001, FROM_LOCAL_HEX=0.006, FROM_NOT_REPLYTO=2,	FROM_NOT_REPLYTO_SAME_DOMAIN=5, RCVD_IN_DNSWL_NONE=-0.0001,	SPF_PASS=-0.001] autolearn=no autolearn_force=no
```

**Comment by phoet** [comment]
hm, kann ich nicht beurteilen ob das jetzt besser oder schlechter ist als vorher... https://github.com/weg-li/weg-li/issues/25

**Comment by hzulla** [comment]
Vielleicht wäre es notwendig, dass Du bei den jeweiligen Behörden mal nachfragst, ob die Mail auch ankommt und nicht weggefiltert wird...

**Comment by phoet** [comment]
die behörden geben ja keinerlei auskunft... und schon garnicht wenn man im namen von jemandem nachfragt. ich könnte also lediglich in hamburg nachfragen, ob meine emails angekommen sind. 🤷‍♂ 

einige, wie z.b. die hamburger schickt (manchmal) eingangsbestätigungen. die bekomme ich regelmäßig zurück, obwohl als reply-to die user-email eingetragen ist?!

nach meinem urlaub spreche ich mit den leuten von wegeheld, vielleicht können die mir jemanden bei der behörde vermitteln, mit dem man sich darüber mal austauschen kann.

**Comment by phoet** [comment]
ich glaube übrigens, dass weder die alte, noch die jetzige lösung wirklich spam-technisch ein problem darstellt. die filter schlagen hauptsächlich deshalb an, weil man sich selber mails schickt die nicht vom eigenen server kommen.

**Comment by phoet** [comment]
<img width="432" alt="Screen Shot 2019-08-27 at 15 57 26" src="https://user-images.githubusercontent.com/48745/63777440-65a5b200-c8e3-11e9-9409-f97d9b2a3745.png">
