### ISSUE TITLE
Emailadresse Bußgeldstelle Hamburg

### ISSUE THREAD

**Issue by atecon** [weg-li/weg-li#451]
Hallo,

ich habe gerade festgestellt, dass nach Versand der Anzeige per Email, die Email-Adresse für Hamburg mit **anzeigenbussgeldstelle@owi-verkehr.hamburg.de** angegeben wird.

Die tatsächliche Email-Adresse lautet aber **bussgeldstelle@owi-verkehr.hamburg.de**. Siehe hier: https://www.hamburg.de/bussgeldstelle/109688/bussgeldstelle/

Danke.

**Comment by Lergin** [comment]
Die Adresse `anzeigenbussgeldstelle@owi-verkehr.hamburg.de` ist zwar eine Email-Adresse der Bußgeldstelle. Laut der Automatischen Antwort Email (die letzte die ich erhalten hatte ist vom 26.07.2021) soll aber für Anzeigen explizit `anzeigenbussgeldstelle@owi-verkehr.hamburg.de` verwendet werden, vermutlich werden dadurch die Emails direkt entsprechend zugeordnet. Daher sollte die verwendete Adresse weiterhin stimmen :)

**Comment by phoet** [comment]
Die Adresse ist mit der Hamburger Bußgeldstelle abgestimmt.
