### ISSUE TITLE
Sign in with Apple

### ISSUE THREAD

**Issue by d12bb** [weg-li/weg-li#455]
Neben Twitter, GitHub etc sollte auch [Sign In with Apple](https://developer.apple.com/sign-in-with-apple/) unterstützt werden, da es für Nutzer dieses Ökosystems die mit Abstand beste Methode ist.

**Comment by phoet** [comment]
da sollte problemlos machbar sein, omniauth hat dafür ein plugin https://github.com/nhosoya/omniauth-apple

**Comment by phoet** [comment]
welp, sollte einfach machbar sein, allerdings braucht man dafür einen apple developers bezahl account. @mnin hast du lust eine service-id dafür zu konfigurieren?

**Comment by mnin** [comment]
@phoet ja, mache ich am Wochenende.

**Comment by levino** [comment]
Ping.

**Comment by phoet** [comment]
Der Signin it Apple funktioniert nicht mit omniauth, da Apple als einziger OAuth-Anbieter einen Weg wählt, der nicht unterstützt ist.

**Comment by phoet** [comment]
Siehe auch folgende Diskussion https://github.com/nhosoya/omniauth-apple/pull/107

**Comment by levino** [comment]
So "closing as wontfix"?

**Comment by phoet** [comment]
It's still in development, but blocked. Just pointing to the issue at hand here

**Comment by bvogel** [comment]
It would help if some more would leave comments on the [now closed PR](https://github.com/nhosoya/omniauth-apple/pull/107) as the owner of the repo isn't responsive al all. If someone has a better alternative to the solution I proposed I'm also keen to know.
