### ISSUE TITLE
Fahrzeugmarke MAN nicht in Liste der Hersteller

### ISSUE THREAD

**Issue by udkde** [weg-li/weg-li#46]
Wollte heute einen LKW anzeigen (https://www.weg-li.de/p/charge/50505d89500026b60d96d32c991d89e2) und konnte zwar die Meldung ohne das ausgefüllte Feld der Marke absenden. Eine Auswahl für den Hersteller MAN wäre dennoch keine schlechte Sache.

**Comment by phoet** [comment]
yo, da sind gerade nur automarken hinterlegt, ich werde noch listen für motorräder, LKW etc hinterlegen.

**Comment by phoet** [comment]
ich habe gerade eine rudimentäre liste an lastwagenmarken hinterlegt 81fee4191531d8aec93df095830102f817822ceb
