### ISSUE TITLE
Routing nach dem Löschen und Absenden einer Meldung FILTER

### ISSUE THREAD

**Issue by spiii** [weg-li/weg-li#463]
Ich arbeite meine Meldungen so ab, dass ich mir die offene aussuche und einer nach der andren bearbeite.
Derzeit muss ich die Filterung nach jeder Meldung neu setzen :(

Könnte man das Routing dahingehend so ändern, dass nach dem Absenden einer Meldung man zurück an die Adresse kommt von der man die Meldung hat. (z.B https://www.weg.li/notices?filter%5Bstatus%5D=open  Übersicht mit Filter für offene Meldungen)

Die Filterfunktion ist sonst wenig hilfreich, da man sie jedes mal aktivieren muss.

**Comment by phoet** [comment]
closed by 095d1045bb02d925fb8aee55edec37b0f75483a6
