### ISSUE TITLE
Ortsbezeichnung sollte nur Straße, Hausnummer, Stadt sein

### ISSUE THREAD

**Issue by udkde** [weg-li/weg-li#47]
Bei der Erkennung der Örtlichkeit füllt sich das Feld mit Bezeichnungen wie 
"Anadolu Market, Bismarckstraße, 64293 Darmstadt, Deutschland" (https://www.weg-li.de/notices/9ae71055cb107f2b37dfad42185a686c), also einer Ortsbezeichnung, die sich auf Läden, POI etc. bezieht. Die Behörden arbeiten eher mit den amtlichen Hausnummern. Vor allem, wenn es auf einer sehr langen Straße zwei Läden gleichen Namens gibt (Modeketten, Tankstellen etc) wäre die Angabe zu ungenau und ggf. ein Grund für einen Einspruch durch die Betroffenen.

Deshalb wäre mein Plädoyer, einfach die Hausnummer aufzulösen und die Läden wegzulassen.

**Comment by phoet** [comment]
ja, das ist etwas ärgerlich. ich werde da evtl schauen ob man die geo-suche entsprechend konfigurieren kann, dass dort mehr straßennamen raus kommen. 

über den map-picker ist es aber sehr einfach dann den marker an eine passende stelle zu ziehen.

<img width="247" alt="Screen Shot 2019-08-26 at 13 45 51" src="https://user-images.githubusercontent.com/48745/63688482-d7103280-c807-11e9-92f7-47951275eb57.png">

**Comment by phoet** [comment]
den map-picker habe ich noch etwas angepasst, damit dort keine POI mehr bevorzugt werden.

der lookup der adresse läuft über opencagedata und sollte auch soweit möglich keine POI zurückliefern.

wenn dort die qualität nicht gut genug ist, dann muss ich schauen ob das noch etwas in form gestreichelt werden kann, oder ob es mit einem anderen lookup besser geht.
