### ISSUE TITLE
Standorterkennung bei Fotos von Android-Gerät funktioniert nicht

### ISSUE THREAD

**Issue by K0nsch** [weg-li/weg-li#48]
Moin,

leider funktioniert seit einigen Tagen die automatische Standorterkennung der Bilder anhand der Meta-Daten nicht mehr. 
Verwendetes Gerät ist ein Samsung Galaxy Note 9 mit Android 9.

Grüße,

Jascha

**Comment by phoet** [comment]
Hi joscha, die automatische Verarbeitung war "zu schnell" da waren die exif Daten noch nicht hinterlegt, die auch in einem Background Job ausgelesen werden. Klappt es beim 2. Mal drücken auf analysieren?

Das ganze benötigt wohl noch etwas mehr Orchestrierung

**Comment by K0nsch** [comment]
Heute hat es komischerweise auf Anhieb funktioniert. Ich behalte das mal im Auge, danke :)

**Comment by phoet** [comment]
ja, es sollte jetzt besser klappen. ich hatte dafür eigentlich schon eine optimierung eingebaut, aber das ist irgendwo stecken geblieben und nicht live gegangen.

**Comment by phoet** [comment]
wenn es wieder auftritt, dann gerne wieder aufmachen das issue
