### ISSUE TITLE
Keine Empfangsbestätigungen der Berliner Bußgeldstelle seit etwa 11.10.2021

### ISSUE THREAD

**Issue by Wikinaut** [weg-li/weg-li#481]
Wir sind jetzt mindestens drei Leute, die seit Mitte Oktober keine einzige Empfangsbestätigung (mehr) erhalten haben.

Bitte um Klärung.

**Comment by Wikinaut** [comment]
siehe #483

**Comment by Wikinaut** [comment]
Ergänzend und Interessant: die Seite https://www.berlin.de/polizei/aufgaben/bussgeldstelle/anzeigenerstattung/ ist wohl auf den Seiten der Berliner Bußgeldstelle nicht mehr verlinkt.

**Comment by phoet** [comment]
Tritt dieses Problem derzeit noch auf?

**Comment by Wikinaut** [comment]
Ich erstelle zur Zeit keine Anzeigen mit https://weg.li mehr.

**Comment by Wikinaut** [comment]
Hi, sag mal, könnte es sein, dass anzeige@bowi ... seit diesem Tag zu große Mails "silently dropped" ? Jemand berichtete gestern oder so von einem anderen Polizeidienst.

**Comment by phoet** [comment]
Das ist eine mögliche Begründung, wir können das aber nicht von unserer Seite herausfinden.

**Comment by phoet** [comment]
Es ist auch nicht das erste mal, dass so etwas passiert. Nach diversen Nachfragen von Anzeigenden wurden die Eingangsbestätigungen dann wieder versendet.

Grundsätzlich ist eine Eingangsbestätigung optional und hat keinerlei Aussagekraft.

**Comment by Wikinaut** [comment]
Die Frage ist ja erstmal, *ob* die Mail(s) überhaupt da angekommen sind, oder ob der Server seit dem 11.10. zu große Mails gar nicht erst annimmt - ohne irgendeine Rückmeldung. Dass man serverseitig so etwas setzen kann, ist doch bekannt, ich habe das auch für einige Systeme so geregelt.

**Comment by phoet** [comment]
Nein, das ist keine Frage. Unser SMTP-Ausgangsserver versendet problemlos alle E-Mails, auch nach Berlin.

**Comment by Wikinaut** [comment]
Und: hast Du schon einmal in Betracht gezogen, alle Bildanhänge, wenn die in Summe größer als x MB sind, auf x transkodieren?

**Comment by Wikinaut** [comment]
> Nein, das ist keine Frage. Unser SMTP-Ausgangsserver versendet problemlos alle E-Mails, auch nach Berlin.

Es geht um den  Posteingangsserver bei anzeige@bowi, Du verstehst mich nicht.

**Comment by phoet** [comment]
Wir haben keine Möglichkeit den Posteingangsserver der Berliner zu prüfen. Was die mit erfolgreich zugestellten E-Mails machen ist für uns nicht erkennbar. Genauso könnten sie eine Eingangsbestätigung versenden und die E-Mail danach trotzdem löschen.

**Comment by phoet** [comment]
Bildanhänge wurden schon immer für den Versand komprimiert. Zusätzliche Komprimierung würde auf kosten der Bildqualität gehen.

**Comment by Wikinaut** [comment]
> Bildanhänge wurden schon immer für den Versand komprimiert. Zusätzliche Komprimierung würde auf kosten der Bildqualität gehen.

Okay! Sehe ich nun auch in(an) der erhaltenen CC-Mail der Anzeige, deren Größe mit 1,2 MB (mit 4 Fotos) perfekt aussieht.

**Comment by tmcguire** [comment]
Eine von mir versendete Anzeige von heute hat ebenfalls keine Empfangsbestätigung erhalten.
Weiß jemand ob die Bußgeldstelle in Berlin E-Mails (nach anzeige at bowi.berlin.de) überhaupt noch empfängt und bearbeitet?
