### ISSUE TITLE
[Verbesserungsvorschlag] Bitte neues Label für "(Anzeigeneingang) bestätigt"

### ISSUE THREAD

**Issue by Wikinaut** [weg-li/weg-li#482]
![grafik](https://user-images.githubusercontent.com/1151915/139724782-d29c921f-05ff-4f64-9b3b-bb2fbf3c2528.png)

Ich wünsche mir ein zusätzliches Label, das über den Zustand "(wegli) gemeldet" anzeigt, dass die entsprechende Bußgeldstelle den Eingang quittiert hat; "bestätigt" (oder: "quittiert" oder "eingegangen").

**Comment by phoet** [comment]
Das wäre sehr schön, ist allerdings mit der Schnittstelle E-Mail nicht zu leisten.
