### ISSUE TITLE
Feature Request: Opt-out von der Bildanalyse

### ISSUE THREAD

**Issue by carstenhag** [weg-li/weg-li#485]
Hey! Bei meinen Bildern (vor allem die, die ich im Winter aufnehmen, mit Blitz) bringt die Bildanalyse eh kaum was. Wenn ich ein paar Meldungen nacheinander erstelle, muss ich immer die ca 2-4s Analysezeit pro Bild abwarten. 

Zusöätzlich zu einer Zeitersparnis für mich würde natürlich auch die API die du benutzt nicht so oft aufgerufen werden müssen, was ja Kosten & Traffic sparen sollte.

**Comment by phoet** [comment]
Die Bildanalyse sollte auch bei schnelchten Witterungsverhätnissen Nummernschilder extrahieren können.

Die Wartezeit wird auch durch diesen Schritt nicht verschwinden, weil im Hintergrund immer eine Bildverarbeitung stattfindet um Thumbnails etc zu generieren.
