### ISSUE TITLE
404 in FAQ: Mehr Fragen und Antworten zum Thema Falschparker findet man auch beim <link>ADFC</link>.

### ISSUE THREAD

**Issue by gerdneuman** [weg-li/weg-li#488]
Der Link unter

> Mehr Fragen und Antworten zum Thema Falschparker findet man auch beim ADFC.

 ganz unten auf https://weg.li/faq ist tot (gibt einen 404er).

**Comment by Konafets** [comment]
Der Link zum ADFC ist tatsächlich tot. Welcher Inhalt sollte da mal verlinkt werden? Vielleicht dieser hier: https://hamburg.adfc.de/artikel/radweg-zugeparkt-falschparker-kannst-du-anzeigen

**Comment by kaese** [comment]
Der Link geht derzeit auf https://hamburg.adfc.de/verkehr/maengelmelder/falschparker/#c11652 .

Die Seite ist unter https://web.archive.org/web/20201110151708/https://hamburg.adfc.de/verkehr/maengelmelder/falschparker/ noch abrufbar.

Der Inhalt entspricht der neuen Seite unter https://hamburg.adfc.de/artikel/radweg-zugeparkt-falschparker-kannst-du-anzeigen

Es müsste also der Link ausgetauscht werden.

**Comment by kaese** [comment]
Habe mal einen PR erzeugt, #507
