### ISSUE TITLE
Irritierender Hinweis zu Chrome, denn Firefox for Androids funktioniert genauso gut wie Chrome for Android

### ISSUE THREAD

**Issue by gerdneuman** [weg-li/weg-li#489]
Beim Erfassen von Meldungen gibt es aktuell den Hinweis:

> Android + Chrome
> 
> Für die Erkennung des Standortes auf Android empfielt es sich Chrome zu benutzen und Fotos über den File-Picker Durchsuchen auszuwählen.

Das hat mich irritiert, denn ich nutze Firefox for Android. Ich dachte (wegen erhöhter Privacy im Firefox), dass Firefox eventuell in den hochgeladenen Fotos die Metadaten löscht (GPS, Zeitstempel). Habe dennoch Firefox benutzt und es hat wunderbar funktioniert.

Hinweis am besten ändern zu:

> Android + Chrome/Firefox
> 
> Für die Erkennung des Standortes auf Android empfielt es sich Chrome oder Firefox zu benutzen und Fotos über den File-Picker Durchsuchen auszuwählen.

**Comment by phoet** [comment]
Habe den Hinweis entfernt, falls es wieder einmal Probleme mit den GPS Daten geben sollte kann man ja einen neuen Hinweis einfügen.
