### ISSUE TITLE
Favoriten setzen für Wiederholungstäter

### ISSUE THREAD

**Issue by corincorvus** [weg-li/weg-li#49]
Hey,
ist zwar kein Fehler, aber ich würde gerne eine Idee vorstellen. Vielleicht findet diese ja anklang.

Gerade bei Falschparkern hat man ja oftmals Wiederholungstäter und nicht immer ist die Erkennung einwandfrei. Um sich bei gewissen Kandidaten die Nachbearbeitung zu sparen, könnte man doch einen Favorit oder einen Pool aus Adressen setzen oder Fahrzeuginfos, sodass man bei einem Bild, was nicht korrekt analysiert wird, einfach mit einem Auswahlmenü Auto-xy anklickt und alle Daten werden eingetragen.

Habe recht viele, die immer an der gleichen Stelle stehen und wo ich eigentlich nur Datum und Uhrzeit ändern muss. 

Freue mich auf Feedback.

Grüße
Corin

**Comment by telewolf** [comment]
Mir geht es ähnlich. Zum einen hat man Standart-Stellen wo häufig ein anderes Auto den selben Verstoß begeht. Zum anderen hat man Standard-Fahrzeuge die an unterschiedlichen Stellen unterschiedliche Verstöße begehen. In beiden Fällen wäre ein Preset / Favorit wirklich großartig.

Ich mache mal den Zusatz-Vorschlag, dass sich wegli zu einem Kennzeichen den Hersteller und die Farbe merkt.

**Comment by phoet** [comment]
grundsätzlich spricht nichts dagegen sich ein "fahrzeug" zu merken und dies über eine auswahl zur verfügung zu stellen. mein ansatz ist allerdings ein anderer, ich möchte zuverlässig aus den fotos alle relevanten infos erkennen und zuordnen.

so eine "krücke" wäre für mich nur dann sinnvoll, wenn die erkennung nicht eine trefferquote über 90% erreicht.

**Comment by phoet** [comment]
Wird im Analyse Schritt ein bekanntes Nummernschild ausgelesen, dann werden die Daten der letzten Meldung kopiert.

**Comment by telewolf** [comment]
Sehr schicke Funktion! 
Welche Daten der letzen Meldung werden kopiert? Nur Fahrzeug-Hersteller und Farbe oder auch der Verstoß oder auch die Adresse?

**Comment by phoet** [comment]
nur die fahrzeugdaten und der verstoß

**Comment by telefontuning** [comment]
Funktioniert das nur wenn die Kennzeichen-Erkennung bei der Analyse klappt? Oder auch bei manueller Kennzeichen-Eingabe oder Korrektur? Ich hatte eben den Eindruck, letzteres geht nicht.

**Comment by phoet** [comment]
nur bei der automatischen erkennung. wird das kennzeichen von hand eingegeben müsste es sonst noch einen zwischenschrit oder irgendeine form der auto-suggest geben, die eine änderung von marke und farbe etc vorschlägt.

**Comment by telewolf** [comment]
Ich würde es toll finden, wenn nach der manuellen Korrektur des Kennzeichens erneut geprüft wird ob Fahrzeugdaten und Verstoß für das Kennzeichen hinterlegt sind und falls ja, dass diese geladen werden. Das viel zeit die 3 Felder nicht manuell auszufüllen, wenn die Daten schon vorhanden sind.

**Comment by telewolf** [comment]
Kann es sein, dass die Verstoß und Fahrzeugdaten-Automatik „blank-sensitiv“ ist? Ich habe gerade eine Meldung bearbeitet, bei der das Kennzeichen auf anhieb richtig erkannt wurde, aber Fahrzeugmarke und Verstoß wurden trotzdem nicht ausgefüllt obwohl ich zu dem Fahrzeug diese Daten bei einer anderen Meldung bereits eingegeben hatte.
