### ISSUE TITLE
Meldung und Meldungsübersicht zu Tatbestand verlinken

### ISSUE THREAD

**Issue by gerdneuman** [weg-li/weg-li#490]
**Motivation:** Ich habe jetzt ersten Meldungen gemacht (erst mal 1000 Dank für weg-li :heart: ). Jetzt hatte mich interessiert, was das überhaupt kosten wird (lohnt es ich überhaupt). 

Das fand ich recht kompliziert rauszufinden. Zuerst bin ich über irgendeinen Link auf weg.li zu dem PDF hier https://weg.li/pdf/bkat_owi_18_05_2020_pdf.pdf gelandet. Ich glaube, weil ich gesucht habe: https://www.google.de/search?source=hp&q=site%3Aweg.li%20parken%20schutzstreifen%20radweg&meta=&aq=f&aqi=g10&aql=&oq=&gs_rfai=

Dann habe ich irgendwann https://weg.li/charges entdeckt. Dann hab ich via Freitext-Suche dort und dem `Verstoß` einer Meldung versucht die Kosten rauszufinden, was aber auch schwierig ist, weil das Wording des `Verstoß` nicht 100% gleich zur ellenlangen Tabelle auf https://weg.li/charges ist.

**Was ich mir wünschen würde:**
1. In der Meldung selbst verlinkt der Verstoß zu den genau passenden Eintrag auf https://weg.li/charges
2. Ggf. auch schon in der Meldungen-Übersicht eine Spalte für Verstoß und erwartete Kosten bzw. zumindest Verlinkung

PS Unter https://weg.li/charges gibt es `TBNR` - keine Ahnung was das heißt. Ja, ich kann es googeln - "Tatbestandsnummer", aber Info-Icon mit Erklärung wäre besser. Das könnte ggf. auch noch eine Zeile unter Meldungen sein (die dann verlinkt)... Aktuell taucht das unter Meldungen nicht auf, dabei wäre das die idellle Kennung/ID um von einer Meldung zu Tatbestand zu springen bzw. zu suchen, weil wirklich eindeutig.

PPS Danke nochmal für das tolle Tool :-)

**Comment by phoet** [comment]
Hallo Gerd,

eine Verlinkung ist möglich und auch sinnvoll.

Bei der Erstellung von Anzeigen weisen wir absichtlich keine Geldbußen aus, da dies ein falsches Zeichen an den Zeugen senden könnte. Grundsätzlich ist auch eine Anzeige nicht an die Geldbuße gekoppelt, da eine Anzeige auch mit einem Verwarngeld eingestellt werden kann, ohne ein Bußgeldverfahren zu eröffnen.
