### ISSUE TITLE
Fehler beim Seeden der initialen Daten

### ISSUE THREAD

**Issue by Konafets** [weg-li/weg-li#494]
Ich versuche gerade das Projekt bei mir lokal aufzusetzen und erhalte hier und da Fehler. Einer davon ist dieser:

```shell
rake dev:data
rake aborted!
Google::Cloud::PermissionDeniedError: forbidden: wegli-107@wegli-332509.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object.
/Users/foo/Sites/wegli/lib/tasks/development.rake:5:in `block (2 levels) in <main>'

Caused by:
Google::Apis::ClientError: forbidden: wegli-107@wegli-332509.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object.
/Users/foo/Sites/wegli/lib/tasks/development.rake:5:in `block (2 levels) in <main>'
Tasks: TOP => dev:data
(See full trace by running task with --trace)
```

Ich habe im Projekt in der Google Cloud Console ein Dienstkonto angelegt, dort einen JSON-Key erstellt und diesen in das Wegli-Projekt gelegt. Als Rollen habe ich dieser erteilt:

![2021-11-18_12-06-08](https://user-images.githubusercontent.com/363363/142404167-b58da9fc-c7f5-4fd9-9076-d649eaf8b537.jpg)

Habe ich was vergessen?

**Comment by phoet** [comment]
manchmal dauert es etwas, bis der zugriff funktioniert. https://stackoverflow.com/questions/51410633/service-account-does-not-have-storage-objects-get-access-for-google-cloud-storag

es ist auch möglich mit dem disk-storage zu arbeiten, wie im test environment zu sehen.
