### ISSUE TITLE
Bezirke sind falsch gesetzt. 

### ISSUE THREAD

**Issue by K0nsch** [weg-li/weg-li#50]
Bei der Übersicht wird der falsche Bezirk angegeben. 

Seit dem 22.08.2019 steht bei meinen Meldungen "Bezirk Hamburg"
Davor wurden meine Meldungen in Bochum nur einmal unter "Bezirk Bochum" registriert, ansonsten steht bei Allen vor dem 22.08 "Bezirk Herne".

Mein Account ist auf Bezirk Herne eingestellt. Gut fände ich es aber, wenn es ein Dropdown-Menü geben würde, in dem man den Bezirk angeben kann und/oder dieses Automatisch anhand des Standortes gefüllt wird. 

Grüße,

Jascha
![2019-08-29 10_00_29-5e049c8612ab4746c915059fef8d4117 · Meldungen · 📸 📝 ✊ weg-li_ 1, 2, 3 - Macht d](https://user-images.githubusercontent.com/13088073/63922032-2b9ff180-ca44-11e9-8bd4-4bcbba3ea0d4.png)
![2019-08-29 10_01_15-2e14852b706ba6e26ed56ee131dc9630 · Meldungen · 📸 📝 ✊ weg-li_ 1, 2, 3 - Macht d](https://user-images.githubusercontent.com/13088073/63922033-2b9ff180-ca44-11e9-97a6-16d31f0bd6a6.png)
![2019-08-29 10_01_33-76fe2dc509c1e2bd4e0740e456ad940f · Meldungen · 📸 📝 ✊ weg-li_ 1, 2, 3 - Macht d](https://user-images.githubusercontent.com/13088073/63922034-2c388800-ca44-11e9-8ff5-73cb1a879f97.png)

**Comment by K0nsch** [comment]
Das dürfte auch der Grund sein, warum ich meine Meldungen nicht mehr auf der Übersichtskarte meines Bezirks sehe. 

Andere Städte wie Bielefeld und Saarbrücken scheinen dasselbe Problem zu haben.
![2019-08-29 10_14_38-📸 📝 ✊ weg-li_ 1, 2, 3 - Macht die Bahn frei!](https://user-images.githubusercontent.com/13088073/63922967-fd231600-ca45-11e9-9944-6d3af217fad6.png)

**Comment by phoet** [comment]
danke für den hinweis joscha. der bezirk an der meldung wurde erst später hinzugefügt und bei der daten-migration der einfachheit halber der bezirk des benutzers hinterlegt. deshalb steht beim letzten herne.

die ersten beiden sind noch "offen" und der bezirk steht dann per default auf hamburg. das habe ich jetztumgebaut, dass nach dem hochladen dort bereits der bezirk des benutzers eingetragen ist.
