### ISSUE TITLE
Publish as Progressive Web App (PWA) in Google Play

### ISSUE THREAD

**Issue by gerdneuman** [weg-li/weg-li#514]
Well, weg.li seems to work pretty much as a PWA already given the FAQ:

https://github.com/weg-li/weg-li/blob/6cf7fccc5c47f24500ca50002c82451970e56164/app/views/home/faq.html.slim#L71-L77

There are many pro arguments for having it listed as an app in app store. Namely, greater visibility and discoverability. Also usability: For tech savvy users like me this is not a deal, but many people are not able to bookmark a website in a browser. For them even entering an URL in the address bar is complicated (thinking of my grandpa).

This is not possible with Apple at the moment as far as I know, but seems possible with Google's Play store (by far the greatest market share in Germany):

Just a few links on how to do this:
* https://www.simicart.com/blog/pwa-app-stores/
* https://css-tricks.com/how-to-get-a-progressive-web-app-into-the-google-play-store/
* https://itnext.io/how-to-get-a-progressive-web-app-into-the-google-play-store-2aef6fff43e3

**Comment by dbermbach** [comment]
What happened to the Android app that our team built last year?

**Comment by phoet** [comment]
@dbermbach it was never oficially released to the public. there is no specific reason for this, mostly lack of resources form my side.

**Comment by dbermbach** [comment]
Okay, I was just wondering. And of course there is never enough time :-)

**Comment by phoet** [comment]
Releasing it was actually not the issue, but there was additional infra + support for the app which i could not reasonably provide up until now.

**Comment by phoet** [comment]
i've incorporated some of the algorithms into the existing app though
