### ISSUE TITLE
Klickanzahl reduzieren

### ISSUE THREAD

**Issue by dbermbach** [weg-li/weg-li#515]
Drei Kleinigkeiten könnten die Klickanzahl reduzieren:

1. das Pulldownmenu mit Gefährdung/Behinderung durch Radiobuttons ersetzen (oder Checkboxen? Ich sehe häufig Gefährdung UND Behinderung). Würde die Klickzahl von zwei auf eins reduzieren.
2. für das Pulldownmenu mit der Verstoßdauer für alle Situationen ohne längere Dauer, die sich aus den EXIF-Timestamps ergibt, einen Defaultwert als persönliche Einstellung konfigurierbar machen. Grund: 99% meiner Meldungen sind "stand dort mindestens 5min" - und jedes Mal sind es mindestens zwei Klicks.
3. Für die Checkbox "war verlassen" entweder den Defaultwert rumdrehen oder ihn als persönliche Einstellung konfigurierbar machen. Grund: 99% meiner Meldungen sind "war verlassen", weil ich keine Lust mehr auf Diskussionen mit Aggrofalschparkern habe.

**Comment by RalphBike** [comment]
Zusätzlich noch:

4. Filterfunktion in /notices/:
Bitte den Fokus nach Klick der Lupe in das Eingabefeld setzen, damit man direkt tippen kann. Das spart einen von drei Klicks.

Zu 2.: Ich würde mir einen einstellbaren Defaultwert wünschen. Ich muss jedes Mal von Hand "3 Min." auswählen.
3 Min ist IMHO ein sehr guter Wert, weil dort die Grenze zwischen Halten und Parken liegt und das Interval gleichzeitig nicht übermäßig lang ist.

**Comment by Nakaner** [comment]
@dbermbach schrieb:
> 1. das Pulldownmenu mit Gefährdung/Behinderung durch Radiobuttons ersetzen (oder Checkboxen? Ich sehe häufig Gefährdung UND Behinderung). Würde die Klickzahl von zwei auf eins reduzieren.

Gefährdung ist schwerwiegender als Behinderung und zieht ein höheres Bußgeld nach sich. Daher genügt es, wenn man nur eines von beiden wählen kann.

OT: Gefährdung ist laut ständiger Rechtssprechung des BGH erst bei einem Beinaheunfall verwirklicht, also einer Situation, bei der es aus Sicht eines objektiven Beobachters gerade noch einmal gut gegangen ist (BGH, Beschluss vom 27. April 2017, Az. [4 StR 61/17](https://www.hrr-strafrecht.de/hrr/4/17/4-61-17.php); BGH, Beschluss vom 6. Juli 2021, Az. [4 StR 155/21](https://juris.bundesgerichtshof.de/cgi-bin/rechtsprechung/document.py?Gericht=bgh&Art=en&nr=121093&pos=0&anz=1)). Ein blockierter Radfahrstreifen führt deshalb nicht allein zu einer Gefährdung, sondern ist nur eine Behinderung. Für eine Gefährdung muss der/die Radfahrende schon abbremsen und anhalten müssen, weil er/sie sonst beim Einfahren auf die Fahrbahn überfahren werden würde.

> Für die Checkbox "war verlassen" entweder den Defaultwert rumdrehen oder ihn als persönliche Einstellung konfigurierbar machen. Grund: 99% meiner Meldungen sind "war verlassen", weil ich keine Lust mehr auf Diskussionen mit Aggrofalschparkern habe.

Dann musst du noch an deiner Fotografiertechnik arbeiten. ;-)

@RalphBike schrieb:
> Zu 2.: Ich würde mir einen einstellbaren Defaultwert wünschen. Ich muss jedes Mal von Hand "3 Min." auswählen.

Als Zeuge bist du zur wahrheitsgemäßen Aussage verpflichtet. Wenn du nicht beobachtet hast, dass das Fahrzeug wirklich 180 Sekunden lang dort stand, solltest du eben eine längere Standzeit angeben. Das Verlassensein reicht aus, damit aus Halten Parken wird (die Rechtssprechung ist hier und da ungenauer, aber das darf dann das Amtsgericht entscheiden).

**Comment by dbermbach** [comment]
> @dbermbach schrieb:
> 
> > 1. das Pulldownmenu mit Gefährdung/Behinderung durch Radiobuttons ersetzen (oder Checkboxen? Ich sehe häufig Gefährdung UND Behinderung). Würde die Klickzahl von zwei auf eins reduzieren.
> 
> Gefährdung ist schwerwiegender als Behinderung und zieht ein höheres Bußgeld nach sich. Daher genügt es, wenn man nur eines von beiden wählen kann.
> 
> OT: Gefährdung ist laut ständiger Rechtssprechung des BGH erst bei einem Beinaheunfall verwirklicht, also einer Situation, bei der es aus Sicht eines objektiven Beobachters gerade noch einmal gut gegangen ist (BGH, Beschluss vom 27. April 2017, Az. [4 StR 61/17](https://www.hrr-strafrecht.de/hrr/4/17/4-61-17.php); BGH, Beschluss vom 6. Juli 2021, Az. [4 StR 155/21](https://juris.bundesgerichtshof.de/cgi-bin/rechtsprechung/document.py?Gericht=bgh&Art=en&nr=121093&pos=0&anz=1)). Ein blockierter Radfahrstreifen führt deshalb nicht allein zu einer Gefährdung, sondern ist nur eine Behinderung. Für eine Gefährdung muss der/die Radfahrende schon abbremsen und anhalten müssen, weil er/sie sonst beim Einfahren auf die Fahrbahn überfahren werden würde.
> 

Die Idee dahinter war, dass die Bußgeldstelle, wenn sie _keine_ Gefährdung sieht (bspw. entsprechend deiner OT-Beschriebung), zumindest noch ein "mit Behinderung" verbucht und dann nicht ein "ohne Behinderung daraus macht".

**Comment by phoet** [comment]
der grossteil ist inzwischen obsolet
