### ISSUE TITLE
Mark useless/report ignoring districts as such

### ISSUE THREAD

**Issue by thrillfall** [weg-li/weg-li#529]
Can we maybe add a warning when we know about a district where reports only go to the trash?
I wasted last 3 month filing reports to Berlin police and they even publicly tell us they don't do shit about it.
Stats 2021:
https://www.berlin.de/polizei/aufgaben/bussgeldstelle/anzeigenerstattung/

We could add a link to this guide on how to make the police do their job; https://www.abschleppgruppe.com/

**Comment by phoet** [comment]
We actually don't know what Berlin police is doing currently. They announced to support the under-staffed traffic police so that reports will be worked on. It should also be in the responsibility of the city of berlin to inform citizens about such things.
