### ISSUE TITLE
Vorschlag: Verstoß Parken auf dem Radweg hinzufügen

### ISSUE THREAD

**Issue by 4rne** [weg-li/weg-li#53]
Mir fehlte heute, dass man in der Liste von Verstößen kein ``` Parken auf dem Radweg ``` auswählen kann. (Transporter parkt auf dem Radweg um Elektroroller einzusammeln, https://www.weg-li.de/notices/bf51379ef5d6ad995143b7933005fc93). 
Ich weiß nicht, ob Parken auf dem Fußweg äquivalent ist; dann könnte man dort eventuell in Klammern noch Radweg ergänzen, falls es so ist, damit man das auch per Suchfunktion findet.

**Comment by phoet** [comment]
Der heißt lediglich anders und zwar "Parken auf dem Radfahrstreifen"

**Comment by 4rne** [comment]
Wäre es dann nicht intuitiv, den Punkt zu ändern in Radfahrstreifen/Radweg? Für mich ist ein Schutzstreifen und ein Radfahrstreifen beides auf der Fahrbahn. Deswegen war ich verwirrt.

**Comment by phoet** [comment]
siehe dazu https://github.com/weg-li/weg-li/issues/22#issuecomment-522125444
