### ISSUE TITLE
Adressen Erkennung aus GPS vom Bild geht nicht mehr auf Android 

### ISSUE THREAD

**Issue by spiii** [weg-li/weg-li#530]
Mit dem Handy geschlossene Fotos (mit GPS an) haben früher nach dem upload direkt die Adresse im Formular reingeladen. Dieses geht seid einigen Wochen nicht mehr.
Ich nutze Chrome Browser auf Android.

**Comment by phoet** [comment]
Die Funktionalität ist unverändert vorhanden. In der Regel handelt es sich um ein Client-Problem, siehe hierzu auch die FAQ https://www.weg.li/faq#faq-9 bzw https://github.com/weg-li/weg-li/issues/489
