### ISSUE TITLE
Exif-Daten sichtbar machen. Oder Wiederholung der Analyse nach erneutem Foto-Upload?

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#532]
Hi, mir fehlen Informationen zur korrekten Wahl der Dauer für den Fall, dass ich in einer Meldung Fotos nachträglich hochlade.

Szenario:
* Jemand parkt falsch, ich mache 1-2 Fotos, lade sie hoch, erstelle eine Meldung.
* Ein paar Stunden später steht der Wagen immer noch da. Ich mache eine weiteres Foto und füge es der ersten Meldung hinzu.
* Ergebnis: eine Meldung mit mehreren Fotos über einen längeren Zeitraum, aber die Meldung weiß nichts davon. Und: die Dateinamen sind auch keine Hilfe, da zumindest mein Android die Dateinamen neu vergibt, wenn ich die Bilder auf dem Telefon bearbeite.
* Aktueller Workaround: Alle Fotos runterladen und Exif-Daten extrahieren, dann von Hand das Interval berechnen :-/

Ideen dazu:
* Meldungen nochmal analysieren lassen, vielleicht auf Knopfdruck? Oder automatisch nach jedem Upload?
* Und/oder: Anzeige der Exif-Zeit im Foto-Popup.

**Comment by phoet** [comment]
Nachträglich User-Daten automatisch zu ändern ist ein no-go. Der Use-Case selber hat für mich keine hohe Priorität, weil er wohl außerst selten ist. In der Regel werden Fotos hochgeladen, Daten befüllt und sofort gemeldet.
