### ISSUE TITLE
Suchfunktion Tatbestände: Umgang mit leeren Strings

### ISSUE THREAD

**Issue by Nakaner** [weg-li/weg-li#539]
Die Suchfunktion bei den Tatbeständen ist defekt.

[https://www.weg.li/charges?utf8=%E2%9C%93&classification=&term=112454&button=](https://www.weg.li/charges?utf8=%E2%9C%93&classification=&term=112454&button=) liefert keine Ergebnisse.

[https://www.weg.li/charges?utf8=%E2%9C%93&classification=5&term=112454&button=](https://www.weg.li/charges?utf8=%E2%9C%93&classification=5&term=112454&button=) liefert den gewünschten Tatbestand.

[https://www.weg.li/charges?utf8=%E2%9C%93&term=112454&button=](https://www.weg.li/charges?utf8=%E2%9C%93&term=112454&button=) liefert auch den gewünschten Tatbestand.

Ein leerer String als Wert des Query-String-Parameters `classification` sollte wie ein fehlender Key betrachtet werden. Zumindest war es bislang so. Sonst müsste man das UI anpassen.

**Comment by phoet** [comment]
Danke für den Hinweis!
