### ISSUE TITLE
Validatoren verhindern Abspeichern von unvollständigen Meldungen

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#541]
Hi, 

leider verhindern die Validatoren das Abspeichern von teilbearbeiteten Meldungen. Man kann Meldungen daher nur abspeichern, wenn sie komplett und verschickbar sind. 

So kann ich z. B. nicht schnell mal ein Kennzeichen nachtragen, sondern muss die Anzeige komplett fertig machen. In meinem Fall wird ein fehlender Tatbestand bemängelt.

Sinnvoller wäre es, wenn Zwischenstände abspeicherbar wären und die Validatoren entweder nonblocking sind oder erst später greifen.

**Comment by phoet** [comment]
Grundsätzlich halte ich das nicht für sinnvoller. Dieser Use-Case ist zwar valide, aber nur eine Ausnahme. Demenstprechend könnte man diese Funktionalität zum Beispiel über einen Knopf im Dropdown Menü verstecken

<img width="298" alt="Screenshot 2022-03-15 at 10 00 36" src="https://user-images.githubusercontent.com/48745/158342733-089147b3-540b-43fc-9947-204410a15467.png">
.

**Comment by RalphBike** [comment]
Moin, "verstecktes" Abspeichern ohne Validatoren finde ich okay. Validatoren umbauen wäre vermutlich Overkill.

Fehlt nur noch ein Text. Vielleicht "Zwischenstand speichern"?

**Comment by phoet** [comment]
<img width="272" alt="Bildschirmfoto 2022-11-17 um 21 24 21" src="https://user-images.githubusercontent.com/48745/202552299-fc2c5d06-6dfd-46ad-8df5-74656dd0e219.png">
