### ISSUE TITLE
Metadaten von bearbeiteten Bildern werden nicht ausgelesen

### ISSUE THREAD

**Issue by foss-** [weg-li/weg-li#544]
iOS 15.4, 15.3.1, 15.3

**Reproduzieren**

1. unter iOS Bild machen (im Kombatibilitätsmodus)
2. Bild bearbeiten und dort z.b. mit Stift Menschen unkenntlich machen
3. speichern
4. Bild bei weg.li hochladen

**Aktuell**

Ort und Zeit werden nicht aus dem Bild gelesen und müssen manuell vergeben werden.

**Erwartet**

Ort und Zeit sollten aus dem Bild gelesen werden.

Wenn unter iOS > Bilder das bearbeitete Bild betrachtet wird, sind sowohl Zeit als auch Geo-Koordination vorhanden. Daher ist etwas unklar, warum die Metadaten nicht wie erwartet ausgelesen werden.

**Comment by phoet** [comment]
Dies ist ein iOS Bug auf Client-Seite. Du kannst Dir das Bild von weg.li im Original (so wie hochgeladen) herunterladen und selbst nachschauen.

**Comment by foss-** [comment]
Nach download sehe ich ein Bild ohne location und mit timestamp des downloads. Kannst du den Fehler genauer ausführen?  Weißt du, ob das schon bei Apple bekannt ist und es eine rdar id dazu gibt?

**Comment by phoet** [comment]
https://stackoverflow.com/questions/57942150/file-upload-and-exif-in-mobile-safari

**Comment by foss-** [comment]
https://bugs.webkit.org/show_bug.cgi?id=207088
rdar://33646508

Seems Apple is aware and will have news *soon* (TM) after coordinating with upload team. 👀

**Comment by phoet** [comment]
So most likely never

**Comment by phoet** [comment]
Same Problem, differnt OS https://stackoverflow.com/questions/61482589/chrome-on-android-10-image-uploading-strips-gps-exif-data
