### ISSUE TITLE
Info zu iOS Safari ausblenden in kompatiblen Browsern

### ISSUE THREAD

**Issue by tordans** [weg-li/weg-li#56]
Ich finden den Hinweis zu dem Metadaten-Problemen von iOS Safari super.
Aber es hat mich irritiert, dass der Hinweis auch dann sichtbar ist, wenn ich in einen der empfohlenen Browser Chrome/Firefox gewechselt bin.

Verbesserungsvorschlag: Den Hinweis dann ausblenden.

Umsetzungsidee: Alle Texte mit einer class versehen und diese im default "display: none" und nur für iOS Safari sichtbar (vielleicht https://solvit.io/bcf61b6).

**Comment by phoet** [comment]
schöner hack :D das werde ich demnächst übernehmen.

es ist ein wenig erschreckend wie schlecht der browser support bei den mobilen endgeräten immernoch ist. man könnte meinen, es wäre inzischen einfach eine cross plattform website zu bauen...

**Comment by phoet** [comment]
wird jetzt nur noch im ios safari eingeblendet

**Comment by telewolf** [comment]
Da ich Safari auf iOS benutze und es bei mir keine Probleme mit der Standorterkennung gibt, verstehe ich den Hinweis nicht.

**Comment by phoet** [comment]
Es ist sehr komisch... Niemand kann mir sagen warum es bei manchen iOS Geräten nicht funktioniert. Bei meinen Tests mit iPhone 6 und iPad hat es jeweils problemlos geklappt...

**Comment by phoet** [comment]
versuche dem ganzen noch mal auf den grund zu gehen https://stackoverflow.com/questions/57942150/file-upload-and-exif-in-mobile-safari
