### ISSUE TITLE
Tatzeit sollte als Ende statt als Beginn gewertet werden

### ISSUE THREAD

**Issue by radpansen** [weg-li/weg-li#561]
Es ist doch meist so: Ich gehe irgendwo vorbei und sehe jemanden falch parken. Komme ich auf dem Rückweg dran vorbei und er/sie steht da immer noch, mache ich ein Foto und verweglie das fix. Ich weiß dann die Uhrzeit des Fotos und dass er/sie da schon seit mindestens ungefähr x Minuten/Stunden steht.

Daher ist die Information, die ich eingebe doch meistens: Fahrzeug steht zur Uhrzeit x schon seit mindestens Zeit y dort und steht dort möglicherweise noch viel länger.
Fast nie ist die Denke, ich mache jetzt mal ein Bild, schaue irgendwann noch mal vorbei und sage dann der App, Fahrzeug steht dort schon seit X Uhr für mindestens Y Stunden.

Beispiel: Hatte letztens Abends beim Nachhausekommen ein Fahrzeug im Kreuzungsbereich. Da mache ich kein Foto, weil vielleicht ist das Fahrzeug in wenigen Sekunden weg, das lohnt nicht. Stand früh aber immernoch da. Dann mache ich das Foto und verweglie es. Dann ist die Tatzeit aus den Bilddaten 8:00 Uhr und ich wähle "mindestens 3 Stunden" aus. Im Anzeigetext wird daraus dann 8:00 - 11:00 Uhr. Und da bin ich der Meinung, das ist zu 99% Quatsch.

**Comment by phoet** [comment]
Diese subjektive Meinung teile ich nicht.

**Comment by plangin** [comment]
Ich schon.

**Comment by phoet** [comment]
Für den Beleg der Tat und die Tatzeit ist es notwendig den Beginn des Beobachtungszeitraums zu dokumentieren.
