### ISSUE TITLE
Foto-Download geht nicht mehr: Your request has a malformed header.

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#563]
Hi, bei mir scheitert zur Zeit der Foto-Download mit folgender Fehlermeldung:

 

```
<Error>
<Code>MalformedSecurityHeader</Code>
<Message>Your request has a malformed header.</Message>
<ParameterName>signature</ParameterName>
<Details>Signature was not base64 encoded</Details>
</Error>

```
Browser: FF 99 unter Linux.

Außerdem wäre es nett, wenn sich der Download-Button eher wie ein Download-Button verhalten würde und mir das Bild zum Download anbieten würde und man nicht von der Seite wegnavigiert. Bisher ist hinter dem Button nur ein Link auf das Bild. 

Danke! 

PS: Weg.li ist toll!

**Comment by phoet** [comment]
Scheitert der Download weiterhin? Das öffnen per Download wurde leider in einer aktuellen Version von Rails kaputt konfiguriert, weshalb sich die dispatch header nicht entsprechend einstellen lassen. Sehr ärgerlich

**Comment by RalphBike** [comment]
Geht wieder, schon seit ein paar Tagen. Ich schließe das Ticket.
