### ISSUE TITLE
Exif-Daten in "Normalansicht" fehlen

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#568]
Hi, leider sind die Exif-Daten aus den JPEGs der Normalansicht verschwunden. Also die Bilder, die im Foto-Popup angezeigt werden, nicht die Thumbnails. Breite 1280 px. 

Ich verwende die Daten gerne, um Aufnahmezeitpunkte via Browser-Plugin anzuschauen. Gibt es eine Chance, die Exif-Daten da wieder zu kriegen? In der Vollansicht sind sie zwar noch drin, aber das sind ein paar Klicks mehr. 

Danke!

**Comment by phoet** [comment]
Die Bilder werden jetzt über Cloudflare geladen, ich bin mir nicht sicher, ob es möglich ist dort die Meta-Daten beizubehalten.

**Comment by phoet** [comment]
sollten jetzt wieder enthalten sein
