### ISSUE TITLE
Lesbarkeit der Hausnummern in der Karte verbessern

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#575]
Hi, die Hausnummern in der OSM-Karte sind oft schlecht lesbar. Da der Algorithmus nach einem Klick in die Karte nicht immer die richtige Nummer vorschlägt, ist hier oft manuelle Kontrolle und Korrektur nötig. Allerdings ist die Lesbarkeit der Hausnummern in der Karte schlecht, die Nummern sind klein und haben wenig Kontrast.

Daher schlage ich vor, einen Custum-Skin von Mapbox anzulegen und zu verwenden, bei dem die Hausnummern besser lesbar sind. Der Font darin sollte **Bold** und größer sein. Eine andere Farbe mit mehr Kontrast wäre nett, kriege ich mit Mapbox aber nicht hin.

Lässt sich alles mit überschaubarem Aufwand in Mapbox in einer Custom Skin konfigurieren, habe ich eben getestet. Siehe Vorher-Nachher-Bild im Anhang.

![Bildschirmfoto_2022-06-15_22-55-57](https://user-images.githubusercontent.com/17691743/173928323-8ebe3590-c16e-4f46-88fa-adbaca346bb9.png)

**Comment by RalphBike** [comment]
Hi, hast du die Änderung schon ausgerollt? Mir fällt auf, dass das Zoom nun beschränkt zu sein scheint. Ich vermute, es geht nur noch Level 17, statt 18. Ich bekomme so nur relativ kleine Hausnummern angezeigt.

**Comment by phoet** [comment]
es werden jetzt die standard OSM tiles verwendet, die mapbox leute wollen viel zu viel geld für ihren käse haben. der retina-modus macht es so klein, habe ich deaktiviert.

**Comment by RalphBike** [comment]
Okay, danke. Die Nummern sind jetzt - zumindest bei mir - besser lesbar.
