### ISSUE TITLE
Thüringer Ordnungsämter möchten, dass ihr eigenes Portal verwendet wird 

### ISSUE THREAD

**Issue by mxa** [weg-li/weg-li#589]
Die Ordnungsämter weigern sich weg.li anzeigen zu bearbeiten und verweisen auf ihr eigenes Portal: https://thavelp.thueringen.de/thavelp/portal/zs/275713/start?pe=2120
Was kann man machen?

**Comment by phoet** [comment]
Das GitHub Repository ist für technische Probleme reserviert. Wende dich am besten an den örtlichen ADFC.

**Comment by mxa** [comment]
Kann der ADFC da einen Adapter programmieren? 🤡
