### ISSUE TITLE
Featurewunsch: Ausblenden der "mit identischem Namen"-Meldung für häufig verwendete Dateinamen

### ISSUE THREAD

**Issue by C-Otto** [weg-li/weg-li#593]
Ich benutze aus Gewohnheit für meine Fotos immer die Namen a.jpg, b.jpg, etc. Beim Upload bekomme ich die unten gezeigte Warnung, die prinzipiell sehr sinnvoll und hilfreich ist. Wäre es möglich, diese für (bestimmte?) sehr häufig genutzte Dateinamen auszublenden?

![image](https://user-images.githubusercontent.com/344948/187074731-50d5aee1-6f5d-4c68-9025-51f83b9d190b.png)

**Comment by C-Otto** [comment]
Mir außerdem anfangs nicht klar gewesen, dass "Meldung löschen" nicht die gelbe Warn-Meldung meint, sondern die "Anzeige". Mir ist aber auch nicht klar, was besser ist.

**Comment by phoet** [comment]
Hallo Carsten, wir werden dafür nicht extra eine logik einbauen.
