### ISSUE TITLE
City of Cologne GDPR Compliance

### ISSUE THREAD

**Issue by b12f** [weg-li/weg-li#596]
I received communication from the city of Cologne asking me to please append a note that I accept the data privacy agreements to the PDF of the notice.

In the form the city uses, they have an explicit option for this: https://formular-server.de/Koeln_FS/findform?shortname=32-F68_file_AnzVerkW&formtecid=3&areashortname=send_html

What would be a good way to incorporate this information into a notice email/pdf sent out by weg.li? I could perhaps write it in the extra comments, but alternatively this could be an option that weg.li somehow natively supports. For example a global boolean setting saying "I accept all data privacy agreements categorically", and that just appends a short note to all PDFs being sent out.

**Comment by phoet** [comment]
"Hiermit bestätige ich, dass ich die Datenschutzerklärung zur Kenntnis genommen habe und ihr zustimme."

Is already part of the E-Mail.

**Comment by b12f** [comment]
Thanks, apparently they did not read this or really want it as part of the PDF. In any case I've contacted them and unless further notices get bounced by the authorities I'll consider this closed. Thanks @phoet
