### ISSUE TITLE
Vorschlag zur Standorterkennung an Kreuzungen oder Einmündungen

### ISSUE THREAD

**Issue by chanelxoxo** [weg-li/weg-li#597]
Bei der automatischen Standorterkennung anhand der Geodaten wird der Ort angezeigt bzw. vorgeschlagen, an dem das Foto aufgenommen wurde. An Kreuzungen oder Einmündungen könnte im Auto-Suggest sowohl das nächstgelegene Haus auf der einen als auch auf der anderen Straße (also an Einmündungen etwa beide) vorgeschlagen werden. Optional könnte der die jeweils andere Straße unter »Tatort« als Kreuzungsbereich eingeblendet werden.

Also: 
![github wegli](https://user-images.githubusercontent.com/58035709/193802502-85a6cbd2-d805-4afd-a5f3-729cd5fc6e1f.png)

**Comment by phoet** [comment]
Eine solche Logik zu implementieren ist alles andere als trivial. Ich gehe nicht davon aus, dass dies umgesetzt wird.
