### ISSUE TITLE
Fehlermeldung unter notices

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#61]
![ED97674D-40CD-43E0-8711-C6DB6DBCEB08](https://user-images.githubusercontent.com/5426586/64905741-031f2500-d6dd-11e9-8943-20160115064e.jpeg)

Siehe Twitter Thread:
https://twitter.com/corin_corvus/status/1172793359225827329?s=21

Rückfragen am besten direkt an Corin @corincorvus

**Comment by phoet** [comment]
da war ein foto kaputt. wenn dann ein thumbnail daraus generiert werden soll macht es puff.

**Comment by phoet** [comment]
closed via https://github.com/weg-li/weg-li/commit/908f10dd69d625be7f43d0e2e42efbca3cf04153
