### ISSUE TITLE
Hochladen von Beweisfotos schlägt fehl. Error Status 0

### ISSUE THREAD

**Issue by DK4PN** [weg-li/weg-li#629]
Der Fehler tritt unter Firefox und Fennec(Android) beim Hochladen von Beweisfotos auf: Error Status 0. Es spielt keine Rolle, wie viele Bilder hinzugefügt werden.

**Comment by phoet** [comment]
Hallo @DK4PN <Error Status 0> ist ein client-side error, da könnne wir garnix machen.

**Comment by DK4PN** [comment]
Gibt es eine Lösung dafür? Mit anderen Browsern klappt es leider auch nicht.

**Comment by phoet** [comment]
Ja, zb Internet connection herstellen 🤷🏻

**Comment by DK4PN** [comment]
Sorry, aber das ist nicht der Fehler, Internetzugang funktioniert einwandfrei. Sowohl über mobile DAten als auch per WLAN, Fehler bleibt.

**Comment by phoet** [comment]
Bei diesem Fehler ist der Upload in die Google Cloud aus einem unbekannten Problem auf Client-Seite unterbrochen worden. Wir haben keine Möglichkeit das zu debuggen oder anderweitig Hilfestellung zu geben.
