### ISSUE TITLE
Umlaute in Kennzeichenerkennung

### ISSUE THREAD

**Issue by RDBloese** [weg-li/weg-li#632]
Die Kennzeichenerkennung scheitert stetig am erkennen eines "Ö"  (Bspw. in Göttinger Kennzeichen "GÖ")

**Comment by phoet** [comment]
Die Bilderkennung von Google mag Umlaute leider nicht so gerne... Vielleicht können wir aber mit einer normalisierung arbeiten und damit auch die Ös verwursten. 🤔

**Comment by phoet** [comment]
Es wird öfters mal ein kleines ö erkannt, das mag unser nummernschild erkenner nicht so gerne.
