### ISSUE TITLE
Kartenansicht: Auswahlzeitraum um Ansichten ergänzen: laufendes Jahr, Vorjahr

### ISSUE THREAD

**Issue by foss-** [weg-li/weg-li#636]
Ein Vergleich zwischen dem Vorjahr und laufendem Jahr auf der Kartenansicht würde mich sehr interessieren. Mir ist klar, dass die Auswahl übersichtlich gehalten werden soll. Fände es dennoch sehr informativ, diese Zeiträume zur Auswahl zu haben.

**Comment by phoet** [comment]
Vielleicht hat Heiko ja lust so etwas auf seiner Karte zu implementieren https://wege-frei.heikozelt.de/

**Comment by Heiko-Zelt** [comment]
> Vielleicht hat Heiko ja lust so etwas auf seiner Karte zu implementieren https://wege-frei.heikozelt.de/

Im Moment habe ich keine Zeit.
