### ISSUE TITLE
Kartenfilter Dropdown: Styling fehlt

### ISSUE THREAD

**Issue by chk1** [weg-li/weg-li#638]
Es geht um die Filter auf der Seite der Falschparker-Karte: https://www.weg.li/map 

Die Dropdowns verhalten sich anders als auf anderen Seiten:
- keine Begrenzung der Höhe des Dropdowns bei der Ortsauswahl, dieses erstreckt sich weit über die Bildschirmhöhe hinaus
- auf den Einträgen habe ich den Standard "Text markieren" Mauszeiger statt Link (`cursor: pointer`)
- schwarzer Hintergrund statt weiß

Auf der Statistiken-Seite (https://www.weg.li/stats -- diese Seite hat fälschlicherweise den Titel "Falschparker-Karte") wird eine ganz ähnliche Filterfunktion genutzt, auf diese Felder wird die `select2` Javascript Library angewendet - fehlt das möglicherweise bei den Filtern der Karte?

**Comment by phoet** [comment]
das sind einfach unterschiedliche dropdowns, eins ist bootstrap, das andere select2
