### ISSUE TITLE
Filter/Suche erweitern: Auf Stadt, PLZ, Adresse, Marke, Tatvorwurf, Hinweis

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#639]
Als Nutzer von Wegli möchte ich über Meldungen nach weiteren Kriterien suchen oder filtern können, um in meinen bearbeiteten Meldungen Dinge nachzuschauen oder um gezielt nur manche meiner offenen Meldungen zu bearbeiten. Außerdem möchte ich auch sehen können, wie oft ich den PKW mit Kennzeichen XY schon in Meldungen aufgenommen habe. Sonst muss ich durch die Pagierung abschätzen, wieviele Anzeigen es sind: (AnzahlSeiten  -1)  *MeldungenProSeite(25???)+ManuelleZählungLetzteSeite

Folgende Usescases sollte die Suche im Idealfall erfüllen:

- Gib mir alle Anzeigen aus der Lindenstraße => Suche erweitern auf Adresse
- Gib mir alle Gehwegparker => Suche erweitern auf Verstoß/Tatvorwurf
- Gib mir alle Audis =>  => Suche erweitern auf Marke
- Gib mir alle Anzeigen mit PLZ oder Stadt =>  => Suche erweitern auf PLZ / Ort
- Gib mir alle Anzeigen mit Hinweis XY.  => Suche erweitern auf Hinweise
- Gib mir alle Anzeigen mit Tatort XY.  => Suche erweitern auf Tatorte
- Anzeige der Anzahl der Funde, um z. B. anzuzeigen, wie oft Kennzeichen HH-HH 1234 bereits in Meldungen auftaucht.
- Weiterhin soll funktionieren: Suche nach Kennzeichen, auch in Kombination mit den anderen Filtern (Status, etc.) und Sortierungen

Bisher geht nur die Suche nach dem Kennzeichen.

**Comment by phoet** [comment]
siehe https://github.com/weg-li/weg-li/issues/636#issuecomment-1436768373

**Comment by RalphBike** [comment]
Das hilft mir nicht weiter. Ich möchte gezielt bearbeitete Anzeigen finden, um Details darin nachzuschauen. Oder um gezielt offene Anzeigen nach z. B. Adresse zu bearbeiten, aus meiner dreistelligen Zahl von offenen Meldungen.
Die Karte ist nett, aber dafür keine Lösung.

**Comment by phoet** [comment]
Vorerst wird es keine erweiterte Filterfunktion geben. Wer in seinen Anzeigen suchen möchte, der kann sie sich als CSV herunterladen und im Spreadsheet durchsuchen.
