### ISSUE TITLE
Faulty encoding in email 

### ISSUE THREAD

**Issue by wasnertobias** [weg-li/weg-li#652]
Falldaten > Verstoß gets rendered the following way:
> Verstoß: Sie parkten unberechtigt auf einem Parkplatz für elektrisch betriebene Fahrzeuge (Zeichen & lt;314/315& gt;) mit Zusatzzeichen.

(I had to add whitespaces after the &, because otherwise GitHub will render it correctly)

**Comment by phoet** [comment]
Where should i find this?

**Comment by phoet** [comment]
plz forward that email to us
