### ISSUE TITLE
Kennzeichenvorschläge sollten initial im Dropdown geladen werden

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#655]
Ausgangsszenario: Das Kennzeichen wurde nur teilweise erkannt. 
Verhalten bisher: Die Kennzeichenvorschlage im Dropdown werden aktuell nur geladen, nach dem ich getippt habe. 
Meine Erwartung: Die Kennzeichenvorschlage im Dropdown werden auch intial geladen, sobald ich es öffne.

Beispiel:
Das echte Kennzeichen ist z. B. AC AB 1910. Dieses Kennzeichen ist weg.li schon bekannt. Aus dem Foto wurde von weg.li "AB 1910" erkannt, ich kenne den Rest nicht und will schauen, ob ähnliche Kennezeichen schon in meinen Kundenpool sind. Also... muss ich irgendwas tippen und das wieder löschen. Diese beiden Schritte könnten entfallen, wenn mir das Dropdown initial das bekannte Kennzeichen anbieten würde.

**Comment by phoet** [comment]
Das kann Select2 leider nicht. Combo-Boxen sind fast so bescheiden wie Date-Picker...
