### ISSUE TITLE
Zuletzt geklickte Zeilen sichtbar machen (bei Mittelklick/öffnen im Hintergrundtab)

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#656]
Als Anwender von Wegli würde ich gerne aus der Meldungsübersicht /notices Meldungen per Mittelklick in Tabs im Hintergrund öffnen und dann erkennen können, welche Meldung ich zuletzt geklickt habe. Mit einfachen Links geht das über a:focus. Vielleicht geht das auch mit den Tabellenzeilen? Alternativ ginge auch eine Hervorhebung auf Link-Basis (statt Tabellenzeilen).

Begründung:
Ich bearbeite oft viele Meldungen in Folge, die ältesten offenen, bestimmte Kennzeichen oder sonst etwas. Sobald man scrollt, wird es leider schwer zu sehen, wo man zuletzt war. Dadurch habe ich entweder Lücken (nervt) oder doppelt geöffnete Links (nervt total).

**Comment by phoet** [comment]
Leider kann man Tabellenzeilen nicht komplett clickbar machen und dementsprechend auch nicht hovern.
