### ISSUE TITLE
Dropdown der Meldungen mobil nicht benutzbar

### ISSUE THREAD

**Issue by mploigt** [weg-li/weg-li#658]
Auf meinem iPhone 13 kann ich bei den DropDowns der Meldungen nur die oberen Einträge klicken. Das drop-down ist zu kurz und lässt sich nicht schollen, wenn man nur 1-2 Meldungen hat. 

![image](https://user-images.githubusercontent.com/433231/233842614-178771d1-1cc9-4ff4-85e5-5a29fdd42c9b.jpeg)

![image](https://user-images.githubusercontent.com/433231/233842620-c5044368-f260-4f5e-af7c-d7e2b7fb44c4.jpeg)

**Comment by phoet** [comment]
yo, das ist leider eine limitation des bootstrap dropdown im responsive table. deshalb ist unten schon extra viel padding bei einem leeren table.

**Comment by mploigt** [comment]
Ah, Du benutzt bootstrap 3. Stimmt, damit geht es dann nicht. Mit v4 könntest du  `boundary: window` setzen. 
Dann vielleicht `.table-padding`auf `180px` setzen, dann ist zumindest auch bei einem Eintrag das DropDown sichtbar.

**Comment by phoet** [comment]
Die Tabelle ist scrollbar und damit müsste auch der letzte Eintrag auftauchen.
