### ISSUE TITLE
Anmildung via Twitter funktioniert nicht

### ISSUE THREAD

**Issue by x0rzist** [weg-li/weg-li#667]
Wenn ich mich via Twitter anmelden möchte, bekomme ich die Fehlermeldung "Mist, da ist was schief gelaufen. (401 Unauthorized)".

Getestet unter Firefox auf dem PC und "Samsung Internet" auf Android.

**Comment by phoet** [comment]
Ja, leider https://twitter.com/weg_li/status/1653345707863027716

**Comment by carstenhag** [comment]
Wenn der Twitter-Login nicht weiter unterstützt wird, wäre es nice den Text zu ändern :)

![chrome_jXrvgb3MuV](https://github.com/weg-li/weg-li/assets/3776997/aa63b4fa-3c06-48da-a161-3a0dc9870c3b)

**Comment by phoet** [comment]
Der Twitter Login funktioniert, elon muss nur die abgeschalten Accounts wieder anknipsen...
