### ISSUE TITLE
Entfernen des Such-Filters sollte nur den Suchbegriff entfernen

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#668]
Hi, die Usability der Suche ist verwirrend und nicht erwartungskonform. Eventuell ist das ein Bug. 

Beim Entfernen eines Suchbegriffs über das X werden *alle* Filter- und Sortierungsparameter entfernt. 
Als Wegli-Nutzer würde ich erwarten, dass nur der Suchbegriff entfernt wird und die sonstigen Filter und Sortierungen erhalten bleiben.

Z.B. folgender Ablauf:

1) Übersichtsseite mit Sortierung und Filter nach Status:
https://www.weg.li/notices?filter%5Bstatus%5D=open&order%5Bcolumn%5D=date&order%5Bvalue%5D=ASC

2) Übersicht mit aktiver Suche:
https://www.weg.li/notices?order%5Bcolumn%5D=date&order%5Bvalue%5D=ASC&filter%5Bstatus%5D=open&search%5Bterm%5D=B+M&button=

3) Nach dem Remove des Suchbegriffs sind alle Sortierungen und Filter entfernt:
https://www.weg.li/notices?filter=remove&order=remove&search=remove

Sinnvoller und erwartungskonformer wäre ein Reset, das wieder zu 1) führt.
Aufgrund dem nicht erwartungskonformem Verhalten würde ich das als Bug betrachten.

**Comment by phoet** [comment]
<img width="284" alt="Bildschirmfoto 2023-05-22 um 10 54 13" src="https://github.com/weg-li/weg-li/assets/48745/58b66907-8b92-49de-a29e-03ddcedaf761">

dafür gibts nen anderen knopf

**Comment by RalphBike** [comment]
Okay, sehe ich jetzt auch. Dann ist aber die Anordnung immer noch recht verwirrend. Für mich zumindest.

**Comment by phoet** [comment]
eigentlich ist sie ziemlich logisch. andersherum wäre es verwirrend

**Comment by RalphBike** [comment]
Aktuell klebt der Button direkt am Suchfeld, was an sich komisch ist. Mach doch 20 Pixel dazwischen und alles ist gut.
