### ISSUE TITLE
Verstoß "Parken vor abgesenkter Fussgängerfurt" außerhalb 5m Bereich

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#67]
Leider liegen die Fussgängerfurten nicht immer im 5m-Bereich vom Kreuzeungsscheitelpunkt, so dass diese Owi hier nicht greift. Dies tritt auch bei sehr lang gezogenen Kreuzung mit einem großen Radius auf. Die Rechtsprechung ist hier möglicherweise nicht eindeutig, ob die Owi nach StVO §1 Absatz 2 verfolgt werden muss. Wobei die zuständigen Behörden Ordnungswidrigkeiten nach meinem Stand grundsätzlich keine einzige Owi verfolgen müssen, sondern immer nach eigenem Ermessen sein lassen können.

Möglicherweise ein Thema für einen späteren Zeitpunkt, falls hier noch die Rechtslage geklärt werden muss.

siehe auch http://www.verkehrsportal.de/board/index.php?showtopic=87585

**Comment by telefontuning** [comment]
Issue kann zu. Gemäß StVO §12 (3) 5 ist es verboten vor Bordsteinabsenkungen zu parken. 

https://www.gesetze-im-internet.de/stvo_2013/__12.html
