### ISSUE TITLE
Tatbestand Grünanlage verschwunden

### ISSUE THREAD

**Issue by Vakrehus** [weg-li/weg-li#672]
Man kann nicht mehr:

"Sie parkten auf einer öffentlichen Grünfläche, die nicht als Verkehrsfläche gilt."

auswählen. Gibt es diese nicht mehr im öffentlichen Katalog?

**Comment by phoet** [comment]
https://www.weg.li/charges/102118-sie-benutzten-verbotenerweise-den-grunstreifen

**Comment by Vakrehus** [comment]
Gemeint ist eine Grünfläche, kein Grünstreifen. Zwischen beiden gibt es einen großen Unterschied und der Tatbestand ist ein anderer.

https://www.bussgeld-info.de/parken-auf-gruenflaeche/#faq-parken-auf-einer-gruenflaeche-oder-einem-gruenstreifen

**Comment by phoet** [comment]
Welche TBNR hat dieser Tatbestand?
Am 10. Juni 2023, 21:22 +0200 schrieb Vakrehus ***@***.***>:

**Comment by Vakrehus** [comment]
```
  <Tatdaten>
    <Vorwurf>
      <Tatbestandsnummer>901400</Tatbestandsnummer>
      <VorwurfText>Parken auf einer Grünfläche</VorwurfText>
      <MitBehinderung>0</MitBehinderung>
    </Vorwurf>
  </Tatdaten>
```
Das konnte ich zumindest am 04.01.2023 auswählen.

**Comment by phoet** [comment]
Die TBNR 901400 ist nicht im BKAT enthalten. Vermutlich war dies ein lokaler Tatbestand einer Gemeinde, den wir irgendwann entfernt haben.

Grünflächen sind ohenhin nicht in den Parkvergehen zu finden, da jedwede Nutzung von Grünflächen untersagt ist. Wir haben diesen Tatbestand der einfachheit halber für unsere Zwecke umkategorisiert als Parkvergehen.
