### ISSUE TITLE
Künstlich verkürzte Zeiträume bewirken zu niedrige Strafen

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#674]
Weg.li verkürzt die Dauer des Tatvorwurfs künstlich. Dies führt dazu, dass vermutlich weniger hohe Strafen verhängt werden. Um beim Gehwegparken einen Punkt für "länger als 1 Stunde" zu erreichen, müsste ich Fotos mit einem Abstand von min. 3 h verwenden.

z. B.:

- Ich mache Fotos eines Gehwegparkers im Abstand von 2 Stunden: 16:30 und 18:30
- Weg.li bietet mir an: "Länger als 1 Stunde"
- In der Mail steht aber: Tatzeit: 20.06.2023 16:30, Zeitraum: 16:30 ~ 17:30
- Der Bussgeldkatalog sagt dazu: `112454 / Sie parkten verbotswidrig auf dem Gehweg. / 55 Euro, 0 Punkte`
- Und `112656 / Sie parkten länger als 1 Stunde verbotswidrig auf dem Gehweg / 70 Euro, 1 Punkt`

Folglich ist davon auszugehen, dass die Bußgeldstelle basierend auf "1.0 Stunden" nur die niedrigere Strafe verhängt, weil sie keinen Anlass hat, von "länger als 1 h" auszugehen. Einen Text, der über 1h hinausgeht, wäre mit Weg.li erst ab 3 h zu erreichen.

Dies sollte entweder dahingehend verändert werden, dass der reale Zeitraum genannt wird. Oder aber dass im Text klargemacht wird, dass es sich um einen Zeitraum von "länger als X" handelt und nicht "genau X" handelt. Dies betrifft alle Zeiträume, nicht nur die genannte 1h.

**Comment by RalphBike** [comment]
Mir ist zu dem auch nicht klar, was Uhrzeit-Tilde-Uhrzeit genau bedeuten soll. Sinnvoller wäre Doppeltilde-Uhrzeit-ndash-Uhrzeit. 

Insgesamt ist mir natürlich klar, dass das ganze ein sehr kleinliches Thema ist. Aber ich denke, dass wir hier sehr auf Details achten müssen, weil unser gegenüber das auch tut.

**Comment by phoet** [comment]
Der Meinung bin ich nicht, unser gegenüber tut was er möchte im Ermessen der Bearbeitung nach dem Opportunitätsprinzip.

**Comment by RalphBike** [comment]
Ja, die Bußgeldstellen nutzen ihre juristische Handlungsfreiheit innerhalb eines gesteckten rechtlichen Rahmens und tun, was sie für angemessen oder verhältnismäßig halten. Sprich im Zweifel machen sie weniger als erhofft. 

Sie haben aber nicht den Freiraum aus eigenem Ermessen mehr Zeit draufzuhauen. Damit ist die Hoffnung aussichtlos, dass aus einer Mail mit "eine Stunde" bei der Bearbeitung "länger als eine Stunde" wird. Ich gebe "mehr als 1h" (70 Euro, 1 Punkt) an und es kommt 1 Stunde (55 Euro, kein Punkt) dabei raus. Für mich verhält sich weg.li hier nicht erwartungskonform, also ist es ein Bug.

Betroffen davon ist jeder Tatbestand der eine zeitbezogene Steigerung hat, sowiegenerell die Unterscheidung zwischen Halten und Parken.

**Comment by hueller** [comment]
Ich kann der Argumentation von @RalphBike nur zustimmen und finde das aktuelle Verhalten von weg.li ebenfalls nicht erwartungskonform, insbesondere weil es eben diese zeitbezogenen Steigerungen im Bußgeldkatalog gibt.

Das Argument, dass das OA Anzeigen sowieso nur nach dem Opportunitätsprinzip bearbeitet, ändert nichts daran, dass die Zeitangaben in den Anzeigen erwartungskonform (für die weg.li User) sowie klar und eindeutig (für das OA) sein sollten.

**Comment by icemanmuc** [comment]
Ich stimmte @RalphBike vollkommen zu. Ich habe von meiner PI, die alle Wegli Anzeigen bearbeitet, einen Anruf erhalten mit dem freundlichen Hinweis, der Zeitraum müsse mind. 1 Stunde und 1 Minute betragen, ansonsten können sie "länger als 1 Stunde"-Tatbestände nicht übernehmen. IMHO spricht nichts dagegen alle möglichen Zeiträume jeweils um eine Minute zu erhöhen. Alternativ und noch flexibler wäre eine Option, den Zeitraum komplett manuell einzugeben/abzuändern.

**Comment by freundTech** [comment]
Wäre es eventuell möglich bis das implementiert ist die Voreingestellten Zeiträume alle um eine Minute zu verlängern?

Aktuell kommt bei Einstellung "über eine Stunde" z.B. `14:29~15:29` in der Meldung raus, was nicht über einer Stunde, sondern jediglich genau einer Stunde entspricht.

**Comment by icemanmuc** [comment]
> Wäre es eventuell möglich bis das implementiert ist die Voreingestellten Zeiträume alle um eine Minute zu verlängern?
> 
> Aktuell kommt bei Einstellung "über eine Stunde" z.B. `14:29~15:29` in der Meldung raus, was nicht über einer Stunde, sondern jediglich genau einer Stunde entspricht.

Gibt es einen Grund das nicht kurzfristig umzusetzen? Ich bin aufgrund des Fehlers häufig gezwungen einen milderen Tatbestand zu wählen, das ist schade.
