### ISSUE TITLE
Filter "offen" setzt sich zurück nach abschicken einer Meldung

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#68]
Wenn ich nach "offen" filtere und dann eine Meldung vervollständige und die Anzeige erstatt wird anschließend wieder die Meldungsübersicht ungefiltert angzeigt. Ich würde es schöner finden, wenn der filter "offen"immer noch gesetzt ist. Andernfalls muss man nach jeder abgeschickten Anzeige den Filter wieder auf "offen" setzen, bevor man die nächste Anzeige vervollständigen und abschicken kann.

**Comment by phoet** [comment]
ich würde empfehlen meldungen in einem neuen tab zu öffnen.

**Comment by telewolf** [comment]
habs ausprobiert. geht nicht schneller, als jedes mal den filter wieder auf "offen" zu setzen. deswegen bleibe ich erst mal bei dem weg.

**Comment by telewolf** [comment]
Da ich gerade mal wieder einen Masenupload durchführe: Von allen aktuellen issues / enhancements ist diese mein absoluter Top 1. Wenn man mehr Meldungen hat als auf einer Seite angezeigt werden, ist das unkomfortabel.

Ist das sehr aufwändig einzubauen?
