### ISSUE TITLE
Tatbestandsvorschlag wird nicht übernommen

### ISSUE THREAD

**Issue by jkfm** [weg-li/weg-li#684]
Hi,

ich habe das Problem mit den Vorschlägen zum Tatbestand angezeigt wird. Unter dem Textfeld ist der Vorschlag als TB-Nummer, wenn ich draufklicke passiert allerdings nichts. Ich könnte mir vorstellen, dass es kein Problem mit meinem Browser ist, da die Vorschläge bei den anderen Feldern funktionieren. 

LG
Johannes

**Comment by phoet** [comment]
funktioniert soweit ich das sehen kann
