### ISSUE TITLE
Klammern aus Tatbeständen entfernen

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#685]
In den Tatbestandsbeschreibungen sind diese Klammern aus dem BKAT enthalten. Deren Sinn erschließt sich mir im BKAT nicht, in Wegli sind sie fehl am Platze, sie landen sogar in den versandten E-Mails:

`Verstoß: Sie parkten auf einem unbeschilderten Radweg und behinderten +) dadurch Andere.`

Daher sollten alle Klammer-Artefakte wie `+)` und `*)` entfernt werden. Gefunden werden können Sie über:

https://www.weg.li/charges?classification=&term=%2B%29&button=

und

https://www.weg.li/charges?classification=&term=*%29&button=

**Comment by phoet** [comment]
Die texte der Tatbestände sind 1 zu 1 aus den Daten des BKAT. Wir fangen nach der Aufnahme der Tatbestände aus dem BKAT jetzt nicht an und ändern diese händisch wieder.
