### ISSUE TITLE
Tatbestände für Ladestationen ergänzen

### ISSUE THREAD

**Issue by jmichler** [weg-li/weg-li#688]
Ich denke es wäre hilfreich, wenn die Tatbestände für nicht-elektrofahrzeuge auf emoG Parkplätzen oder nicht-Laden auf "nur im Ladezustand" Parkplätzen ergänzt werden würden.

Siehe  unter anderem: https://www.gesetze-im-internet.de/bkatv_2013/anlage.html

Der Punkt 55a:
Unberechtigt auf einem Parkplatz für elektrisch betriebene Fahrzeuge geparkt (§ 12 Absatz 2 StVO; Zeichen 314, 315)

§ 42 Absatz 2 i. V. m. Anlage 3 lfd. Nr. 7 (Zeichen 314 mit Zusatzzeichen 1010-66) Spalte 3 Nummer 1, 3a, lfd. Nr. 10 (Zeichen 315 mit Zusatzzeichen 1010-66) Spalte 3 Nummer 1 Satz 2, Nummer 3a § 49 Absatz 3 Nummer 5

55 Euro

Es gibt aber auch noch andere Beschilderungen, da wäre sicher gut wenn die auch auswählbar wären. Alle Details : http://www.vzkat.de/2018/Elektrofahrzeuge/Elektrofahrzeuge-Ladestationen.htm

Ich denke die Funktion würde den Nutzerkreis massiv erhöhen.

**Comment by phoet** [comment]
<img width="894" alt="Bildschirmfoto 2023-09-13 um 22 11 15" src="https://github.com/weg-li/weg-li/assets/48745/581819dd-f005-4749-b9b1-13141df4091f">

🤷
