### ISSUE TITLE
Stand länger als... automatisch berechnen anhand ältestem und jüngstem Foto einer Meldung

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#69]
Ich würde es richtig schick finden, wenn die Dauer der Owi "Stand länger als 3 Minuten / 1 Stunde / 3 Stunden" anhand der Differenz der Uhrzeit zwischen dem jüngsten und dem ältesten Foto in einer Meldung berechnet wird. Also wenn das erste Foto kurz vor 08:00 gemacht wurde und das letzte um kurz nach 12:00 wird automatisch der Haken bei "Stand länger als 3 Stunden" gesetzt.

**Comment by telewolf** [comment]
Das scheint noch nicht zu funktionieren. Ich kann verschiedene Beispiele liefern:
z.B. https://www.weg-li.de/notices/8c023b3fbdf811e6d7e39d4f557c3bf2

Bei Bedarf gerne weitere oder neue Beispiele.

**Comment by phoet** [comment]
eine änderung geht gleich live, die das korrigieren sollte
