### ISSUE TITLE
Geolokationsdaten werden nicht aus Bildern übernommen

### ISSUE THREAD

**Issue by c-schmitz** [weg-li/weg-li#693]
Hallo, 
bei mir werden die Geolokationsdaten niemals aus meinen Bildern übernommen.
Wenn ich die Bilder inspiziere, z.B. über Google Fotos, sind diese aber vorhanden.
Ist das ein Bug oder mache ich etwas falsch?

**Comment by phoet** [comment]
Vermutlich löscht dein Browser oder FilePicker die Daten aus den Bildern vor dem Upload. Am besten eine andere Kamera-App, Browser oder Filepicker verwenden.

**Comment by phoet** [comment]
Aprospot, wenn die Bilder in Google Fotos sind, dann kannst Du ein Album per Link im Massen-Upload einlesen lassen.

**Comment by c-schmitz** [comment]
@phoet Warum wurde das schon geschlossen?

**Comment by phoet** [comment]
Die App kann nicht auslesen was nicht da ist.

<img width="906" alt="Bildschirmfoto 2023-09-29 um 13 07 33" src="https://github.com/weg-li/weg-li/assets/48745/bf9ec593-6d7f-4e3e-b53d-16a546a25acf">

**Comment by c-schmitz** [comment]
Alles klar. Ich denke ich hab das Problem gefunden. 
Als Referenz für andere Leute mit dem gleichen Problem:

In den Einstellungen von Google Fotos gibt es folgenden Option:

![image](https://github.com/weg-li/weg-li/assets/1364282/307051f3-8154-4faa-a81e-bac6e3f719a9)

Diese muss aktiviert werden, dann klappt's auch mit dem Sharing.
