### ISSUE TITLE
Remove .env file

### ISSUE THREAD

**Issue by levino** [weg-li/weg-li#694]
There is 
https://github.com/weg-li/weg-li/blob/9e348fb8d8ff412e0ba169409b8d952a868822f0/.env#L1-L6
I hope these secrets are not valid any more. The file however should be removed from version control, I guess.

**Comment by phoet** [comment]
Those are valid app credentials for local development.

**Comment by levino** [comment]
Maybe also https://www.dotenv.org/security/ could be interesting...

**Comment by phoet** [comment]
Well, I disagree

**Comment by levino** [comment]
Okay. I accept. I suggest to keep this issue closed then, if that is your decision. As a final remark I would like to highlight the recommendation of the [dotenv project against committing .env files](https://github.com/motdotla/dotenv#should-i-commit-my-env-file). Nevertheless this is not a critical issue as of now and for me the matter can be closed. Since you reopened the issue (and I do not really understand why), I let you the honors to close it again, if you want to.
