### ISSUE TITLE
cannot run migrations

### ISSUE THREAD

**Issue by levino** [weg-li/weg-li#697]
When trying to run the migrations, I get 
```bash
== 20230309102559 AddChargeRelation: migrating ================================
-- change_table(:notices)
   -> 0.0646s
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

uninitialized constant Charge::UPDATED_CHARGES

        Charge::UPDATED_CHARGES.each do |_, charge, tbnr_standard, tbnr_hinder, _, _|
              ^^^^^^^^^^^^^^^^^
```
I created https://github.com/weg-li/weg-li/pull/696 to show the error here in a PR and discuss a potential fix. Unfortunately the checks do not run yet, please someone approve them to run. Maybe it is also not necessary to do so and one can run all the checks for all the PRs without approval. I dunno. 

Please also keep in mind that the PR is a draft and I will remove some of the changes later, it is mostly about the failing migrations and how to fix these.

**Comment by phoet** [comment]
Why exactly are you trying to run migrations? The db:prepare task should load the schema just fine

**Comment by levino** [comment]
I am simply following the set up instructions. Running `bin/setup`. Is that wrong?

**Comment by levino** [comment]
Actually I am running [`bin/rails db:prepare`](https://github.com/weg-li/weg-li/pull/696/files#diff-d0777657fa3fd81d23aaf7273e58aee453b04e67882517900c56daeef9b3e4c1R98). Should that not be okay?

**Comment by phoet** [comment]
CI does a db:setup on every run, there should not be an issue with migrations as they are applied through the schema already?

**Comment by phoet** [comment]
(mostly guessing here as I'm not near a PC this week)

**Comment by levino** [comment]
No. This gets run:
https://github.com/weg-li/weg-li/blob/9e348fb8d8ff412e0ba169409b8d952a868822f0/.github/workflows/build.yaml#L60
I tried: I can run the tests and the test migrations (if there are any) fine.

**Comment by levino** [comment]
> (mostly guessing here as I'm not near a PC this week)

That is unfortunate, but okay. I can wait. Are you the only maintainer of this project? It would be nice if you could still merge some of my PRs in order to unblock me, but I also understand, if you want to take the time to carefully check them once you have a proper setup again.

**Comment by phoet** [comment]
Still don't understand what the issue could be. It should be completely fine to just delete all migrations and run from the schema file.
