### ISSUE TITLE
Massen-Upload: Mülleimer ergänzen

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#70]
"Beim Massen-Uploads / gruppieren" wäre es toll wenn man dort einzelne Bilder wieder rauswerfen kann.

**Comment by phoet** [comment]
das gibt es schon, ist aber ausplatzgründen im popover versteckt

<img width="616" alt="Screen Shot 2019-09-25 at 16 10 46" src="https://user-images.githubusercontent.com/48745/65608845-1c628400-dfaf-11e9-9b40-d2f890bfacd8.png">

**Comment by phoet** [comment]
da hats noch irgendwo puff gemacht, sollte gleich behoben sein.
