### ISSUE TITLE
explain and improve imagine folder

### ISSUE THREAD

**Issue by levino** [weg-li/weg-li#700]
I do not understand the [`imagine`](https://github.com/weg-li/weg-li/tree/9e348fb8d8ff412e0ba169409b8d952a868822f0/imagine) package. The way it is located in the app is unusual and the code does not adhere to the eslint rules. What is the purpose of this package? Maybe one could add a Readme for it.

Having such subpackages in the repo is possible, but one should use a monorepo / workspace setup with lerna, yarn or even better `bun`. I can help fix this, if I know what the package is about.

**Comment by phoet** [comment]
This is a cloud flare worker, I think it's documented in the single js executable. Please do not change anything here, its tied to the js runtime Version of the worker.

**Comment by levino** [comment]
I understand your concern, that changes that I make to this might break things. However I always work under the premise that changes cannot break functionality. So as long as functionality is retained, changes should be okay, should they not?

Since the code has no dependencies and just one devDependency, namely prettier in an outdated version, I would assume it is safe to remove the [`package.json`](https://github.com/weg-li/weg-li/blob/9e348fb8d8ff412e0ba169409b8d952a868822f0/imagine/package.json) and fix the code style issues in the file by including it in the linting step and autofix all issues. Also one would have to provide some globals for eslint which seem to be available in the cloudflare worker.

Would that be okay with you? How do you check that the code still works? How is this code deployed? It does not get deployed from CI as far as I can tell. Does cloudflare trigger a redeploy on merge to master? Or do you deploy by hand?

**Comment by phoet** [comment]
At the time of writing testing could only be done through a staging app, much like with other cloud functions. I don't know weather the situation has improved as of now. 

As long as formatting is applied that should be ok, since code runs on a somewhat opaque js runtime anything but formatting is not ok, including chances to the package.json

**Comment by phoet** [comment]
The reasonable thing to do would be to put this into another repo, but I was too lazy to do that

**Comment by levino** [comment]
I do not think that it is necessary or better to put it in its own repo. Creates a lot of overhead. The code should also be [migrated](https://developers.cloudflare.com/workers/learning/migrate-to-module-workers/) to the new format which will improve readability a lot. But whatever I do, please explain how you deploy this code.

**Comment by levino** [comment]
I am a big fan of monorepos and this is a good example for why they make sense. The code should stay here. However I am also a big fan of CD (deploying automatically from any merge to main/master (I prefer the first one since BLM)). I suggest to eventually move to that. I can help with it, but would probably need more info, even access rights. Lets see how this progresses here :)

**Comment by phoet** [comment]
This is a perfect example of code that does not fit in a monorepo

**Comment by levino** [comment]
I disagree :) But as I said, it is not important. Closing.
