### ISSUE TITLE
Abschalten der Kennzeichenerkennung

### ISSUE THREAD

**Issue by carstenhag** [weg-li/weg-li#701]
Zumindest bei meinen Bildern ist die korrekte Erkennungsrate der Kennzeichen gegen null. Beim Hersteller und der Farbe ist es 50:50.

Natürlich könnte man eine der neuen AI-Technologien verwenden, aber ich weiß nicht, ob das notwendig ist. die 5 Zeichen einzutippen ist auch nicht das Problem, finde ich. Jedes Mal was falsche zu sehen ist für mich zumindest frustrierender - auch wenn ich natürlich weiß, dass es gut gemeint ist :D

**Comment by carstenhag** [comment]
Schande über mein Haupt, es ist bereits als Nutzer-Setting abschaltbar. 
![chrome_dL6fjItEXZ](https://github.com/weg-li/weg-li/assets/3776997/d3852ca0-1b15-418f-8286-9ee7996beba4)

**Comment by phoet** [comment]
Natürlich kann man die Erkennung deaktivieren, das erscheint mir jetzt allerdings die schlechteste aller Optionen. Ich habe schon lange keine Beschwerden mehr zur Kennzeichen Erkennung gehört. Muss man sich mal deine Beweisfotos ansehen.

**Comment by carstenhag** [comment]
Ironischerweise hat die Erkennung jetzt auch 2x funktioniert. Egal, ich lass es aus 😄

**Comment by phoet** [comment]
Die Erkennung ist linear zur Qualität der Beweisfotos
