### ISSUE TITLE
allow workflow runs for more people

### ISSUE THREAD

**Issue by levino** [weg-li/weg-li#704]
It should be unproblematic to allow workflow runs for everyone with an established github account. Secrets will not be available in these runs anyhow. If somebody abuses this, settings can be changed back.
![Screenshot from 2023-10-12 12-41-23](https://github.com/weg-li/weg-li/assets/1150767/c694a854-8517-406c-b917-b6983d01cae8)

**Comment by levino** [comment]
Please @phoet do this, it is kinda annoying / discouraging that I have to recreate every PR in my fork in order to see if the workflows run correctly.

**Comment by phoet** [comment]
Yeah, this is some GitHub BS they introduced in order to minimize crypto miners running on their infrastructure...
