### ISSUE TITLE
München KVR Hinweis ist falsch

### ISSUE THREAD

**Issue by bmikaili** [weg-li/weg-li#709]
Der Hinweis "In München sind ausserhalb des Mittleren Rings die örtlichen [Polizei-Inspektionen](https://www.polizei.bayern.de/?uigmd=m%C3%BCnchen&gdts=162000001&gmds=162000&gmdklartext=80331%20M%C3%BCnchen) anstelle des [KVR](http://www.muenchen.de/dienstleistungsfinder/muenchen/1073669/) zuständig, deren Zuständigkeit man auf [dieser Karte](https://umap.openstreetmap.fr/de/map/unbenannte-karte_422905#14/48.1444/11.5718) findet." 

Ist so nicht richtig. Das KVR hat mich mehrmals darauf hingeweisen, dass zb im Distrikt Maxvorstadt die Polizeiinspektion 12 zuständig ist.

**Comment by phoet** [comment]
Gut, wie sollte denn dieser Hinweis deiner Meinung nach umformuliert werden?

**Comment by bmikaili** [comment]
> Gut, wie sollte denn dieser Hinweis deiner Meinung nach umformuliert werden?

Sorry, hätte ich ergänzen sollen. Dass man auf die Karte schauen soll, und zwar auch **im** mittleren Ring.
