### ISSUE TITLE
Doubletten-Erkennung (schutz vor versehentlicher doppelmeldung der selben owi)

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#71]
neue meldung:
https://www.weg-li.de/notices/09680a3e744b660acb65d1a169e34770

die selben beiden fotos wurden bereits in dieser älteren meldung verwendet:
https://www.weg-li.de/notices/3152f0a9a1f6330029508e49a81d5670

 eine warnung wurde nicht angezeigt.

**Comment by telewolf** [comment]
Verbesserungsidee: Doubletten-Erkennung auch anhand folgendem Merkmal. Wenn ein Kennzeichen am selben Tat-Datum 2 Mal angezeigt wird. In obigen Fall wäre diese Warnung gegriffen, weil der Tat-Tag in beiden Meldungen der selbe ist.

**Comment by phoet** [comment]
die erkennung erfolg anhand des dateinamens, dieser ist nicht gleich:

```
=> [#<ActiveStorage::Filename:0x0000559fce8fa390 @filename="7A697A73-BC83-4778-AFE3-A9CCB9D7E10B.jpeg">, #<ActiveStorage::Filename:0x0000559fce8ffed0 @filename="2B68E7A2-DB55-44DE-B76B-234DF95D87B1.jpeg">]
irb(main):002:0> Notice.from_param('09680a3e744b660acb65d1a169e34770').photos.map(&:filename)
=> [#<ActiveStorage::Filename:0x0000559fce913278 @filename="1821D76A-1BAE-4DEE-868D-0B2FFFAFB9BB.jpeg">, #<ActiveStorage::Filename:0x0000559fce910410 @filename="71836F02-0FFA-4BC7-9EEF-E0897255700B.jpeg">]
```

ggf handelt es sich um eine bearbeitete variante?

**Comment by telewolf** [comment]
Ich habe die Dateien vom iPhone auf das iPad übertragen. Vermutlich hat sich dabei der Dateiname geändert.

Das aufnehmen unterwegs ist mit dem iPhone praktisch. Der Massenupload auf dem iPhone war immer wieder abgebrochen. Zusätzlich ist das bearbeiten der Meldungen auf dem iPad grundsätzlich angenehmer.

Was hältst Du von obigen Vorschlag "doubletten-erkennung anhand von Kennzeichen und Tag"?

**Comment by phoet** [comment]
ja, guter vorschlag

<img width="1164" alt="Screen Shot 2019-09-25 at 16 01 30" src="https://user-images.githubusercontent.com/48745/65608066-eb358400-dfad-11e9-8c46-999527bb7961.png">

**Comment by phoet** [comment]
closed by https://github.com/weg-li/weg-li/commit/2936760a48256122f3572de91e7fba3192962d0e

**Comment by telewolf** [comment]
Sehr schick. Und super schnell. Danke!

**Comment by telewolf** [comment]
Ich habe es gerade nicht ausprobiert, aber haben wir hier genau wie bei Issue 49 die Situation dass die Warnung nur dann kommt wenn das Kennzeichen automatisch erkannt wurde, aber nicht wenn das Kennzeichen per Hand korrigiert wurde?
