### ISSUE TITLE
Vorschlag: Option Ende des Tatzeitraums manuell zu bestimmen hinzufügen

### ISSUE THREAD

**Issue by icemanmuc** [weg-li/weg-li#718]
Die Dropdown-Optionen unter "Zeitraum" sind IMHO zu sehr limitiert und es ergibt Sinn entweder:

1. diese stark zu erweitern 
2. eine manuelle Endzeitangabe zu ermöglichen
3. Punkt 2 + die exakten Zeiten von den Aufnahmen zu übernehmen (favorisierte Variante)

### Gründe
Meine lokale PI (vermutlich auch andere) ahndet laut eigener Aussage z. B. Vergehen im eingeschränkten Haltverbot erst ab ca. 20 Minuten, ich muss somit mind. 30 Minuten beobachten, da die darunterliegende Option "15 Minuten" nicht ausreicht.
 
Zudem wäre es eine Lösung oder zumindest ein Workaround für #674 .
Ein Tatbestand mit "länger als 1 Stunde" kann aktuell aufgrund des Bugs nur bei einem Beobachtungszeitraum von mind. 3 Stunden ausgewählt werden.

**Comment by RalphBike** [comment]
IMHO solte auch der Anfangszeitpunkt flexibler gehandhabt werden. Ich finde jedenfalls immer mehr Fahrzeug von "Miles", die diese praktische digitale Parkscheibe haben. 

Z.B. Ich finde einen Falschparker mit Parkscheibe. Das Auto steht seit mehr als 10 h dort. Ich kann aber nur "min. 3h angeben" und die liegen dann in der Zukunft, was das Portal nicht zulässt. Und was natürlich auch potentiell eine Falschaussage wäre.

**Comment by icemanmuc** [comment]
> IMHO solte auch der Anfangszeitpunkt flexibler gehandhabt werden. 

@RalphBike Der Anfangszeitpunkt kann beliebig geändert werden, Datum sowie Uhrzeit. Wie soll das noch flexibler werden? Oder verstehe ich etwas falsch?
