### ISSUE TITLE
Meldung duplizieren

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#72]
Das Beweisfoto soll ja möglichst so sein, dass der Tatvorwurf darauf klar erkennbar ist. Manchmal lässt sich dadurch nicht vermeiden, dass ein zweites Fahrzeug auf dem Bild mit drauf ist. Wenn dieses zweite Fahrzeug ebenfalls eine Owi erfüllt, wäre es toll wenn man die Meldung kopieren kann, damit man die Fotos, den Standort und den Vorwurf ein Mal für Kennzeichen A und ein Mal für Kennzeichen B verwenden kann.

Siehe z.B. https://www.weg-li.de/notices/8137cddbe61e17273a45e46cb08d0cfd 
(Zwei Fahrzeuge die beide im 5m-Kreuzungsbereich parken)

**Comment by phoet** [comment]
das erscheint mir zu kompliziert. ich würde das foto stattdessen nochmal hochladen.

**Comment by phoet** [comment]
in dem zuge ggf mal die action buttons umbauen zu einem dropdown menü

**Comment by telewolf** [comment]
Kann das Issue zu?

**Comment by phoet** [comment]
ich habe gerade die buttons zu dropdowns umgebaut, ich glaube es ist nun relativ einfach möglich das einzubauen ohne die ux schlechter zu machen.

**Comment by phoet** [comment]
geht gleich live
