### ISSUE TITLE
Marke "Fisker" fehlt

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#720]
Hi, überflüssigerweise gibt es schon wieder eine neue Automarke: Fisker.

Mir ist gerade der erste "Ocean" von Fisker begegnet. Stand auf einer Grünfläche :-/

Ist zwar erst eingeführt, aber der Hersteller will 65k Bestellungen oder Reservierungen für seinen Stadtpanzer haben.

https://de.wikipedia.org/wiki/Fisker_Inc.
https://vision-mobility.de/news/fisker-ocean-kommt-2023-244334.html

**Comment by phoet** [comment]
Ich arbeite gerade an einer besseren Abbildung der Marken auf weg.li Man kann sie sich jetzt schon einmal ansehen und es wird einen ähnlichen Prozess zum vorschlagen geben wie bei den Bezirken https://www.weg.li/brands?page=4

**Comment by winkmal** [comment]
> Ich arbeite gerade an einer besseren Abbildung der Marken auf weg.li Man kann sie sich jetzt schon einmal ansehen und es wird einen ähnlichen Prozess zum vorschlagen geben wie bei den Bezirken https://www.weg.li/brands?page=4

Komisch, dort erscheint z.B. die Marke "Ora", welche mir jedoch nicht im Drop-Down-Menü angezeigt wird...
Außerdem fehlt bei den Lkw [Fuso](https://de.wikipedia.org/wiki/Mitsubishi_Fuso_Truck_and_Bus_Corporation)
