### ISSUE TITLE
Zeitraum in PDF unvollständig falls Start- und Enddatum nicht identisch

### ISSUE THREAD

**Issue by icemanmuc** [weg-li/weg-li#724]
Seit das Tatzeitende festgelegt werden kann (yayyy!!) ist die generierte PDF-Datei inkorrekt, sobald das Tatzeitende zB erst am Folgetag ist.

Unter notices/ werden Tatzeitstart und Tatzeitende korrekt dargestellt:
![screenshot_notices](https://github.com/weg-li/weg-li/assets/16356555/a0726a56-60dd-48db-abab-b844a2475fbc)

In der generierten PDF falsch:
![screenshot_pdf](https://github.com/weg-li/weg-li/assets/16356555/1b2a0e77-213a-465f-bdf8-1672f3dc5c3f)

Mögliche Lösung:
In der PDF-Datei in der Zeile "Zeitraum" nicht nur Start- und Enduhrzeit, sondern die kompletten Datetimes, also inkl. des jeweiligen Datums anzeigen. Das Beispiel oben würde demnach folgenden Text zeigen:
```
Tatzeit: 05.01.2024 16:30
Zeitraum: 05.01.2024 16:30 bis 07.01.2024 11:54
```

**Comment by phoet** [comment]
Schau ich mal
