### ISSUE TITLE
Doppelter Name für Stadt Essen

### ISSUE THREAD

**Issue by bezin** [weg-li/weg-li#727]
Hallo zusammen, 

mir ist aufgefallen, dass bei der Karte im Filtermenü sowohl `Essen` als auch `Essen, Ruhr` zur Auswahl stehen. Beide zentrieren die Karte auf die Stadt Essen im Ruhrgebiet, aber Marker werden nur bei der Auswahl von `Essen, Ruhr` angezeigt. Bei der Auswahl von `Essen` scheinen keine Marker hinterlegt zu sein. 

Cheers

**Comment by phoet** [comment]
Alle bezirke mit der E-Mail Adresse  	verkehrsueberwachung@ordnungsamt.essen.de heißen jetzt nur noch `Essen`
