### ISSUE TITLE
Vergrößerung des Empfängerkreis bei Tatbeständen in Feuerwehrzufahrten und Feuerwehrbewegungszonen

### ISSUE THREAD

**Issue by Maltis** [weg-li/weg-li#734]
Hallo, 

es wäre wirklich toll, wenn sich die Möglichkeit realisieren ließe, bei Verstößen in Bereich von Feuerwehrzufahrten auch die jeweilige Brandschutzdienststelle der Stadt/Kreis informell per Mail zu benachrichtigen. z.B. durch optionale Checkbox bei den entsprechenden Tatbeständen.
Diese Verstöße werden bei den Feuerwehren dokumentiert und lösen idR weitere Maßnahmen aus wie z.B. Kennzeichnung von Sperrflächen oder Poller um die Feuerwehrzufahrten, Anleiterflächen und Feuerwehrbewegungszonen frei zu halten. 

Nachteil: Die E-Mailadressen der jeweiligen Brandschutzdienststellen müssten noch gesammelt und den Kommunen zugeordnet werden.

**Comment by phoet** [comment]
Wir könnten das für einen Bezirk mal exemplarisch ausprobieren. Dafür benötige ich die entsprechenden Daten.

**Comment by Maltis** [comment]
Ich hab mal für 5 größere Städte in NRW entsprechende Kontaktdaten der zuständigen Dienststellen rausgesucht: 

Düsseldorf: vb-feuerwehr@duesseldorf.de
Köln: 37-Gefahrenvorbeugung.feuerwehr@stadt-koeln.de
Essen: vb@feuerwehr.essen.de
Duisburg: brandverhuetungsschauen@feuerwehr.duisburg.de
Aachen: FB37.400@mail.aachen.de

**Comment by phoet** [comment]
Die Kontaktdaten raussuchen ist schön und gut. Hast Du einen direkten Kontakt zu einer Dienststelle, damit wir überprüfen können wie das funktioniert? Was soll in der E-Mail stehen? Bei welchen Vergehen sollen wir die E-Mail versenden? Wer soll Ansprechpartner dafür sein (Wir werden dafür keinen Support machen)?
