### ISSUE TITLE
Fotos vor Upload verkleinern

### ISSUE THREAD

**Issue by jkfm** [weg-li/weg-li#74]
Wäre es möglich, Fotos vor dem Upload clientseitig zu verkleinern? 
Meine Handykamera kann nur sehr große oder sehr kleine Auflösungen speichern, so dass ich immer 3MB hochladen muss.

**Comment by phoet** [comment]
es gäbe die möglichkeit, dass du auf deinem handy das foto zunächst bearbeitest. ein vorverarbeitung im browser ist mir nicht bekannt.

**Comment by jkfm** [comment]
An so etwas dachte ich: https://github.com/nodeca/pica

Aber dein Vorschlag stimmt natürlich auch ;-)

**Comment by phoet** [comment]
@jkfm das sieht nicht schlecht aus. ist natürlich die frage wie gut mobile browser das hinbekommen...
