### ISSUE TITLE
🐘 Wegliphant, ein API-Client für weg.li 🚲💨 in PHP

### ISSUE THREAD

**Issue by Art4** [weg-li/weg-li#740]
Hallo zusammen, 👋 

erstmal vielen Dank für dieses tolle Projekt. Leider kann ich kein Ruby und kann daher nur wenig an diesem Projekt mithelfen. Da ich aber PHP kann und gesehen habe, dass es eine API gibt, hatte ich eine Idee.

Ich möchte euch gerne **🐘 Wegliphant** vorstellen, ein API-Client für weg.li 🚲💨, geschrieben in PHP.

https://github.com/Art4/wegliphant

Mit 🐘 Wegliphant kann die Weg.li API einfacher in PHP-basierten Web-Applicationen oder Webseiten-Systemen wie WordPress, Symfony, Joomla oder Typo3 verwendet werden.

Im Moment (Release 0.1) wird nur der Endpoint `/districts.json` unterstützt, aber ich werde Stück für Stück alle weiteren Daten-Schnittstellen, sowie die personalisierte API implementieren.

**Update:** Seit Version 0.3 können auch die personalisierten API-Endpoints angesprochen werden.

**Comment by phoet** [comment]
Hi,

dir ist schon klar, dass Du einen API-Client aus mittels Swagger generieren kannst?

https://www.weg.li/api-docs/index.html

**Comment by phoet** [comment]
Wäre das dann nicht sinnvoller, diese hinzuzufügen?

**Comment by Art4** [comment]
"Das eine tun, aber das andere nicht lassen." wie ein deutscher Podcaster so gerne sagt. Wenn du mir sagst, wo ich die OpenAPI Spec anpassen kann, kann ich da vielleicht mithelfen. Und trotzdem gibt es dann den PHP-Client für die Entwickler, die sich den Client nicht generieren können, weitere Features wie Filter haben möchte, oder einfach nicht mit der generierten Code-Qualität zufrieden sind.

**Comment by phoet** [comment]
Das hier ist die spec für notices https://github.com/weg-li/weg-li/blob/master/app/controllers/api/notices_controller.rb

**Comment by Art4** [comment]
Vielen Dank. Ich werde sehen, was ich tun kann. Vielleicht werde ich ja doch noch warm mit Ruby.

**Comment by phoet** [comment]
FYI beide Endpunkte sind deprecated und ich behalte mir vor diese zukünftig zu entfernen. Die Daten sollten stattdessen über die API Endpunkte geladen werden https://www.weg.li/api-docs/index.html

**Comment by Art4** [comment]
Danke für die Info. Ideal wäre eine Versionierung der API, die im Moment auf 1.0.0 steht.

**Comment by phoet** [comment]
Wofür brauchst Du die Versionierung?

**Comment by Art4** [comment]
Er erleichtert die Kommunikation mit den Benutzern der API. Da ich einen API-Client baue, trifft der obere Post also genau auf mich zu. Für die zukünftige Entwicklung brauche ich nur auf die API-Version schauen, ob ich den Client anpassen muss. Und du brauchst nicht mehr daran zu denken, eventuelle andere Client-Entwickler über die Änderungen zu informieren, wie du es eben dankenswerterweise getan hast. Du setzt nur [hier die API-Version hoch](https://github.com/weg-li/weg-li/blob/master/app/controllers/apidocs_controller.rb#L15) und bist fertig. Ich suche mir dann selber die Änderungen an der API raus, und ob ich meinen Client anpassen muss.

Und ja, die veralteten Endpoints sind noch nicht Teil der Swagger-API, daher wäre das auch kein Breakin Change. :+1: 

Ich kann zu dem Thema das Buch [Build APIs you wont hate](https://apisyouwonthate.com/books/build-apis-you-wont-hate/) von Phil Sturgeon empfehlen. Der Autor hat ziemlich viel APIs und Tools zu OpenAPI a.k.a. "Swagger 3.0" geschrieben.

**Comment by Art4** [comment]
> Die API ist größtenteils work in progress und es wird auch keine konkrete API-Versionierung geben solange es keinen relevanten 3rd party client gibt.

Das verstehe ich und ergibt dann leider ein Henne-Ei-Problem. Ohne Versionierung ist es schwierig, einen relevanten 3rd Party client zu erstellen, wenn man durch die rolling releases keine verlässliche API hat. Denn ohne Versionierung (und sunsetting von deprecated APIs) bedeutet das, dass der Client jederzeit kaputt gehen kann. Das ist nicht sehr attraktiv, um sich dauerhaft darauf zu verlassen.

Weil weg.li auch keine Release-Tags hat, macht es alles etwas komplizierter. Denn ich kann als Versionierung nur noch einen Git Commit verwenden, aber kann selbst da nicht sicher sein, ob der Produktion-Server gerade auf diesem Commit läuft.

Eine Versionierung direkt von weg.li einzuführen macht bei einem rolling release Prozess wenig Sinn, daher der Vorschlag zur Versionierung der API. Das heißt für dich, dass du die API-Version nur hochsetzen musst, wenn du eine Änderung an den relevaten API-Controllern durchführst. Für API-Clienst bedeutet das direkt eine Sicherheit, weil ich jetzt auf eine bestimmte API-Version setzen kann und Änderungen viel leichter mitbekommen kann und z.B. nur bei einer neuen API-Version den Client neu generieren kann.

**Comment by phoet** [comment]
Es gibt keinen relevanten 3rd party client, weil es keine App (mehr) gibt.

**Comment by Art4** [comment]
> Es gibt keinen relevanten 3rd party client, weil es keine App (mehr) gibt.

Wenn du damit die [iOS](https://github.com/weg-li/weg-li-ios) und [Android](https://github.com/weg-li/weg-li-android)-Apps meinst, die sich in deinem direktem Einflussbereich befinden, dann sind das 1st Party clients. Aber das ist jetzt Wortklauberei.

> Doch, es läuft immer auf dem letzten commit `<!-- served Revision 203f5be779307bde1a017b0c9c23a70dc07c0db0 by Puma-6.4.2 The Eagle of Durango Ruby: 3.2.3 on Rails 7.1.3.2 -->`

Das ist gut zu wissen, ändert aber nichts daran, dass der Versionierungsabgleich über den Commit-Hash sehr auswendig ist. Ich muss für beide Hash den Commit-Zeitpunkt aus dem Github-Repository ermitteln und dann vergleichen, ob zwischen diesen Commits Änderungen an der API gemacht wurden. Wenn die API-Version hochgesetzt wird, brauche ich nur den `info.version`-Wert  aus der [aktuellen Swagger-Datei](https://www.weg.li/apidocs.json) zu ermitteln und kann die Versionsnummern vergleichen.

Wir reden hier wirklich nur von einer Änderung an einer Zeile Code. Ich habe dir dafür auch den PR #750 erstellt.
