### ISSUE TITLE
Feature request: add a help text/clarification about what "active user" means on the statistics page

### ISSUE THREAD

**Issue by stepo2** [weg-li/weg-li#742]
I wonder what "active" on https://www.weg.li/stats?display=active actually means.

When does a user count as "active"? Does he had to report a parking delict in the selected timespan? Or In the last X days? Or have minimum of reports ever/in X weeks? When does he lose his "active" state again: after fixed time without report, never after reporting once, when reaching a specific report/time ratio?

The statistics page should have a small sentence clarifying this.

**Comment by phoet** [comment]
In contrast to passive users, active users have reported something. There is no complex logic to this that would need explaining.

**Comment by phoet** [comment]
I reworded it to "Aktive Melder" like on the Homepage.
