### ISSUE TITLE
Nicht alle Tatbestände auswählbar

### ISSUE THREAD

**Issue by manu-cyber** [weg-li/weg-li#744]
Ich kann beim Bearbeiten einer Meldung den Tatbestand [TBNR 102100](https://www.weg.li/charges/102100-sie-benutzten-vorschriftswidrig-den-gehweg) nicht auswählen. Sollte dies möglich sein? Falls ja, gibt es hier wahrscheinlich einen Bug. Falls nein, ist diese Einschränkung unzureichend oder gar nicht kommuniziert.

..oder ich benutze es einfach nur nicht richtig, dann würde ich mich über Hinweise freuen ;)

**Comment by phoet** [comment]
Es sind nur Verstöße im ruhenden Verkehr auswählbar (Park & Halteverstöße)

**Comment by manu-cyber** [comment]
Ach schade, ich hab so ein schönes Foto gemacht ^^ Danke für die Info :)

**Comment by Art4** [comment]
Nur zur Info: Für den fließenden Verkehr ist die Polizei zuständig, nicht die Ordnungsämter.
