### ISSUE TITLE
Statistics bug: raise ("Anstieg") bars in monthly grouping are wrong

### ISSUE THREAD

**Issue by stepo2** [weg-li/weg-li#746]
If I for example open monthly over one year statistics (https://www.weg.li/stats?display=user&interval=1+month&since=48), then the last two bars say "february 17th" and "march 17th", which both clearly passed. Yet, the march raise bar does not nearly show the sum of the daily raises. The total number (the dot-line) seems to be correct. The "Anstieg" (raise) should be like ~11.000, but it shows only ~1.000.

**Comment by phoet** [comment]
That is how postgres `generate_series` query works. I dont intend to change any of it.
