### ISSUE TITLE
JSON-Download scheitert

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#748]
Aufgrund von begrenzten Filtermöglichkeiten im Portal ist es interessant, den JSON- oder CSV-Download zu verwenden. Dies wurde hier auch schon empfohlen (z. B. #639)
Der Download scheitert bei meinem User allerdings in letzter Zeit. Bitte prüfen. 

Falls es an der Dateigröße liegen sollte, schlage ich vor, die Dumps nach Zeiträumen zu unterteilen, z. B. nach Jahr des Tatzeitpunkts.

Bisherige URL:
https://www.weg.li/notices/dump.json

Neue URL (nur Vorschlag):
https://www.weg.li/notices/dump_2024.json 
https://www.weg.li/notices/dump_2023.json 
https://www.weg.li/notices/dump_2022.json 

Zusätzlich wäre dann noch eine Download-Option mit fester URL interessant, wie:
https://www.weg.li/notices/dump.json 
oder
https://www.weg.li/notices/dump_CurrentYear.json 

BItte auch analog für CSV umsetzen.

**Comment by phoet** [comment]
das scheint bei deinem user wohl schon zu lange zu dauern. wir werden diese funktionalität zukünftig anders anbieten, da der prozess derzeit die web-worker blockiert.

**Comment by phoet** [comment]
for reference https://twitter.com/weg_li/status/1770750120830685642

**Comment by phoet** [comment]
Die eigenen Daten können als CSV exportiert werden: https://www.weg.li/user/exports

**Comment by RalphBike** [comment]
Danke! Der Download funktioniert und ist auch schneller als zuvor. Die Dateigröße ist deutlich kleiner als das JSON. 

Allerdings fehlt mir noch der Status der Meldung. Nett wären zusätzlich noch Euros und Punkte. Auf den Hinweis per Mail könnte ich dafür verzichten.

**Comment by RalphBike** [comment]
Status ist jetzt auch drin. Danke!
