### ISSUE TITLE
iOS & Safari / Hinweis zur Standortfreigabe fehlerhaft

### ISSUE THREAD

**Issue by bondskin** [weg-li/weg-li#751]
In der Webseite ist wie folgt formuliert:

"Für die Übermittlung der Standort-Metadaten muss iOS 17 oder neuer verwendet werden. Außerdem muss in den Einstellungen unter Safari die Option Standortzugriff auf Immer erlauben gesetzt sein."

Diese Option gibt es aber weder für Safari unter "Einstellungen / Datenschutz & Sicherheit / Ortungsdienste / Safari" noch unter "Einstellungen / Safari"
"Immer erlauben" ist für nativ Safari nicht möglich
(iOS 17.4.1)

![IMG_4287](https://github.com/weg-li/weg-li/assets/55050117/18ead884-ad84-48c6-9f2c-edde5dbd8feb)
![IMG_4286](https://github.com/weg-li/weg-li/assets/55050117/f75d297a-db27-45eb-b6cc-7d5fee7eb299)

**Comment by mnin** [comment]
Der Weg ist (auf Englisch) ist wohl der folgende:

Settings => Privacy & Security => Photos => Safari => Options => Include: Location

1.  ![IMG_0398](https://github.com/weg-li/weg-li/assets/92227/f28fc74c-4ae5-41db-a4b1-d3e7eff4f3b3)
2. ![IMG_0397](https://github.com/weg-li/weg-li/assets/92227/1fcb54af-af7f-4725-a203-a57ae85900df)
3. ![IMG_03992](https://github.com/weg-li/weg-li/assets/92227/0b0ce403-cf5b-41f3-8a85-0918ae5038b7)
4. ![IMG_0402](https://github.com/weg-li/weg-li/assets/92227/316f95c6-0d59-4a85-9d5d-f1933e383092)
5. ![IMG_0403](https://github.com/weg-li/weg-li/assets/92227/16bfd880-127e-4555-aa41-5efc732579a7)

**Comment by bondskin** [comment]
Danke @mnin , das habe ich so bereits eingerichtet, deshalb war ich über die Instruktion verwundert.

**Comment by phoet** [comment]
🤷 was genau ist denn jetzt der Pfad in der deutschen Benutzerführung? Ich hatte das glaube ich aus dem entsprechenden Apple Issue übernommen.

**Comment by mnin** [comment]
@phoet in der deutschen Sprache ist das wie folgt:

Einstellungen => Datenschutz & Sicherheit => Fotos => Safari => Optionen => Einbeziehen: Standort anschalten

Hier die Screenshots:

![IMG_0765](https://github.com/weg-li/weg-li/assets/92227/f3a5f5e9-9c1e-4575-9c9c-a9a65bd43816)
![IMG_0766](https://github.com/weg-li/weg-li/assets/92227/2226e010-d4a8-40fe-bb73-6864e9a5a5e4)
![IMG_07672](https://github.com/weg-li/weg-li/assets/92227/379d2618-274a-4ce6-867b-2f381983a846)
![IMG_0768](https://github.com/weg-li/weg-li/assets/92227/0352493b-1457-49ac-8c8b-07636f10e6ca)
![IMG_0769](https://github.com/weg-li/weg-li/assets/92227/2e4e6b8b-400a-418a-94fa-842a45419cc4)

**Comment by phoet** [comment]
Habe den Hinweis ein wenig angepasst.
