### ISSUE TITLE
Enhancement: Datums-/Uhrzeituebernahme Beobachtungsstart -> Beobachtungsende

### ISSUE THREAD

**Issue by g6094199** [weg-li/weg-li#757]
Hi,

das Beobachtungsende ist im Minimum der Beobachtungsstart. In den ueberwigenden faellen is der Beobachtungsstart == Beobachtungsende, also macht es Sinn, sobald der Beobachtungsstart ausgewaehlt ist das Beobachtungsende automtisch auch auf dieses Datum zu setzten.

Gleiches gilt natuerlich auch fuer die Uhrzeit.

![image](https://github.com/weg-li/weg-li/assets/37833326/e9b374c8-2bba-4201-becc-2b43d79f5a88)

**Comment by phoet** [comment]
Das ergibt ggf Sinn, allerdings ist es immer etwas problematisch Nutzerdaten zu überschreiben.

**Comment by g6094199** [comment]
ok. der gedachte workflow ist doch setzte Beobachtungsstart (Datum/Zeit) und dann setzte Beobachtungsende. also so wuerde der NORMALE nutzer das ja an gehn. das koennte man ja nudgen im dem man das Beobachtungsende ausgraut und erst setzt wenn Beobachtungsstart bearbeitet ist. ;-)

man koennte halt  einmal nerviges datum auswaehlen/eingeben in bestimmt 90% der faelle sparen. das ist schon beim ersten mal nervig......also im allgemeinen...net nur hier...das ist einfach ein ultra nerviges feld fuer anwender  ;-)

**Comment by phoet** [comment]
Also grundsätzlich sollten die Zeitstempel der Bilder den Beobachtungszeitraum vorgeben und die können per click übernommen werden. Die manuelle Auswahl ist eher der Sonderfall

**Comment by g6094199** [comment]
hat er bei meinen tests jetzt nicht gemcaht. welches tag liest der genau aus?

**Comment by phoet** [comment]
Die dafür vorgesehenen EXIF Daten oder den Dateinamen. In deinem Screenshot sind auch schon die Vorschläge zu sehen 🤷

**Comment by g6094199** [comment]
hhmmm...ok, dann sieht man auch auch direkt das es wohl nicht funktioniert.

dateiname war zum bsp 2024-04-10-13-45-49-250

**Comment by phoet** [comment]
das datumsformat wurde noch nicht unterstützt, scheint kein gängiges format zu sein.
