### ISSUE TITLE
Fotos auf Gesichter überprüfen und diese zum Blurren vorschlagen

### ISSUE THREAD

**Issue by Somebodyisnobody** [weg-li/weg-li#759]
Wenn ich als Nutzer ein Foto hochlade möchte ich Bereiche auf den Fotos vorgeschlagen bekommen, auf denen personenbezogene Daten von Dritten erkannt wurden und die ich verpixeln möchte, damit ich das Prinzip der Datensparsamkeit anwende und damit die DSGVO einhalten kann.

Konkrete Ideen dazu:
Zusätzlicher Schritt im Workflow "Bilder verpixeln" mit den Funktionen:

- Vorgeschlagene Bereiche 
  - Gesichtsformerkennung
  - unbeteiligte KFZ-Kennzeichen
- Manuelle Markierung von Bereichen.
- Vorschau der Verpixelung

Gesichtserkennung könnte mithilfe von yeephycho/tensorflow-face-detection passieren.

Einen Algorithmus zur Kennzeichenerkennung gibt es ja offenbar schon. Diesen könnte man nutzen und wie folgt erweitern:
- Entweder: Alle Kennzeichen außer das, das auf dem Bild die größte Fläche einnimmt werden zur Verpixelung vorgeschlagen.
- Oder: Es sollten zwei Kriterien einfließen, die die erkannten Kennzeichen gewichten. Die zwei Werte werden addiert, das Kennzeichen mit dem höchsten Summenwert gewinnt:
  - Je weniger Pixelfläche das Kennzeichen einnimmt desto geringer ist der Wert des Kennzeichens. Als Maßstab wird das kleinste Kennzeichen (0) und das größte Kennzeichen (1) genommen.
  - Je weiter außen sich das Kennzeichen von der Bildmitte befindet, desto geringer ist der Wert des Kennzeichens. Als Maßstab wird der am weitesten entfernteste Punkt (0) und die Bildmitte (1) genommen.

**Comment by phoet** [comment]
Ähnliche Features wurden bei uns schon gewünscht. Imageprocessing wollen wir aber nicht anbieten, das kann auch jedes Mobiltelefon besser als der Browser
