### ISSUE TITLE
Bitte Tatbestand 102118 mit Ergänzung "zum Parken" hinzufügen

### ISSUE THREAD

**Issue by 4s1** [weg-li/weg-li#762]
Bitte den Tatbestand [TbNr. 102118](https://www.weg.li/charges/102118-sie-benutzten-verbotenerweise-den-grunstreifen) mit der Konkretisierung "Sie benutzten verbotenerweise den Grünstreifen zum Parken" hinzufügen.

**Comment by phoet** [comment]
Du meinst https://www.weg.li/charges/112030-sie-parkten-verbotenerweise-auf-der-verkehrsinsel-dem-grunstreifen ?

**Comment by 4s1** [comment]
Ja vermutlich, da hat mich der "Verkehrsinsel" Teil irritiert. 
Lässt sich das als 2 Tatbestände, also ein mal mit "... der Verkehrsinsel" und ein mal mit "... dem Grünstreifen" im System hinterlegen, dass das nicht jedes mal manuell unten mit eingetippt werden muss?

**Comment by phoet** [comment]
Nein
