### ISSUE TITLE
Fahrzeughersteller "Piaggio" hinzufügen

### ISSUE THREAD

**Issue by C-Otto** [weg-li/weg-li#764]
Mofas der Marke Piaggio können im Moment nicht korrekt eingetragen werden.

**Comment by phoet** [comment]
in wiefern?

**Comment by C-Otto** [comment]
Das Dropdown "Marke" erlaubt keinen Freitext und Piaggio ist keine der Möglichkeiten.
Siehe https://www.weg.li/notices/8ee4ae9b070514c1490ccf941b7d9227 (ich habe Fiat ausgewählt und einen Freitext-Kommentar dazu ergänzt).

**Comment by phoet** [comment]
1. optionales Feld
2. Marke vorschlagen https://www.weg.li/brands/new

**Comment by C-Otto** [comment]
Danke, den Link habe ich gesucht, aber nicht gefunden. Und mir war nicht klar, dass das Feld optional ist - die Markierung ist aber eindeutig, mea culpa.

**Comment by phoet** [comment]
👌
