### ISSUE TITLE
'+' in sign up email forbidden

### ISSUE THREAD

**Issue by SimSon2710** [weg-li/weg-li#769]
Hey!

I always add a '+' sign and the service name in my email address when I register for a new service, f.e. mmueller+wegli@gmail.com.

However, when I tried to register for weg.li, I got an error "E-Mail ist nicht gültig" (see screenshot). Without the +serviceName it worked as expected.
Interestingly, I could use the '+' notation for receiving the sign up invitation mail.

Is there any reason to disallow this notation/pattern or could one just edit the code to allow it, as it is a legal mail format?

![test_example](https://github.com/weg-li/weg-li/assets/82225296/75daf5b2-3b33-41d2-b4bf-6ff9818b885c)

Cheers

Simon

**Comment by phoet** [comment]
besteht dieses problem noch immer?

**Comment by SimSon2710** [comment]
Wunderbar, funktioniert jetzt. Vielen Dank für's Fixen :)
