### ISSUE TITLE
CSV-Export noch Bedarf statt wöchentlich

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#770]
Als Anwender von Weg.li möchte ich die (im übrigen sehr hilfreichen) CSV-Exporte zu beliebigen Zeiten starten und das CSV anschließend herunterladen können. Bei Bedarf auch mehrfach pro Tag oder in Abständen von weniger als einer Stunde.

Begründung: Die CSV-Exporte sind generell sehr cool. Sie erlauben Nutzern, eigene Auswertungen zu machen und frei zu suchen und zu filtern. Allerdings werden sie inzwischen automatisch wöchentlich angelegt. Damit fehlt die Flexibiliät in der Erstellung und die Aktualilität der Daten, gerade nach Bearbeitung vieler Meldungen. Im Worst case müsste ein Nutzer dann 6,99 Tage auf einen neuen Export warten. Daher schlage ich vor, die Erzeugung der Exporte wieder auf "Nach Bedarf" umzustellen. Der Nachteil einer Wartezeit bei der Erstellung kann IMHO vernächlässigt werden, solange die Erstellungszeiten überschaubar bleiben. Mehrere Minuten bis zu einer Stunde fände ich okay.

Ich sehe in der Umstellung keinen großen Mehraufwand in der Berechnung, sondern vermutlich weniger Rechenaufwand und weniger Platzbedarf, da nur wenige User das Feature nutzen. Ich gehe davon aus, dass es fast nur von aktiveren Nutzern verwendet wird. Das ist allerdings alles Vermutung, mir liegen keine Nutzungsdaten vor.

**Comment by phoet** [comment]
Äh, wie meinen? Es gibt den Export der eigenen Daten, der manuell angestoßen werden muss und den Export des anonymisierten Datensatzes, der pro Kalenderwoche läuft. Hast du da was verwechselt?

**Comment by RalphBike** [comment]
Uah, ich habe die beiden anscheinend tatsächlich verwechselt. Entschuldige bitte! 

Das Ursprungsthema ist damit erledigt. 

Beim Export auf /user/exports fallen mir aber noch Kleinigkeiten auf:
* Ich bekomme reproduzierbar eine Meldung "Immer nur einen Export zur Zeit starten!", obwohl ich nur einen einzigen gestartet habe. Die Erwartung wäre, einen solche Meldung nur zu bekommen, wenn wirklich mehrere parallele Downloads gestartet habe.
* In den beiden Dropdowns könnten die jeweils einzigen Optionen Meldungen und CSV bereits vorausgewählt sein, da es ohnehin keine alternativen Optionen gibt.
* Das Wort "dauern" in der Meldung "kann einige Minuten Dauern" sollte klein geschrieben werden (Sorry für das Minimal-Finding)

**Comment by phoet** [comment]
Wie lange die Generierung daurert wird nicht gemessen oder abgespeichert, geht aber aus der Ankunftszeit der E-Mail hervor. Eine Änderung des Prozesses ist derzeit nicht geplant.

**Comment by RalphBike** [comment]
Naja. Die Fehlermeldung trotz korrekter Nutzung ist ein Usability Bug. 

Und das Preselect der beiden Dropdowns ist vermutlich sehr überschaubarer Aufwand und würde bei jedem Export zwei Klicks sparen.
