### ISSUE TITLE
Kartenansicht: Merken des als letzten besuchten Areals

### ISSUE THREAD

**Issue by g6094199** [weg-li/weg-li#771]
Ich hoffe viele befolgen den weisen Rat: never fuck with our neigbours. Und "verbessern die Verkehrssituation" einige (Kilo)meter von Zuhause weg. So zumindest bei mir. Im Moment ist das default Verhalten beim aufruf der Kartenansicht: Zoome zur Home-PLZ. Jetzt interessiert mich aber vornehmlich natuerlcih die PLZ/Ort wo ich die "Verkehrssituation verbessere", daher waere es viel besser, wenn der Kartenansicht auf die "letzte gesuchte PLZ/Ort" zoomen wuerde. Das betrifft sicherlcih einen grossteil der Ansichten.

ggf. koennte man einen "Home" Button hinzufuegen, der auf die Heim-PLZ zoomt.

Sascha

**Comment by phoet** [comment]
Was hindert dich denn daran Beweisfotos mit Geo-Location hochzuladen?

**Comment by g6094199** [comment]
ueberschneidung mit diesem [issue](https://github.com/weg-li/weg-li/issues/340)

**Comment by g6094199** [comment]
> Was hindert dich denn daran Beweisfotos mit Geo-Location hochzuladen?

und wenn mein aufnahmegeraet keine geolokation besitzt?! und selbst wenn, bis das gps ein lock hat bin ich schon eine minute am problem vorbei gefahren....

**Comment by phoet** [comment]
Wir optimieren nicht für Sonderfälle
