### ISSUE TITLE
API: Get all Notices scheitert mit 502

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#774]
Die API ist ziemlich cool!

Leider scheitert ab einer bestimmten Zahl von Meldungen der Abruf aller Meldungen über die API (/notices) . Der Aufruf dauert recht lange und endet dann in einem 502 (Bad Gateway). Hier von sind vor allem aktive Nutzer betroffen.

`502 Server Error: Bad Gateway for url: https://www.weg.li/api/notices/?X-API-KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
`

Zur Lösung schlage ich eine konfigurierbare Paginierung vor, über optionale Parameter. Z.B. StartIndex und EndIndex der Ausgabe. Wichtig wäre mir dabei, dass als Sortierung "Latest-First" verwendet wird, damit man schnell und einfach an die aktuellen Meldungen kommt und sich nicht durch N Seiten von alten Meldungen quälen muss.

**Comment by RalphBike** [comment]
Ist ja schon ne Weile her, gibts hierzu ein Update?

**Comment by phoet** [comment]
Nein

**Comment by phoet** [comment]
notices can now be paginated with `page` and `per_page` request params https://github.com/weg-li/weg-li/commit/85fcaeacc6e4c285154ea090fa1b5a6750ab2de6#diff-5c06f5e686b7a88eb49b45a88bd74da4cae027155a3cfd86f2d4ed0e93cf94cd
