### ISSUE TITLE
weg.li does not allow reporting in Apple's Lockdown Mode

### ISSUE THREAD

**Issue by ekaflaereht** [weg-li/weg-li#776]
Hi,

when you enable on your [iPhone Lockdown Mode](https://support.apple.com/en-us/105120) and try to report a case with Safari on https://weg.li, then the website does not properly continue after uploading the picture.

There is no analysis or menu where you can select the details of the case.

If you disable "Lockdown mode" in the website setting then upload works fine but of course it compromises the security.

Maybe it has something to do with Javascript, but usually most websites work beside small graphical issues from time to time.

Thanks in advance

**Comment by phoet** [comment]
You can exclude specific sites from lockdown mode, which is not supported on weg.li
