### ISSUE TITLE
falsche E-mail adresse für den Landkreis Wolfenbüttel

### ISSUE THREAD

**Issue by JabelsBS** [weg-li/weg-li#780]
Ich habe auf eine Anzeige heute die Antwort bekommen, dass die hinterlegte E-Mail adresse (oeffentlichesicherheit@wolfenbuettel.de) nicht (mehr) der richtige Adressat ist. 
Laut Mail sollen zukünftige Anzeigen an: strassenverkehrsamt@lk-wf.de

![grafik](https://github.com/weg-li/weg-li/assets/64330818/a1bf4249-5316-4a6f-a625-1ff2aebaa352)

**Comment by phoet** [comment]
Ich habe noch 3 Einträge mit der veralteten Adresse gefunden und korrigiert. Nutze beim nächsten mal bitte das entsprechende Formular auf der Seite des Bezirks.
