### ISSUE TITLE
Analyse hakt bei manchen Notices

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#786]
Hi, ich bin mir nicht sicher, ob das Thema in einem Ticket gut aufgehoben ist. Ich versuche es trotzdem.

Vier meiner Meldungen hängen nun schon seit einiger Zeit in einer Analyse-Schleife fest. Zwei davon seit ca. 45 Minuten, zwei seit fast 24 h. Das kommt mir seltsam vor. Ich hätte sie auch gerne manuell bearbeitet, kann das aber nirgends tun, die Edit-Seite ist in einer Dauerschleife gefangen. IDs sind:

```
c858ba7dc103fb9d779659abdd3709fb
5a262d66c57c4a490b1b8b6a0dfe646c
9c5ebcf251be7d8d8b7768df1c111460
c8c4edbcf5e31d86d5beb635cb36fc0a
```

**Comment by phoet** [comment]
Da hat sich wohl die API von Google Vision leicht verändert und liefert keinen default wert mehr mit wenn kein Text enthalten ist. Closed via 20712388

**Comment by RalphBike** [comment]
Cool, danke. Aber was mache ich mit den 4 Meldungen? Nochmal neu hochladen?

**Comment by phoet** [comment]
Sobald die neue version live ist gehts, allerdings schlägt gerade das deployment fehl.

**Comment by RalphBike** [comment]
Okay, dann lasse ich die Meldungen mal so und warte, was passiert. Falls ich noch etwas beitragen kann, sag gerne Bescheid, Danke nochmal!
