### ISSUE TITLE
Mehrere Bezirke/Ordnungsämter pro PLZ erlauben

### ISSUE THREAD

**Issue by der-eismann** [weg-li/weg-li#787]
Moin! Bisher hatte die Sache mit dem vorgeschlagenen Ordnungsamt immer super funktioniert, in Brandenburg (und anderen ländlichen Gegenden) stößt das Prinzip leider an seine Grenzen.
Beispiel: PLZ 15537. Darin enthalten sind als separate Gemeinden:
- Grünheide
- Erkner
- Gosen-Neu Zittau

Die jeweils alle eigene Gemeinden mit eigenen Ordnungsämtern sind. Einer der Mitarbeiter war so freundlich meine Anzeige weiterzuleiten, aber das kann man nicht immer erwarten. Wäre es vielleicht möglich eine Art Dropdown-Menü für die Bezirke einzuführen, damit die Anzeige auch den richtigen Empfänger findet? Aber vermutlich wären dafür größere Umbauten erforderlich.

**Comment by phoet** [comment]
Größere umbauten nicht, aber alles müsste genau kartiert werden, das wäre ein. Riesiger Pflegeaufwand. deswegen können aliase in einem Bezirk hinterlegt werden.

**Comment by phoet** [comment]
Die Vorschläge werden händisch geprüft, eine Entsprechende Begründung eintragen.
