### ISSUE TITLE
Gamification vs. Updatefrequenz des Leaderboards

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#795]
Gibt es eine Chance, den Lag des Leaderboards etwas zu reduzieren?

Ich als Anwender finde es ziemlich schade, wenn ich Altlasten bearbeitet habe und das Leaderboard das erst gefühlt eine Stunde später honoriert. Etwas mehr Dynamik wäre nett, alle 2-10 Minuten oder so? 

Mja, das eigene Profil funktioniert als Ersatz, ist aber nicht halb so lustig, außerdem weichen die Zahlen teilweise vom Leaderboard ab.

**Comment by phoet** [comment]
Die Statistiken im Leaderboard werden eine Stunde gecached, weshalb auch unten im Fuß steht wann sie wieder aktuell sind:

> Wird aktualisiert: 17.09.2024 16:34 

Die generierung der Statistiken verbraucht relativ viele Resourcen vor allem in der Datenbank, weshalb es ohne Caching derzeit nicht geht. Stündlich finde ich schon relativ generös, bei einem Umbau würde ich es wahrscheinlich auf Tagesbasis nächtlich berechnen.

**Comment by Joshua2504** [comment]
Vielleicht lässt es sich so umbauen, dass die Statistiken bzw. der Cache bei neuen Anzeigen entsprechend aktualisiert werden? Ohne die Statistiken komplett neu zu generieren?
