### ISSUE TITLE
Option um Google-Services zu deaktivieren

### ISSUE THREAD

**Issue by evur** [weg-li/weg-li#797]
Hallo, die Kennzeichenanalyse über Google finde ich etwas bedenklich und eher unnötig. Es wäre schön eine Option zu haben um die Google-Services abzuschalten, damit die Verarbeitung der Bilder minimal gehalten wird um keine vermeidbare Angriffsfläche zu erzeugen.

**Comment by phoet** [comment]
"um keine vermeidbare Angriffsfläche zu erzeugen." Wer soll hier was angreifen? 😶

**Comment by evur** [comment]
Es geht darum, rechtliche Konsequenzen durch die Übermittlung der Bilder an Dritte zu vermeiden, falls doch mal jemand das bemängeln sollte. Wobei mir gerade in den Sinn kommt, dass es am Ende überhaupt nicht möglich ist, festzustellen ob solch eine Option aktiviert war - außer dies wird in der Anzeige vermerkt.

**Comment by evur** [comment]
PS: Google ist ja nicht gerade für datenschutzfreundliche Services bekannt. 😖

**Comment by evur** [comment]
?
