### ISSUE TITLE
Vorschlag: Möglichkeit den Kartenausschnitt mit Marker als Anhang per Klick einfügen

### ISSUE THREAD

**Issue by c-schmitz** [weg-li/weg-li#798]
Ich habe nun schon mehrere Mal Rückmeldung vom Ordnungsamt bekommen, dass man gerne eine Hausnummer zum Ort des Verstoßes hätte. Das Problem ist, dass in manchen Straßen, z.b. in der Nähe von dünner besiedelten Gebieten eine Straße nicht durchgängig mit Häusern bestückt ist, ergo es auch keine Hausnummern gibt. Dann muss man erstmal versuchen den Ort zu beschreiben.

Deswegen wäre es toll, wenn man mit einem Klick die Openstreetmap(?) Kachel mit Pin/Marker als Bild/Anhang in die Mail mit reinsetzen könnte.
Das würe langwierige Beschreibungen im Tatort Feld ("200m hinter der toten Katze links") vermeiden.

**Comment by phoet** [comment]
Genau für diesen Fall gibt es das "Tatort" Feld. Unser Kenntnissstand ist, dass die Ämter keine Geocoordinaten wollen.

**Comment by c-schmitz** [comment]
Nee, es geht nicht um Geokoordinaten, sondern um einen Kartenausschnitt, in dem der Marker zu sehen ist, als Bild.

**Comment by phoet** [comment]
Und vom Amt kam die Anfrage doch bitte einen Kartenausschnitt zu übermitteln?

**Comment by c-schmitz** [comment]
Die Idee ist es mit Kartenausschnitt und Marker die Nachfrage überflüssig zu machen. Dann ist nämlich ganz klar, wo genau das war und ich muss mir nicht sprachlich und aus dem Gedächtnis eine Beschreibung zusammenklöppeln.

**Comment by phoet** [comment]
Dann müsste der Sachbearbeiter diese Information zusammenstöpseln, ohne Gedächtnis 🤷 

In der E-Mail gibt es bereits einen Link zur Webseite, die einen Kartenausschnitt beinhaltet. Diese Info wäre also redundant und zusätzlich keine Verbesserung im Prozess.

**Comment by c-schmitz** [comment]
@phoet Wir wissen ja schon, dass Sachbarbeiter nicht gerne auf Links klicken und sich Infos von irgendwo zusammensuchen wollen.
Wie wäre es, wenn ich den Sachbarbeiter mal frage, ob ein solches Bild als E-Mail-Anhang hilfreich wäre statt Tatort-Beschreibung?  Dann wüssten wir mehr vom Standpunkt der Personen, die es betrifft.

**Comment by phoet** [comment]
Es wurde nicht übereilt geschlossen, sondern weil dieses Feature nicht notwendig ist und deswegen auch nicht implementiert wird.

**Comment by c-schmitz** [comment]
Ich dachte, das Projekt lebt vom Mitmachen, aber mit der Haltung ("hier gibts keine Diskussion und irgendwelche Fakten sind mir auch egal, ich habe das jetzt so beschlossen") fühlt sich das eher nicht so an.

**Comment by phoet** [comment]
Gerne diskutiere ich mit dir über Fakten:

- es gibt für diesen Anwendungsfall das Feld "Tatort", so wie vom Amt gewünscht
- es gibt bereits die Möglichkeit der Kartenprüfung
- das Generieren von redundantem Kartenmaterial, kostet Rechenzeit und Speicherplatz

Solange es keine Anforderung von Amtsseite gibt (nein gibt es nicht) ist dies kein sinnvolles Feature.
