### ISSUE TITLE
Mehrere Fotos, Kennzeichenerkennung findet trotzdem falsches Auto

### ISSUE THREAD

**Issue by hzulla** [weg-li/weg-li#8]
Mein Eintrag vom 10.08.2019 17:59 besteht aus drei Fotos, wo jeweils mittig der Falschparker zu sehen ist. Auf allen drei Fotos ist das Kennzeichen des Falschparkers zu sehen. Die Analyse hat trotzdem das in nur einem der Fotos vollständig sichtbare Kennzeichen eines unbeteiligten Autos daneben erkannt und mir vorgeschlagen.

Vorschlag: Alle Fotos auf Kennzeichen analysieren und am Ende das Kennzeichen übernehmen, das am häufigsten erkannt wird und/oder die größte Anzahl Pixel bedeckt.

**Comment by hzulla** [comment]
Zweites Beispiel: 13.08.2019 06:52. Falschparker in der Mitte, unbeteiligtes Auto klein im Hintergrund. Bildanalyse schlägt das Kennzeichen des Unbeteiligten vor.

Vielleicht wäre neben der Pixelfläche auch der Abstand des Kennzeichens zur Bildmitte ein geeignetes Sortierkriterium.

**Comment by phoet** [comment]
hi hanno, vielen dank fürs fleißige testen und feedback geben!

du hast recht, bei der erkennung des kennzeichen ist noch viel luft nach oben. ich bin ehrlich gesagt überascht, dass überhaupt so viele nummernschilder erkannt werden, denn da wird momentan nur per OCR text ausgelesen und dann mit einem regulären ausruck geschaut ob eventuell ein nummernschild drinne stecken könnte...

anhand der gesammelten fotos kann ich demnächst bestimmt eine stark verbesserte version bauen. zunächst versuche ich mich noch an der erkennung der automarken und an einer optimierten hochlade funktion, bei der man gleich viele bilder in unterschiedlichen meldungen auf einmal erstellen kann.

**Comment by hzulla** [comment]
Die Kennzeichenerkennung scheint von links nach rechts zu suchen und liefert offenbar einfach den ersten Fund zurück.

**Comment by telewolf** [comment]
Nach Auskunft eines Hamburger Knöllchen-Angestellten ist es von Nachteil, wenn sich auf den Beweisfotos Kennzeichen oder Gesichter nicht Beteiligter Personen oder Fahrzeuge befinde. Da die Beweisfotos im Falle eines Widerspruchs Bestandteil eines öffentlichen Verfahren werden und die Bilder dann für Jeden einsehbar wären, der Datenschutz dann nicht mehr gewährleistet ist, lässt die Hamburger Owi-Stelle die Owi angeblich sofort Fallen wenn Widerspruch eingelegt wird und fremde Gesichter oder Kennzeichen zu sehen sind. Warum dieses nicht einfach geschwärzt bzw. anonymisiert werden ist noch nicht geklärten.

In sofern stellt sich die Frage ob es evtl. besser ist den User darauf hinzuweisen, dass keine anderen Kennzeichen auf den Aufnahmen zu sehen sind, anstatt dem OCR bei zu bringen z.B. Kennzeichen in der Bildmitte oder anhand der Größe zu bevorzugen.

**Comment by phoet** [comment]
am besten beides machen: langfristig die sachen verpixeln die irrelevant sind und in der zwischenzeit aufzeigen wie man am besten beweisfotos macht, am besten mit einem beispiel.

für den anfang habe ich schon mal den hinweistext ein wenig erweitert.

**Comment by phoet** [comment]
das schöne an weg-li ist ja auch, dass "die behörde" im zweifel "die optimierten" bilder vom server laden kann 😏

**Comment by telewolf** [comment]
Idee: Bilder markieren die für die Analyse verwendet (bevorzugt) oder bei der Analyse nicht berücksichtigt werden sollen.

**Comment by hzulla** [comment]
Dagegen. Man sollte eh nur für die Analyse relevante Bilder hochladen.

**Comment by telewolf** [comment]
Ich mache z.B. ein Foto von vorne und eins von hinten. Wenn hinten ein Angänger dran ist, möchte ich dass das Foto von vorne ausgewertet wird. 

Wenn man mehrere Fotos als Nachweis macht, kann es sein, dass man auf einem Bild ein fremdes Kennzeichen mit drauf hat. Auch in dem Fall würde ich gerne bei dem anderen Foto „nur dieses Bild analysieren“ klicken.

In sofern möchte ich meinen Vorschlag abändern, dass es zusätzlich zum vorhandenen Analyse-Button neben den Fotos ein weiterer kleines Zeichen gibt mit der Funktion „nur dieses Bild analysieren“

**Comment by phoet** [comment]
im analyse-prozess wird jetzt nicht mehr nur der erste treffer verwendet, sondern eine wahrscheinlichkeit abgebildet. die werde ich zukünftig noch etwas anpassen, aber im allgemeinen sollte es diese problematik lösen #66
