### ISSUE TITLE
Status "Bearbeitet"

### ISSUE THREAD

**Issue by Joshua2504** [weg-li/weg-li#805]
Feature Request: Neuer Status "Bearbeitet" oder "Bereit" für Anzeigen, was bedeutet, dass die Anzeige fertig bearbeitet wurde und sie bereit zum Versand ist.

Das würde einfach bei der Bearbeitung von angelaufenen Anzeigen helfen.

**Comment by phoet** [comment]
In wiefern? Ich verstehe nicht welchen Unterschied das zu unvollständig haben soll.

**Comment by Joshua2504** [comment]
Sobald eine Anzeige gespeichert wird, ist sie unabhängig davon, ob sie wirklich vollständig erfasst wurde (bspw. fehlen noch Hinweise o.Ä.), bereit für den Versand. Solche Anzeigen könnten dann mit einem entsprechenden Status versehen werden, um zu wissen, dass sie noch nachbearbeitet werden muss.

**Comment by phoet** [comment]
Das wäre ähnlich wie #680 über ein entsprechendes tag abhandelbar.
