### ISSUE TITLE
API: Patch Notice scheitert mit Error 500

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#808]
Hi, ich finde die API weiterhin sehr spannend. Grundsätzlich funktioniert mein Zugriff, z.B. auf die Charges. Allerdings komme ich mit Patch-Notice nicht weiter, ich bekomme folgende Meldung:

`json: {'code': 500, 'message': 'undefined method `permit\' for "tbnr":String'}`

Wobei immer das letzte Feld in meinem Data-Dictonary diesen Fehler wirft, in diesem Fall eben "tbnr". Diverse Versuche waren bisher erfolglos.

Hier ein Stück Beispiel-Code (Python): 

```
def patchNotice_SetTBNR(session_token, token, tbnr = '112454'):
	noticeDate = {'token': token, 'tbnr': tbnr}

	url_tmp = 'https://weg.li/api/notices/'+token;

	params_dict = {
		"X-API-KEY": session_token
		,"notice": noticeDate
	}

	try:
		response = requests.patch(url_tmp, params_dict)
		response.raise_for_status()
		json = response.json()
		print (f"json: {json}")
		return json;

	except requests.exceptions.HTTPError as err:
		raise SystemExit(err)
	return False;
```
		
Falls ich noch weitere Infos liefern kann, mache ich gerne.

**Comment by phoet** [comment]
Diese Funktionalität ist vorhanden: https://github.com/weg-li/weg-li/blob/master/spec/requests/api/notices_request_spec.rb#L54-L72

Am besten einmal das JSON anschauen, was da übermittelt wird, die Fehlermeldung lässt darauf schließen, dass `tbnr` nicht korrekt in einem JSON objekt steckt.
