### ISSUE TITLE
Zeitliche Sortierung der Meldungen scheitert nach erstem Edit wegen fehlender Sekunden

### ISSUE THREAD

**Issue by RalphBike** [weg-li/weg-li#816]
Als Anwender von weg.li suche ich nach einer Möglichkeit, die Meldungen in korrekter Reihenfolge nach Tatzeit/Datum erstes Foto zu sortieren, auch wenn diese schon teilweise editiert wurden. Ich möchte das machen, um Lücken in den Daten besser füllen oder fehlerhafte GPS-Daten korrigieren zu können. Welche Straße und Hausnummer war das davor oder danach, etc.

Das Sortieren geht im Portal und im Export gut, solange die Meldungen nur angelegt, aber NICHT editiert wurden. Nach dem ersten Edit verlieren die Meldungen ihre korrekte Sortierung, weil anscheinend die Sekunden der Tatzeit fehlen. Aus 2024-11-14 10:02:34 +0100 wird 2024-11-14 10:02:00 +0100 und die Meldungen mit "10:02:00" sind nur noch auf Minutenbasis in eine Reihenfolge zu bringen. 

Die Daten kommen aus größeren Bulk-Uploads und werden daher auch nicht zwingend in chronologisch korrekter Rangfolge angelegt, weil die Fotos durch Bearbeitung nicht zwingend in korrekter Reihenfolge in den Upload kommen oder auch beim Zuordnen nicht unbedingt in korrekter Reihenfolge angelegt werden.

Hat noch jemand Ideen dazu?

**Comment by phoet** [comment]
Das ist korrekt, da wir zur Erfassung den input-type time verwenden, der nur stunden und minuten kennt https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time
