### ISSUE TITLE
Bundesstraßen „B123“ statt Straßenname

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#82]
In der Stresemannstraße wird „B431“ statt dem Straßennamen in die Owi geschrieben.

Siehe z.B. https://www.weg-li.de/notices/d1cdcad2dbd509315efdf50be4b69b75/edit

**Comment by phoet** [comment]
das sind die open-streetmap daten. dafür gibt es den map-picker, dass man alternativ etwas anderes auswählen kann.
