### ISSUE TITLE
Vorschlag: Überholabstandsverstöße in die Liste der Verstöße übernehmen

### ISSUE THREAD

**Issue by RDBloese** [weg-li/weg-li#825]
Es wäre schön, wenn Verstöße wie
"105112 Sie hielten beim Überholen keinen ausreichenden Seitenabstand zu anderen Verkehrsteilnehmern ein." (oder auch 103708, 103709)
in den Katalog der Verstöße übernommen werden könnten, sodass man weg-li auch zum Anzeigen zu dichten Überholens nutzen könnte.

**Comment by phoet** [comment]
Die Anforderungen an Anzeigen im fließenden Verkehr sind wesentlich höher und es sind oft andere Zuständigkeiten gegeben, weshalb bei uns nur der ruhende Verkehr gelistet ist. Kennst du schon den Openbike-Sensor?

**Comment by RDBloese** [comment]
Danke für die Antwort. Openbike-Sensor ist mir schon bekannt. Ich nutz bislang den Code für Sonstige Vergehen,  führe die Tatbestandsnummer dann im Kommentarfeld an und füge DashCam-Bilder bei. Da wäre es eine Erleichterung gewesen .

**Comment by phoet** [comment]
Hast du beim Ordnungsamt telefonisch erfragt, ob diese Anzeigen überhaupt bearbeitet werden?
