### ISSUE TITLE
Bug: Fix API example value datetime format

### ISSUE THREAD

**Issue by dbttr** [weg-li/weg-li#827]
The [API definition](https://www.weg.li/api-docs/index.html) shows datetimes as UTC values (ending in Z), e.g. for exports

```json
[
  {
    "token": "string",
    "export_type": "notices",
    "file_extension": "csv",
    "interval": 0,
    "created_at": "2024-12-10T15:53:30.455Z",
    "download": {
      "filename": "string",
      "url": "string"
    }
  }
]
```

However, the actual values specify an offset in contrast

```json
{
    "export_type": "notices",
    "file_extension": "csv",
    "created_at": "2024-12-09T03:02:28.827+01:00"
}
```

While this does not present a hurdle for some programming langues that handle this dynamically, it does e.g. for Rust, where a [chrono datetime](https://docs.rs/chrono/latest/chrono/struct.DateTime.html) has a different type depending on whether it is UTC or FixedOffset.

The examples should reflect the actual value format.

**Comment by phoet** [comment]
the examples are generated by the rswag swagger ui and nothing we have controll over. also the client is expected to handle all common date formats.
