### ISSUE TITLE
Bug: Fix API "fine" field data type in Charge model

### ISSUE THREAD

**Issue by dbttr** [weg-li/weg-li#828]
The [API definition](https://www.weg.li/api-docs/index.html) specifies the "fine" field of the Charge model as  `number($float)`. However, the /charges API actually delivers a stringified value for the field. This should be reflected in the description. Or changed in the implementation, but that could be a breaking change.

**Comment by phoet** [comment]
this is expected https://stackoverflow.com/questions/35709595/why-would-you-use-a-string-in-json-to-represent-a-decimal-number
