### ISSUE TITLE
Wenn man Meldung bearbeitet Button um ganze Meldung zu löschen

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#83]
Ich würde es toll finden, wenn man in einer Meldung ist um diese zu bearbeiten, dass man diese dann vollständig löschen kann.

Z.B. wenn man die Warnung bekommen hat, dass für dieses Datum und Uhrzeit für das Kennzeichen bereits eine Meldung vorhanden ist.

**Comment by phoet** [comment]
andersherum, in der warnung würde ich eine action anbieten, nämlich das löschen der aktuellen meldung.

**Comment by phoet** [comment]
geht gleich live
