### ISSUE TITLE
Bug: Fix API description of  Export model - non-existing fields

### ISSUE THREAD

**Issue by dbttr** [weg-li/weg-li#830]
The [API definition](https://www.weg.li/api-docs/index.html) lists fields `token` and `interval` for the Export model. The /exports/public API however does not include these fields in any item of its answer. They should be removed from the description.

**Comment by phoet** [comment]
Feel free to provide a patch for this. Just use the inline editor or whatever to change it 👍

**Comment by dbttr** [comment]
created pull request #833 for this
