### ISSUE TITLE
Feature: sort /exports/public API items by created_at field

### ISSUE THREAD

**Issue by dbttr** [weg-li/weg-li#831]
Currently, the /exports/public API has the last three items with created_at

- 2024-12-02T03:03:11.856+01:00
- 2024-**11-25**T03:02:58.858+01:00
- 2024-12-09T03:02:28.827+01:00

So it seems to be unsorted. It would be convenient to have this in chronological order straight from the API as most will be interested in the very newest item usually.

**Comment by phoet** [comment]
Hm, should be sorted by ID when unsorted. Weird...
