### ISSUE TITLE
PLZ-Feld Mindestbreite

### ISSUE THREAD

**Issue by jkfm** [weg-li/weg-li#85]
Hi,

Bei mir unter Firefox/Android hat das PLZ-Feld trotz genug Bildschirmbreite nur Platz für 4 Ziffern. Schöner wäre es, wenn immer die 5 Ziffern angezeigt werden.

![Screenshot_20191011-153032_Firefox](https://user-images.githubusercontent.com/17497479/66663609-525c6500-ec4b-11e9-9a1c-4d072fd2c41a.png)

**Comment by phoet** [comment]
ja, in der tat. das ist gerade ein wenig aus der not geboren. das werde ich alles nochmal anders anordnen, damit das mobile einfacher zu benutzen ist
