### ISSUE TITLE
Automarke Tesla fehlt

### ISSUE THREAD

**Issue by jkfm** [weg-li/weg-li#86]
Hi,

Die Automarke Tesla fehlt. Wäre es möglich, ein frei ausfüllbares Feld zu dem Dropdoen hinzuzufügen?

Gruß,
Johannes

**Comment by phoet** [comment]
füge ich hinzu, ein freitext feld halte ich nicht für hilfreich, die anzahl neuer automarken hält sich alles in allem relativ in grenzen.

**Comment by jkfm** [comment]
Danke!
