### ISSUE TITLE
Logo zu jedem Autohersteller in Liste

### ISSUE THREAD

**Issue by Natenom** [weg-li/weg-li#88]
Nicht jeder Mensch kennt sich mit Autos aus. Daher wäre es schön, wenn in der Liste der Hersteller rechts mindestens ein zugehöriges Logo zu sehen wäre.

**Comment by phoet** [comment]
sobald eine liste mit gemeinfreien logos im vektor format vorliegt sollte sich das leicht realisieren lassen.

**Comment by Natenom** [comment]
Eine Liste gibt es z. B. unter https://de.wikipedia.org/wiki/Kategorie:Datei:Logo_(Automobilhersteller)

Es ist aber die Info hinterlegt, dass die rechtliche Situation schwierig ist.

**Comment by phoet** [comment]
ich halte den zusätzlichen nutzen für überschaubar. zudem ist die automarke kein pflichtfeld. daher wird es dieses feature eine sehr niedrige priorität bekommen.

**Comment by Natenom** [comment]
Okay, das wusste ich nicht. In dem Formular für Privatanzeigen, das es für meine Stadt gibt, ist das eine Pflichtangabe.

**Comment by phoet** [comment]
ja, weil es in unterschiedlichen städten unterschiedliche anforderunge gibt, ist dieses feld optional. in 95% der fälle geht die automarke aber ohnehin eindeutig aus den beweisfotos hervor.

**Comment by phoet** [comment]
pro tip: auf dem nummernschild-rahmen steht idr das autohaus, z.b. mazda-hamburg.

**Comment by hollma** [comment]
Könnte man die Bilderkennung dafür nutzen, wenn man das Herstellerlogo im Beweisfoto markiert bzw. eine separate Grafik nur mit dem fotografierten Logo hochladen kann? Ich kann mich nicht erinnern, dass aus meinen Fotos die Marke jemals korrekt erkannt wurde, es aber bei den Kennzeichen sehr zuverlässig funktioniert.
