### ISSUE TITLE
Zeitformat/Datumformat bitte einstellbar im Profil machen

### ISSUE THREAD

**Issue by Natenom** [weg-li/weg-li#89]
Anscheinend werden Zeitformat und Datumformat entsprechend der Browsereinstellung zur Erfassung angezeigt. Ich habe im Browser EN eingestellt, möchte aber trotzdem DE nutzen. Hierfür habe ich keine Einstellung gefunden. Es ist sehr ungewohnt Daten in MM/DD/YYYY einzustellen. Auch der Umgang mit PM/AM ist eher ungewohnt.

**Comment by phoet** [comment]
es werden standard browser input fields genommen. bitte nutze die locale in deinem browser so, dass es für dich sinnvoll ist.
