### ISSUE TITLE
Erneute Anmeldung bei jeder Session

### ISSUE THREAD

**Issue by hzulla** [weg-li/weg-li#9]
weg-li will, dass ich mich regelmäßig neu einlogge. Ich würde stattdessen bevorzugen, dass die Session gültig bleibt, solange ich mich nicht bewusst auslogge.

**Comment by phoet** [comment]
eigentlich gibt es einen "remember me" cookie. ich schau mal ob ich da ggf was an der lebensdauer ändern muss. da ich mich selber zum testen ständig neu ein und auslogge ist mir das noch nicht weiter aufgefallen.

**Comment by hzulla** [comment]
Wenn ich einen Tag später die Site besuche, bin ich "irgendwie" eingeloggt. Im [Hamburger-Menu](https://de.wikipedia.org/wiki/Hamburger-Men%C3%BC-Icon) finde ich zwar meinen Account eingetragen, aber die Homepage fordert mich trotzdem auf, erneut einen Login vorzunehmen.

**Comment by phoet** [comment]
ah, ok, danke für den hinweis. schau doch mal, ob im hamburger menü dann der "mitteilungen" reiter auftaucht. 

es gibt eine logik, die erkennt ob der nutzer eingeloggt ist und im dann "notices/index" anstelle von "home/index" anzeigt auf der root-url. evtl harmonisiert das noch nicht so gut mit dem remember-me cookie

**Comment by hzulla** [comment]
Nein, immer noch.

Ich bin angemeldet, sehe meine Einträge, tippe unten in der Fußleisten-Navi auf "weg-li", lande auf der Homepage und werde dort zur Anmeldung aufgefordert.

**Comment by phoet** [comment]
ah! ok, das ist quasi ein link zu homepage, wo die login buttons so eingebaut sind. gibt es da was interessantes für dich zu gucken?

**Comment by hzulla** [comment]
Ich finde, wenn man eingeloggt ist darf kein Login-Formular/Button erscheinen.

**Comment by phoet** [comment]
ich sehe die beim entwickeln die ganze zeit, deshalb ist mir das nicht so aufgefallen 😄 

meine frage ist auch eher ob ich diese seite dann lieber verstecken soll, oder ob du findest, dass es relevante, für eingeloggte user sichtbarer inhalt sein sollte.

**Comment by hzulla** [comment]
Der Inhalt der Homepage ist relevant, aber für eingeloggte Nutzer sollte vielleicht besser die Login-Aufforderung durch einen Link zu /notices ersetzt werden.

**Comment by phoet** [comment]
<img width="1178" alt="Screen Shot 2019-08-15 at 19 09 43" src="https://user-images.githubusercontent.com/48745/63112406-745da200-bf90-11e9-9e38-bb14e5d0ad44.png">

die login buttons werden jetzt durch einen link zur meldungs übersicht ersetzt.

**Comment by phoet** [comment]
nachdem ich einige macken aus dem session-tracking gebügelt hatte, hab ich wohl auf dem weg vergessen die lebensdauer des remember-me-cookie über die session hinaus zu setzen... auch das sollte inzwischen heile sein und nach dem nächsten aufruf für 30 tage eingeloggt bleiben 🤞
