### ISSUE TITLE
Notwendigkeit für Sekunden bei Zeitangabe?

### ISSUE THREAD

**Issue by Natenom** [weg-li/weg-li#90]
Gibt es eine rechtliche Notwendigkeit für die Erfassung der Sekunden in der Zeitangabe? Finde ich unnötig.

**Comment by phoet** [comment]
das ist abhängig vom format des timepickers, der in deinem browser verwendet wird. hat das foto einen zeitstempel, dann müssen hier keine informationen zusätzlich ausgefüllt werden.
