### ISSUE TITLE
Abfrage zur Standzeit eines Fahrzeugs verbessern?

### ISSUE THREAD

**Issue by Natenom** [weg-li/weg-li#91]
Bei der Frage, wie lange das Auto schon parkte (3 min, 1h, 3h) könnte man dazu schreiben, ob das exclusiv ist oder ob man alles ankreuzen muss, wenn es z. B. 4 Stunden dort stand. Es sind keine Optionsfelder, also habe ich alles angekreuzt bis zur entsprechenden Dauer.

**Comment by phoet** [comment]
die standzeit wird demnächst anders abgespeichert werden.

**Comment by phoet** [comment]
das ist sogar teilweise schon fertig https://github.com/weg-li/weg-li/pull/95
