### ISSUE TITLE
PLZ automatisch ausfüllen anhand von Ort und Straße?

### ISSUE THREAD

**Issue by Natenom** [weg-li/weg-li#92]
Gerade in größeren Städten gibt es verschiedene PLZ je nach Straße. Das könnte man automatisiert eintragen. Vielleicht ist das auch schon so und bei mir nur nicht funktioniert, dann bitte einfach schließen.

**Comment by phoet** [comment]
wenn fotos die geo-coordinaten haben, dann wird die adresse automatisch ermittelt (so steht es auch im hinweisetext).

**Comment by Natenom** [comment]
Nicht jeder möchte Geolocation für Fotos anmachen oder hat die Möglichkeit gar nicht, weil er die Fotos mit einer normalen Kamera macht. In solchen Fällen muss man dann für jede Adresse umständlich selbst die PLZ raussuchen.

**Comment by phoet** [comment]
nein, man kann den map-picker nutzen.
