### ISSUE TITLE
Dateinamen verändern/anonymisieren fürs Versenden der E-Mail?

### ISSUE THREAD

**Issue by Natenom** [weg-li/weg-li#93]
Aktuell wird der Dateiname beim Hochladen beibehalten. Ich fände es besser, wenn dieser zumindest für die generierte E-Mail einen zufälligen Namen bekommen würde oder einen, der das Kennzeichen enthält oder sonstwas.

**Comment by phoet** [comment]
welchen zweck sollte das haben? die fotos heißen in der regel datum_zufallszahl.jpg

**Comment by Natenom** [comment]
Es dürfte nicht jedem bei der ersten Benutzung klar sein, dass der Dateiname erhalten bleibt. Ein abwägiges Beispiel wäre vielleicht, dass jemand das doofkopfnachbar_unter_mir3.jpg nennt.

Ich habe hier die Ansicht, dass nicht notwendige Daten nicht übertragen werden sollten. Ist natürlich deine Entscheidung.

**Comment by phoet** [comment]
für benutzer ist es verwirrend wenn ihre informationen aus irgendwelchen gründen verändert werden. daher würde ich so ein feature nur für sinnvoll erachten, wenn es aus irgendeinem grund notwendig ist oder einen hohen mehrwert hat.
