### ISSUE TITLE
Metadaten entfernen(?)

### ISSUE THREAD

**Issue by Natenom** [weg-li/weg-li#94]
Werden die Metadaten in den Dateien vor dem Versenden an die Behörde entfernt? Wenn nicht, wieso nicht? Die Behörden brauchen diese nicht und dann gibt es auch keine Notwendigkeit, diese mitzuschicken.

**Comment by phoet** [comment]
es steht dir frei diese informationen vor dem upload zu entfernen. den behörden wird ohnehin das original-foto zur verfügung gestellt, was dann auch die meta-daten wie hochgeladen enthält.
