### ISSUE TITLE
Marke „setra“ (Omnibus)

### ISSUE THREAD

**Issue by telewolf** [weg-li/weg-li#98]
Bitte in die Liste der Marken mit aufnehmen. Danke.

**Comment by phoet** [comment]
ggf im zuge eines umbaus für die unterscheidung von fahrzeugtypen

**Comment by telewolf** [comment]
Kann ich die Meldung trotzdem schon abschicken? Die Marke ist ein Pflichtfeld - oder?

**Comment by phoet** [comment]
nein, die marke und die farbe ist sollte kein pflichtfeld sein.

Am Fr., 1. Nov. 2019 um 16:07 Uhr schrieb telewolf <notifications@github.com
